### ISSUE TITLE
[Bug] Can't produce report from Grafana with credentials

### ISSUE THREAD

**Issue by abadyan-vonage** [IzakMarais/reporter#1]
I try to produce a report from my local grafana server. Installed reporter on the same machine as grafana (runs on port 3000).
When I try to generate the report, I get the following message in the log:
`GET /api/dashboards/db/call-cluster HTTP/1.1" 401 Unauthorized 26 bytes in 289u`
It doesn't matter if the dashboard exists or not.
This is because I need to somehow provide the reporter with credentials (in postman I get the same result until I provide basic authentication).

**Comment by IzakMarais** [comment]
This is a shorcoming; I have been very lax with authentication.

I run my Grafana with anonymous auth enabled in the grafana.ini to avoid dealing with it in API calls. 
```
[auth.anonymous]
# enable anonymous access
enabled = true

# specify organization name that should be used for unauthenticated users
;org_name = Main Org.

# specify role for unauthenticated users
org_role = Admin
```

You can try with these settings. 

I would be open to a PR that adds proper authentication support.

**Comment by adrianlzt** [comment]
I have opened this [PR](https://github.com/IzakMarais/reporter/pull/3) to allow auth.

You have to pass an API key as a parameter in the URL.

**Comment by ArcticSnowman** [comment]
#3  Fixes this..
