### ISSUE TITLE
Wrong Grafana IP specified

### ISSUE THREAD

**Issue by mafrancis** [IzakMarais/reporter#103]
Hi Sir,
I am planning to take a PDF report for my dashboard. I followed all your steps. but I am getting below error when I click the PDF icon. 

[root@inmonprd1 bin]# ./grafana-reporter
2018/12/10 13:37:06 grafana reporter, version: 2.1-0 hash: 997082a234c053fad981efaccf3f2332c6ba5ed2
2018/12/10 13:37:06 serving at ':8686' and using grafana at 'localhost:3000'
2018/12/10 13:39:54 Reporter called
2018/12/10 13:39:54 Called with api Token:
2018/12/10 13:39:54 Called without variable
2018/12/10 13:39:54 Called with dashboard: hofnQd-mk
2018/12/10 13:39:54 Called with time range: {now-5m now}
2018/12/10 13:39:54 Connecting to dashboard at http://localhost:3000/api/dashboards/uid/hofnQd-mk
2018/12/10 13:39:54 Error generating report: error fetching dashboard hofnQd-mk: error executing getDashboard request for http://localhost:3000/api/dashboards/uid/hofnQd-mk: Get http://localhost:3000/api/dashboards/uid/hofnQd-mk: dial tcp 127.0.0.1:3000: connect: connection refused

In Browser:-
error fetching dashboard hofnQd-mk: error executing getDashboard request for http://localhost:3000/api/dashboards/uid/hofnQd-mk: Get http://localhost:3000/api/dashboards/uid/hofnQd-mk: dial tcp 127.0.0.1:3000: connect: connection refused

My Dashboard Report URL - http://monitoring.otpp.com:8686/api/v5/report/hofnQd-mk?from=now-5m&to=now

Please help me to fix this issue.

**Comment by IzakMarais** [comment]
It seems like your Grafana serving at a different URL? From the log above:
> 2018/12/10 13:37:06 serving at ':8686' and **using grafana at 'localhost:3000'**
...
dial tcp 127.0.0.1:3000: connect: connection refused

From the readme:

> Running without any flags assumes Grafana is reachable at localhost:3000:
`grafana-reporter`
Query available flags:
`grafana-reporter --help`

Perhaps you should use the [ip](https://github.com/IzakMarais/reporter/blob/master/cmd/grafana-reporter/main.go#L31) command line option to specify the correct IP port combination for Grafana.

**Comment by mafrancis** [comment]
Hi Team,
This issue has been fixed now. But i have the other issue like... I got my PDF of my dashboard but its not comes in proper alignment
[EDP HEALTH CHECK MONITORING DASHBOARD REPORT.pdf](https://github.com/IzakMarais/reporter/files/2668367/EDP.HEALTH.CHECK.MONITORING.DASHBOARD.REPORT.pdf)

![dashboard](https://user-images.githubusercontent.com/45704301/49813753-26740880-fd36-11e8-8cc2-f90341aee87b.PNG)

Please help me how to align PDF same as dashboard. 
.

**Comment by mafrancis** [comment]
Hi Izak, I have issue with pdf alignment please can you help me with that.

**Comment by IzakMarais** [comment]
Is this a scripted dashboard or does it have dynamic number of rows based on the data? The reporter doesn't currently support those types of dashboards. It is also not clear whether it would be possible to do given the Grafana API. See #79.

I tested again on a test dashboard with a graph panel and two single stat boxes. The dashboad:
![dashboard](https://user-images.githubusercontent.com/8266640/50143095-65650980-02b4-11e9-95d3-fffac8ee147d.PNG)
The report:
![image](https://user-images.githubusercontent.com/8266640/50143058-41a1c380-02b4-11e9-98f8-dae2914e5622.png)

You can customise the layout of the report to an extent by providing your own LaTeX template. See the template section of the readme as well as #50.

**Comment by Baboy71** [comment]
I love it when people fix issues themselves but never explain what they did!!!

I have the same issue.  Grafana and reporter on the same server and used Docker to install and run.  First I found Grafana didnt like the url as shown in the video as it needs http://at the beginning but now I try I get the following message:

2019/01/07 12:36:00 Reporter called
2019/01/07 12:36:00 Called with api Token:
2019/01/07 12:36:00 Called with variable: var-Project [All]
2019/01/07 12:36:00 Called with dashboard: Y93vOd-mk
2019/01/07 12:36:00 Called with time range: {now-7d now}
2019/01/07 12:36:00 Connecting to dashboard at http://localhost:3000/api/dashboards/uid/Y93vOd-mk?var-Project=All
2019/01/07 12:36:00 Error generating report: error fetching dashboard Y93vOd-mk: error obtaining dashboard from http://localhost:3000/api/dashboards/uid/Y93vOd-mk?var-Project=All. Got Status 401 Unauthorized, message: {"message":"Unauthorized"}

any clues as to how to fix it?

**Comment by Baboy71** [comment]
I figured it out!!  I needed to add an api token to the URL I was calling

**Comment by concept-trainer** [comment]
> I figured it out!! I needed to add an api token to the URL I was calling

i have followed and stuck at this point can you advise how you generate and add api token to solve unauthorized access issue.
