### ISSUE TITLE
reporter don't take pov if user is not admin

### ISSUE THREAD

**Issue by konvergence** [IzakMarais/reporter#104]

**Comment by konvergence** [comment]
in this case, reporter take the default pov of the dashboard

**Comment by IzakMarais** [comment]
Can you please give a more detailed description with some examples.

**Comment by konvergence** [comment]
hi Izak,
Think that i not an issue on Reporter, but well an issue from grafana 5.4.x.
I rollback to  grafana 5.3.4 and all work fine.

With grafana 5.4.2 ou 5.4.3 le POV are not well passed to the links

**Comment by IzakMarais** [comment]
Great, thanks for sorting it out and reporting back here.
