### ISSUE TITLE
Problem with link creation

### ISSUE THREAD

**Issue by JulesLassara** [IzakMarais/reporter#106]
Hello, I just installed Grafana and Grafana Reporter via Docker.
Now, I'm trying to add the external link button like on the read.me's gif. I'm doing the same steps as the gif, the button is displayed, but nothing happen when I'm clicking on it. Is it normal ? I generated an API key too.

**Comment by IzakMarais** [comment]
Hi, 

Have you made any progress? 

The gif is not intended as an instruction manual but rather just an example. Can you open the report by typing the URL directly into a browser? Or download it with curl? Did you use the correct IP address for the docker?  Depending on how you configured your Docker networking that might change.

**Comment by JulesLassara** [comment]
Hello,

Yes sorry I didn't precise that. Only with the URL is working, and I can download the PDF with curl for example.
Do you think that the problem is coming from Docker's authorizations ? Do you have any tutorial to recommend me to learn ? I am still learning Docker.

**Comment by cpmbailey** [comment]
I think this may be related to Grafana 5.4 as have just started encountering this myself when it used to work in 5.3. Can't say this with full certainty but its the only change I can think of in and around the time that it stopped working.

**Comment by cpmbailey** [comment]
The issue seems to be that 5.4 is treating localhost:8686 as a relative link. If I prefix the link with http:// it works

**Comment by JulesLassara** [comment]
Great ! Thank you.

For more information about this problem, do not forget to inquire the api token in the URL with ?apitoken={your_api}. It isn't shown on the gif in the README.md.

Sorry, it might have grammar mistakes into my previous posts, english is not my native language.
