### ISSUE TITLE
Reporter works only from localhost

### ISSUE THREAD

**Issue by faveloso** [IzakMarais/reporter#107]
Dear,

I made the installation of the reporter, locally on the server it operates ok, generating the PDF file. But the problem is that opening Grafana from another IP does not connect to port 8686.

This is the result from localhost:
[root@zabbix-fv ~]# wget http://192.168.116.128:8686/api/v5/report/fiRoPiPmz?
--2019-01-22 12:31:05--  http://192.168.116.128:8686/api/v5/report/fiRoPiPmz?
Connecting to 192.168.116.128:8686... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/pdf]
Saving to: â€˜fiRoPiPmz?â€™

    [ <=>                                                                                                                       ] 130,572     --.-K/s   in 0s      

2019-01-22 12:31:29 (567 MB/s) - â€˜fiRoPiPmz?â€™ saved [130572]

The Grafana server is disabled Firewalld and Selinux:

[root@zabbix-fv ~]# systemctl status firewalld
â— firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)
[root@zabbix-fv ~]# getenforce
Disabled

Checking port 8686 from another server indicates that it is not responding.

[root@localhost ~]# nmap 192.168.116.128

Starting Nmap 6.40 ( http://nmap.org ) at 2019-01-22 13:01 -03
Nmap scan report for 192.168.116.128
Host is up (0.00044s latency).
Not shown: 996 filtered ports
PORT     STATE  SERVICE
22/tcp   open   ssh
80/tcp   open   http
443/tcp  closed https
3000/tcp open   ppp
MAC Address: 00:50:56:22:0D:FC (VMware)
Nmap done: 1 IP address (1 host up) scanned in 5.19 seconds

This server also has Firewalld and Selinux disabled

Please helpme.

Regards,

Fernando Veloso.

**Comment by IzakMarais** [comment]
Can you look at the reporter logs? Confirm that it is configured correctly to reach Grafana on the different server.

**Comment by yuanbit** [comment]
Hello,

I have the same problem that the grafana reporter only works on our local server.

Our main grafana dashboards are hosted by an external company. I tried to do as someone suggested in another post:

/root/go/bin/grafana-reporter -ip username:password@grafana_ip:3000

However, I got a timeout when trying to generate the report and I don't get any messages in the reporter log.

Is there a solution to this problem?

Thank you

**Comment by IzakMarais** [comment]
Yes, you would definitely need to populate the -ip parameter of the reporter with the ip and port where grafana is hosted. However, I don't think adding the username:password would work. For authentication you would need to use authentication tokens. 

There should at least be startup messages in the reporter log (where it confirms for example the IP settings as well as the input parameters for each call. You need to fix this first, in order to assist in debugging further.

**Comment by IzakMarais** [comment]
Assistance given, closing issue.
