### ISSUE TITLE
How to set the order panels get exported in?

### ISSUE THREAD

**Issue by domsch1988** [IzakMarais/reporter#108]
I'm currently enjoying your Tool quite a bit and the fact that it is Latex based is great for making templates.
I'm facing one issue though: How can i change the order my Panels get exportet in? It currently seems to somehow go by the Panels ID. Since i have Dashboards that where dynamically created over time, the ID doesn't match with where the Panel is placed on the page.

Is there any chance to change the order the panels appear in the report? It doesn't matter if it's in Grafana or Latex. I'm willing to do the solution by hand for every dashboard or create one PDF Template per Dashboard.

**Comment by IzakMarais** [comment]
> Is there any chance to change the order the panels appear in the report?

There is no support for this.

> It currently seems to somehow go by the Panels ID.

[This](https://github.com/IzakMarais/reporter/blob/master/report/report.go#L192) line of code passes a subset of the dashboard JSON returned by the Grafana API to the LaTeX template.  The subset is defined [here](https://github.com/IzakMarais/reporter/blob/master/grafana/dashboard.go#L62). If you've been customising templates you probably already know that the Dashboard's panels array is iterated over by the templating engine [here](https://github.com/IzakMarais/reporter/blob/master/report/texTemplate.go#L31). 

Which is all to say that the panels are rendered in the order they appear in the Dashboard JSON returned by the Grafana API. I am not entirely sure what internal rules Grafana uses to determine the order of the Panels in the JSON, but from your description it sounds like they are ordered by ID which gets bumped for each added panel. 

> I'm willing to do the solution by hand for every dashboard 

You could try exporting the dashboards from Grafana, editing the dashboard JSON by hand to change the Panel ID values (or order of the panels in the array) and then re-importing the panels. If you then export again and look at the order of panels in the array, you could see if your changes had the desired effect.

**Comment by domsch1988** [comment]
Thanks, i appreciate the fast feedback. I just tried ex- and importing while changing the ID's and also tried re-ordering the elements in the JSON File. Both sadly doesn't seem to affect the order they appear in in the export. I guess i'll be redoing the dashboard and creating the elements in exactly the order i need them in.

Also, while we're at it, can i change the Date Format for the Export? Currently it's "Mon Jan 28 13:20:23 CET 2019" but i'd only need the Date really. Dashboard or Grafana global Timezone don't seem to affect this.

**Comment by IzakMarais** [comment]
> Both sadly doesn't seem to affect the order they appear in in the export. 

That is too bad. 

Based on inspecting the dashboard structure, how do you think Grafana knows how to layout the panels? 

Regarding the data format: the _FromFormatted_ referenced in the [template](https://github.com/IzakMarais/reporter/blob/master/report/texTemplate.go#L28) calls [this](https://github.com/IzakMarais/reporter/blob/master/grafana/time.go#L72) function. So unless you wanted to check out the source code, modify and recompile, there is currently not an option to modify the date format.

**Comment by domsch1988** [comment]
> > Both sadly doesn't seem to affect the order they appear in in the export.
> 
> That is too bad.
> 
> Based on inspecting the dashboard structure, how do you think Grafana knows how to layout the panels?
> 
> Regarding the data format: the _FromFormatted_ referenced in the [template](https://github.com/IzakMarais/reporter/blob/master/report/texTemplate.go#L28) calls [this](https://github.com/IzakMarais/reporter/blob/master/grafana/time.go#L72) function. So unless you wanted to check out the source code, modify and recompile, there is currently not an option to modify the date format.

Holy, that worked! I just changed `.Format(time.UnixTime)` to `.Format("02.01.2006)` and recompiled it. Works as intended!

I have no clue by what logic the Panels get inserted. If it was by ID, i'd assume changing those it the JSON would yield the intended result, but it doesn't. I guess i'll dive into the code later today and see how this works. I might come up with a "workaround", that reads another property of the Panel, like the Name or a Variable or such, that i can set to some value in Grafana. Not sure if it is possible, but that's my current idea.

I think we can close this issue for now, as one thing is solved and the other not solvable atm. I'll report back though, when i come up with something.

**Comment by domsch1988** [comment]
Ok, i've come up with a "quick and dirty" solution that will work for me:
The reporter actually puts out the Panels in the order they are present in the JSON, disregarding the ID. Grafana, on Importing a JSON seems to dynamically reorder the Panels in the JSON based on something (no clue what). No matter the IDs or the Order i put the Panels in in the JSON, the result after import is always identical.

So for me, i added a oneliner, that sorts the Panels based on ID:
`sort.Slice(dash.Panels, func(i, j int) bool {return dash.Panels[i].Id < dash.Panels[j].Id})`
before `return dash` in the `populatePanelsFromV5JSON` function. This needs `"sort"` as an additional import.
Now, i can change the IDs in the JSON file, which are kept on import, and get the desired result. This seems to be a bit "wonky" with repeating rows, but works pretty much as intended.

By that logic, it "should" also be possible to sort by any other Property really. Since i need a solution that works with either Basic, or Repeating Dashboards, ID it is. But for static only Dashboards one could just as well sort by Title, or (maybe even more interesting) gridPos. I'm looking into adding the actual position to the Panels slice. This "might" Translate to repeating rows and such. Further Testing required though.

**Comment by IzakMarais** [comment]
Thanks for investigating this. Sorting by some position based property sounds like the ideal solution. I PR along those lines would be welcome.
