### ISSUE TITLE
grafana + reporte on container connection refused

### ISSUE THREAD

**Issue by IvoJakubovie** [IzakMarais/reporter#110]
Greetings!
 Can not generate pdf from dashboard. On server Ubuntu 16.4 runs two containers
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                                    NAMES
76777aa4bc56        izakmarais/grafana-reporter       "/usr/local/bin/graf…"   45 hours ago        Up 45 hours         0.0.0.0:8686->8686/tcp                                                   grafana-reporter
d5b4b7d5f8f1        adejoux/docker-influxdb-grafana   "/start.sh"              6 days ago          Up 6 days           0.0.0.0:3000->3000/tcp, 0.0.0.0:8083->8083/tcp, 0.0.0.0:8086->8086/tcp   test

URL on Grafana Links: http://zpubuntu01:8686/api/report/hesb1-nmon-report
Browswer http://zpubuntu01:3000/dashboard/db/hesb1-nmon-report?editview=settings
Report page http://zpubuntu01:8686/api/report/hesb1-nmon-report?from=now-24h&to=now
with content :
error fetching dashboard hesb1-nmon-report: error executing getDashboard request for http://localhost:3000/api/dashboards/db/hesb1-nmon-report: Get http://localhost:3000/api/dashboards/db/hesb1-nmon-report: dial tcp 127.0.0.1:3000: getsockopt: connection refused
Where am I making a mistake?
IJ

**Comment by IzakMarais** [comment]
>  tcp 127.0.0.1:3000: getsockopt: connection refused 

This seems like it related to container networking. It sounds like the reporter is configured to connect to grafana at localhost, but trying to do that inside a container wil not succeed if grafana is running in a different container. I would suggest providing an explicit IP for the grafana container and configuring the reporter with that. 

There might be other fancy container networking options; I am not an expert in those.

**Comment by IvoJakubovie** [comment]
Thank you, I'll be exploring - I'll write to you and resolve
IJ
