### ISSUE TITLE
Pass grafana host/ip as env variable when running grafana and grafana-reporter with docker-compose

### ISSUE THREAD

**Issue by yudarik** [IzakMarais/reporter#112]
Hi Izak,
I'm running Grafana and Grafana-Reporter using docker-compose behind Nginx reverse proxy.
Grafana is served from localhost/grafana-dashboard using Nginx that proxy_pass to http://grafana:3000/
Grafana Reporter is served from http://localhost/grafana-reporter/ using Nginx as well that proxy_pass to http://grafana-reporter:8686/api/v5/report/
Now I have a link on grafana to generate PDF using grafana-reporter that points to:
http://localhost/grafana-reporter/$reportsDashboard?apitoken=$reporterToken&from=now-30d&to=now
It looks that Nginx proxy the request as expected, but since grafana-reporter is running on static-network, it cannot reach localhost:3000 where it expects to reach grafana, since localhost points to itself as docker container where grafana-reporter leaves. The error I get from grafana-reporter is:
dial tcp 127.0.0.1:3000: getsockopt: connection refused

The question is, is there a way to pass Grafana IP/HOST to grafana-reporter container as Env variable, or is there some other way to run grafana-reporter with the IP flag using docker-compose.config file?
Thanks

**Comment by yudarik** [comment]
I've also tried to overwrite the default Dockerfile entrypoint with docker-compose command attribute as follows in my docker-compose.config.yml:
`version '3.4'
services:
   grafana-reporter:
      container_name: grafana-reporter
      command: bash -c "/usr/local/bin/grafana-reporter -ip=grafana:3000"
      networks:
        - static-network
      ports:
        - 8686:8686
      restart: always`

grafana-reporter logs says: 

> 2019/02/06 13:10:26 grafana reporter, version: 2.1-0 hash: 997082a234c053fad981efaccf3f2332c6ba5ed2
> 2019/02/06 13:10:26 serving at ':8686' and using grafana at 'localhost:3000'
So it looks like grafana-reporter is still expecting to find grafana on localhost:3000

**Comment by yudarik** [comment]
Finally I've found the way to pass "grafana" host to grafana-reporter container:
Since grafana-reporter has an entrypoint we can pass additional params to it using "command" attribute:

```
grafana-reporter:
      container_name: grafana-reporter
      command: -ip=grafana:3000
      networks:
        - static-network
      ports:
        - 8686:8686
      restart: always
```

**Comment by IzakMarais** [comment]
Glad you sorted it out. Thanks for letting us know. 

I don't use the docker compose for deploying, so I don't know all the options off hand. 

________________________________

**Comment by salvq** [comment]
@yudarik I am facing similar problem as you in the past, is there a way to use `docker run` i.e. pass arguments instead of compose ?

I am using currently docker run and host:
```
sudo docker run -d \
--name="exporter" \
--restart=unless-stopped \
--network="host" \
--user root \
izakmarais/grafana-reporter
```

 but this is bypassing HTTPS and getting connection via HTTP `http://ms.azure.device.com:8686/api/v5/report/ybG8WXyZz?apitoken=MYIPKEY`

I need HTTPS
`https://ms.azure.device.com/api/v5/report/ybG8WXyZz?apitoken=MYIPKEY`

[Nginx reverse proxy issue](https://github.com/IzakMarais/reporter/issues/189)

**Comment by yudarik** [comment]
Hi @salvq,
I'm not sure I've followed your question... What exactly are you trying to achieve? 
if you will find a way to pass --command along with "docker run -d..." as I did with the docker-compose.yaml, should this solve your problem?

**Comment by salvq** [comment]
@yudarik thanks for getting back and I appreciate your answer.

Here is my use case, running both Grafana and reporter on the same host (azure VM) and also running Nginx reverse proxy as a standard host service (not in docker).

Grafana runs in one docker instance and reporter on different docker instance, see below. This is the only way I was able to generate the link that create PDF report). However I am worry about the link using HTTP. I am logging in Grafana via `https://example.azure.com` therefore was expecting report link to be `https://example.azure.com/api/v5/report/ybG8WXyZz?apitoken=MYIPKEY`

How to create Grafana and Grafana reporter docker instances that will allow me to use `https://example.azure.com/api/v5/report/ybG8WXyZz?apitoken=MYIPKEY` and this link I will add to grafana dashboard ?

Thanks

**Grafana**
```
sudo docker run -d \
--name="grafana" \
--restart=unless-stopped \
--network=monitoring \
--ip 172.18.0.20 \
--net-alias=grafana \
--user root \
-p 3000:3000 \
-v /home/aqmp/config/grafana.ini:/etc/grafana/grafana.ini \
-v grafana-data:/var/lib/grafana \
grafana/grafana
```

**Reporter**
```
sudo docker run -d \
--name="exporter" \
--restart=unless-stopped \
--network="host" \
--user root \
izakmarais/grafana-reporter
```

**Nginx config**

```
server {

        root /var/www/example.azure.com/html;
        index index.html index.htm index.nginx-debian.html;

        server_name example.azure.com;

        location / {
                proxy_pass http://localhost:3000;
        }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.azure.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.azure.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = example.azure.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        listen [::]:80;

        server_name example.azure.com;
    return 404; # managed by Certbot


}
```

**Comment by yudarik** [comment]
What works for me, should work for you as well, since we share the same use case.
Here how I've solved the issue:
First of all, that's not a good idea to expose grafana reporter port 8686 to the entire word, that's why we use Nginx proxy....

1. Add a rule on your nginx config, that will proxy all request from /grafana-report/ to grafana-reporter api. Something like:

> location /grafana-report/ {
>       proxy_pass http://grafana-reporter:8686/api/v5/report/;
>  }

where grafana-reporter is the docker container name.

2. On your grafana dashboard, add a link to the PDF report that will look like:
[http://ms.azure.device.com/grafana-report/ybG8WXyZz?apitoken=MYIPKEY
](url)
That way, nginx will proxy all requests to /grafana-report/xyz to http://grafana-reporter:8686/api/v5/report/xyz

Hope this solves your use-case.

**Comment by salvq** [comment]
@yudarik thanks a lot for your valuable information, also regarding the ports (they are disabled in firewall however better as you suggested will be to not use -p at all and rather use --expose.

Just when I tried to put new location as you suggested I am getting an error and need to be honest I am not very good at nginx at all, just starting :) 

What do I need to do to make this config to work ? Do I need to create new folders or kind of condition within config file ?

> aqmp@aqmp:/var/www/ms.azure.device.com/html$ sudo nginx -t
> nginx: [emerg] host not found in upstream "grafana-reporter" in /etc/nginx/sites-enabled/ms.azure.device.com:13
> nginx: configuration file /etc/nginx/nginx.conf test failed
> aqmp@aqmp:/var/www/ms.azure.device.com/html$
> aqmp@aqmp:/var/www/ms.azure.device.com/html$ sudo nano /etc/nginx/sites-available/ms.azure.device.com


```
server {

        root /var/www/ms.azure.device.com/html;
        index index.html index.htm index.nginx-debian.html;

        server_name ms.azure.device.com;

        location / {
                proxy_pass http://localhost:3000;
        }

        location /grafana-report/ {
                proxy_pass http://grafana-reporter:8686/api/v5/report/;
        }


    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/ms.azure.device.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ms.azure.device.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = ms.azure.device.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        listen [::]:80;

        server_name ms.azure.device.com;
    return 404; # managed by Certbot


}
```

**Comment by yudarik** [comment]
Nginx cannot find grafana-reporter host....
Your grafana-reporter container is named "exporter" 

> `sudo docker run -d \
--name="exporter" \
--restart=unless-stopped \
--network="host" \
--user root \
izakmarais/grafana-reporter`

So you need to refer to the same exact name in your rule in nginx.conf:
`proxy_pass http://exporter:8686/api/v5/report/;`
The same goes for grafana container. Change your rule for `location /`to proxy to `http://grafana:3000;`

Hope this will work now

**Comment by salvq** [comment]
```
aqmp@aqmp:/etc/nginx$ sudo docker container ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                    NAMES
63a3fe3b7d6f        izakmarais/grafana-reporter   "/usr/local/bin/graf…"   12 seconds ago      Up 10 seconds       8686/tcp                 exporter
029304e4013b        grafana/grafana               "/run.sh"                7 days ago          Up 3 days           0.0.0.0:3000->3000/tcp   grafana
1d006ba6b0ab        amqp                          "python3 ./readIotHu…"   2 weeks ago         Up 3 days                                    amqp
189d6517cfa3        influxdb                      "/entrypoint.sh -con…"   3 weeks ago         Up 3 days           8086/tcp                 influxdb

```aqmp@aqmp:/etc/nginx$ sudo nano /etc/nginx/sites-enabled/ms.azure.device.com



        location /grafana-report/ {
                proxy_pass http://exporter:8686/api/v5/report/;
        }


aqmp@aqmp:/etc/nginx$ sudo nginx -t
nginx: [emerg] host not found in upstream "exporter" in /etc/nginx/sites-enabled/faurecia.westeurope.cloudapp.azure.com:13
nginx: configuration file /etc/nginx/nginx.conf test failed
aqmp@aqmp:/etc/nginx$

**Comment by salvq** [comment]
@yudarik I was able to run and move forward however still some issue, can you help please ?

I have to change nginx conf file to use localhost instead of container name (even alias net did not help, this is ok for now this I will solve later).

```
        location / {
                proxy_pass http://localhost:3000;
        }

        location /grafana-report/ {
                proxy_pass http://localhost:8686/api/v5/report/;
        }

```

However when I run the reporter container and put link in browser I am getting this errors in shell

**Link**
`https://ms.azure.devices.com/grafana-report/ybG8WXyZz?apitoken=myIPtokenSecret`


**Shell logging**
```
aqmp@aqmp:/etc/nginx$ sudo docker run \
> --name="exporter" \
> --net-alias=exporter \
> --restart=unless-stopped \
> --network=monitoring \
> -p 8686:8686 \
> --user root \
> izakmarais/grafana-reporter
2020/02/06 11:23:58 grafana reporter, version: 2.3-1 hash: 6cfc3e220dc4f8fc0175ae0ec8698d35546d8c10
2020/02/06 11:23:58 serving at ':8686' and using grafana at 'http://localhost:3000'
2020/02/06 11:23:58 SSL check enforced
2020/02/06 11:23:58 Using sequential report layout. Consider enabling 'grid-layout' so that your report more closely follow the dashboard layout.
2020/02/06 11:24:16 Reporter called
2020/02/06 11:24:16 Called with api Token: myIPtokenSecret
2020/02/06 11:24:16 Called without variable
2020/02/06 11:24:16 Called with dashboard: ybG8WXyZz
2020/02/06 11:24:16 Called with time range: {now-1h now}
2020/02/06 11:24:16 Connecting to dashboard at http://localhost:3000/api/dashboards/uid/ybG8WXyZz
2020/02/06 11:24:16 Error generating report: error fetching dashboard ybG8WXyZz: error executing getDashboard request for http://localhost:3000/api/dashboards/uid/ybG8WXyZz: Get http://localhost:3000/api/dashboards/uid/ybG8WXyZz: dial tcp 127.0.0.1:3000: getsockopt: connection refused
```
a this in web browser:
`error fetching dashboard ybG8WXyZz: error executing getDashboard request for http://localhost:3000/api/dashboards/uid/ybG8WXyZz: Get http://localhost:3000/api/dashboards/uid/ybG8WXyZz: dial tcp 127.0.0.1:3000: getsockopt: connection refused`

**Comment by salvq** [comment]
The only way how it works so far is to use **host network** instead of my **custom bridge** network. Do I have wrong bridged network setup or missing some settings that reporter does not works within custom network and also nginx reporting issues using hostnames values (need to use localhost), what to check ?

```
aqmp@aqmp:/etc/nginx$ sudo docker run --name exporter --restart=unless-stopped --network **"host"** -p 8686:8686 --user root izakmarais/grafana-reporter
WARNING: Published ports are discarded when using host network mode
2020/02/06 12:09:16 grafana reporter, version: 2.3-1 hash: 6cfc3e220dc4f8fc0175ae0ec8698d35546d8c10
2020/02/06 12:09:16 serving at ':8686' and using grafana at 'http://localhost:3000'
2020/02/06 12:09:16 SSL check enforced
2020/02/06 12:09:16 Using sequential report layout. Consider enabling 'grid-layout' so that your report more closely follow the dashboard layout.
2020/02/06 12:09:24 Reporter called
2020/02/06 12:09:24 Called with api Token: myIPtokenSECRET
2020/02/06 12:09:24 Called without variable
2020/02/06 12:09:24 Called with dashboard: ybG8WXyZz
2020/02/06 12:09:24 Called with time range: {now-1h now}
2020/02/06 12:09:24 Connecting to dashboard at http://localhost:3000/api/dashboards/uid/ybG8WXyZz
2020/02/06 12:09:24 Populated dashboard datastructure: {Title:Dashboard 1 Description: VariableValues: Rows:[] Panels:[{Id:73 Type:table Title:Last Status (3 days window) GridPos:{H:5 W:12 X:0 Y:0}} {Id:60 Type:grafana-piechart-panel Title: GridPos:{H:9 W:6 X:12 Y:0}} {Id:68 Type:graph Title: GridPos:{H:9 W:6 X:18 Y:0}} {Id:18 Type:graph Title:OEE trend GridPos:{H:6 W:12 X:0 Y:5}} {Id:4 Type:gauge Title: GridPos:{H:4 W:4 X:12 Y:9}} {Id:6 Type:gauge Title: GridPos:{H:4 W:4 X:16 Y:9}} {Id:15 Type:singlestat Title:Good Units GridPos:{H:2 W:4 X:20 Y:9}} {Id:71 Type:singlestat Title:Rejected Units GridPos:{H:2 W:4 X:20 Y:11}} {Id:39 Type:singlestat Title:Machine Available Time GridPos:{H:2 W:4 X:12 Y:13}} {Id:44 Type:singlestat Title:Expected Units GridPos:{H:2 W:4 X:16 Y:13}} {Id:58 Type:graph Title:Quality Trend GridPos:{H:5 W:4 X:20 Y:13}} {Id:12 Type:singlestat Title:Machine Running Time GridPos:{H:2 W:4 X:12 Y:15}} {Id:43 Type:singlestat Title:Produced Units GridPos:{H:2 W:4 X:16 Y:15}} {Id:72 Type:graph Title:Availability Trend GridPos:{H:5 W:4 X:12 Y:17}} {Id:13 Type:graph Title:Machine Cycle Time Trend GridPos:{H:5 W:4 X:16 Y:17}}]}
2020/02/06 12:09:24 Downloading image  73 http://localhost:3000/render/d-solo/ybG8WXyZz/_?from=now-1h&height=500&panelId=73&theme=light&to=now&width=1000
```

**Comment by yudarik** [comment]
Hey there,
Honestly I'm not a big expert in docker networks but, it sounds that grafana-reporter cannot reach out grafana at http://localhost:3000 since localhost refers it's it's internal reporter container network. Since docker containers are isolated environments, when you say localhost, it means container self localhost, and not the host (the linux host). So the way to communicate between containers, is to setup a "static-network" and call each container API, by http://[container name]:[exposed port]. In such way docker is managing the static network, and proxing the request between the relevant containers networks by their names. Again I'm not an expert, but that how I see it.
Now, I don't really like the "docker run" way to execute the containers, since you need to provide all the params inline. I do prefer docker-compose way, where you define all that in a docker-compose.yaml file.

So here's a snippet of my docker-compose.config.yaml that works for me:
```yaml
version: '3.4'

services:
   nginx:
      restart: always
      depends_on:
       - webapi
      ports:
       - 443:443
       - 80:80
      networks:
       - static-network
  
   grafana:
      container_name: grafana
      networks:
        - static-network
      ports:
        - 3000:3000
      restart: always
      volumes:
        - grafana_stor:/var/lib/grafana
      environment:
        - GF_ANALYTICS_REPORTING_ENABLED=false
        - GF_PATHS_PLUGINS=/data/grafana/plugins
        - GF_SERVER_DOMAIN=localhost
        - GF_SERVER_ROOT_URL=https://localhost/grafana-dashboard/
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_SECURITY_ALLOW_EMBEDDING=true
   
   grafana-reporter:
      container_name: grafana-reporter
      command: -ip=grafana:3000
      networks:
        - static-network
      ports:
        - 8686:8686
      restart: always

volumes:
   influxdb: {}
   grafana_stor: {}
  
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16

```

And here's part of my nginx.cong:
```conf
server {
  listen  80;
  charset utf-8;
  client_max_body_size 512M;
  proxy_send_timeout 600;
  send_timeout 600;
  location / {
    rewrite ^ https://$host$request_uri? permanent;
  }
  location /grafana-dashboard/ {
    proxy_pass http://grafana:3000/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_max_temp_file_size 0;
  }
  location /grafana-reporter/ {
    proxy_pass http://grafana-reporter:8686/api/v5/report/;
  }
}
```
Could be that since your Nginx is running as a service on the host, and not as a docker container, is the reason why it cannot resolve "exporter' host, since there is not such host on the host network. It's a host known only for the docker/docker-compose.
So I guess you will need to try running Nginx as a container instead to make it work.

**Comment by salvq** [comment]
Hi sir, thanks a lot for your valuable answer.

I will study your answer more deeply but running Nginx in docker I do think will solve the problem as you mention. Lesson learn for me is situation about localhost and it may not necessary mean linux host after all.

Thanks a again, so next round of try and fail... :)
