### ISSUE TITLE
Getting {"message":"Not found"}

### ISSUE THREAD

**Issue by cejac** [IzakMarais/reporter#115]
Hello, 

I have everything up and running, but when I click the report button a new window opens with "{"message":"Not found"}". 

My backend is served up on a different port. The link reflects the correct port, as 8686 will bring up connection error. Maybe I changed the port number incorrectly? Any help with this?

Sorry, sort of a newbie to all of this.

**Comment by IzakMarais** [comment]
> My backend is served up on a different port. 

On what port is it set up? Can you paste the log output of the granfa reporter service? Then we can ensure that the reporter is configured with the correct grafana IP.

**Comment by cejac** [comment]
HI! I got this working. I reconfigured the backend to serve on port :3333 (grafana-reporter -port :3333). 

Is there any instructions on pushing this up to github and working for our customers to also generate these pdf reports?

**Comment by IzakMarais** [comment]
> Is there any instructions on pushing this up to github and working for our customers to also generate these pdf reports?

I'm afraid you will have to elaborate; I do not understand this question.
