### ISSUE TITLE
Unauthorized message

### ISSUE THREAD

**Issue by clarelewis73** [IzakMarais/reporter#12]
Hi, I've been following your steps and i keep getting these errors when the dashboard is being generated:

2017/06/08 09:18:46 Error obtaining dashboard:  401 Unauthorized
2017/06/08 09:18:46 Error generating report: Error obtaining dashboard: {"message":"Unauthorized"}

I assume I need to change the credentials of something, any idea of a fix?

Thanks!

**Comment by IzakMarais** [comment]
You can either:
1. disable authentication on your Grafana instance (see the Grafana configuration), or 
2. you need to pass along the Grafana authentication API token as a querey paramater to grafana-reporter. The query paramter name is **apitoken**, as mentioned in the readme. You can obtain the token from the Grafana GUI.

**Comment by clarelewis73** [comment]
Hi, 

Any chance you have more step by step instructions for passing along the API token as a query?

Thanks

**Comment by IzakMarais** [comment]
Passing the apitoken as an HTTP GET [query paramter}(https://en.wikipedia.org/wiki/Query_string) will look something like:

    /api/report/<dashBoardName>&apitoken=<tokenstring>

where <dashBoarName> and <tokenstring> should be substituted with your desired values.
