### ISSUE TITLE
Maps Graphics not shown in PDF

### ISSUE THREAD

**Issue by fadjar340** [IzakMarais/reporter#122]
Hi All,

I just use the latest Grafana 6.2.0 and build the dashboard using World Maps Panel.
I installed the grafana-reporter and the process was succeeded, but only the maps graphics not shown.
I already add the apitoken also, so the PDF can showed up.

Is there any workaround to bring the maps graphics appears??

Regards,
Fadjar Tandabawana

**Comment by IzakMarais** [comment]
I have seen that often the third party plugin panels don't work properly with Grafana's _Share->Direct Link Rendered Image_ feature. You can test this using only the Grafana UI, by clicking on the panel in question and going to _Share_ then _Direct link rendered image_. I suspect that is the problem. If so, please log a bug at the panel author and link to this issue.

**Comment by DanieljuarezASIR** [comment]
Hola buenas, estoy usando docker y grafana y tengo la version v6.4.1 de grafana y no se que hacer para obtener el dashboard en pdf, Hice la parte de link y le puse /api/v5  tal y como pones. 
Me puedes decir como puedo implementarlo con esta version 6.4.1

**Comment by DanieljuarezASIR** [comment]
![image](https://user-images.githubusercontent.com/43546581/56603721-8d68ce80-6600-11e9-8fbf-87c86c1f029e.png)

**Comment by DanieljuarezASIR** [comment]
![image](https://user-images.githubusercontent.com/43546581/56603779-aec9ba80-6600-11e9-99a2-74560bf35657.png)

**Comment by IzakMarais** [comment]
The port numbers in your two screenshots differ: on which port is the reporter serving? If it is 8686, the top image is connecting to some other service.

These comments seem completely unrelated to this Maps Graphics issue. Please create a new issue if you want to discuss this further. 

Also, I am not a Spanish speaker, so please post questions in English if you want me to answer them.

**Comment by DanieljuarezASIR** [comment]
the problem then is at port 8080 ??  I'm going to the container docker  prometheus:9000
Grafana:3000
Cadvisor:8686
