### ISSUE TITLE
executable binary for reporter

### ISSUE THREAD

**Issue by srini3463** [IzakMarais/reporter#123]
Hi All,

Can someone please upload an executable binary for this project. Due to some restrictions my linux box doesn't have Internet connectivity, so i can not build/install directly on my linux machine.
I tried to install but getting the below error message:
go install /data1/monitoring/reporter-2.1.0/cmd/grafana-reporter
can't load package: package /data1/monitoring/reporter-2.1.0/cmd/grafana-reporter: import "/data1/monitoring/reporter-2.1.0/cmd/grafana-reporter": cannot import absolute path

I am completely new to Go Lang. Please upload an executable binary(linux-amd64) for reporter.

Thanks and appreciate your help.

**Comment by IzakMarais** [comment]
If you have already installed go your are halfway there. The following three commands, executed from any empty directory, should check out the repo and build it in no time.
```
λ export GOPATH=`pwd`
λ go get github.com/IzakMarais/reporter/...
λ go install -v github.com/IzakMarais/reporter/cmd/grafana-reporter
```
The `go get` creates a `src/` folder with the repo in. This is the only part that needs internet connectivity (and I would be surprised if it requires anything more than port 80 to be open -- if you can do `git clone`,  `go get` should also work). The `go install` creates a `bin` directory with the executable in:
```
λ ls
bin/  pkg/  src/
λ ls bin/
grafana-reporter
```

**Comment by srini3463** [comment]
Thanks for your help. git clone, go get are not working in my machine because of no internet connectivity. But I have compiled and created executable binary file for this project in some other linux machine(Using cloud) and copied to my work machine and it worked.

Now the issue is with pdflatex. Getting below error message  -
Error generating report: error calling LaTeX preprocessing: "exec: \"pdflatex\": executable file not found in $PATH". Latex preprocessing failed with output:

Can you please provide some instructions to install pdflatex on RHEL6

Thanks.

**Comment by srini3463** [comment]
I fixed the issue by installing texlive-latex package. It's working now.

Thanks.

**Comment by manoj-uv** [comment]
> I fixed the issue by installing texlive-latex package. It's working now.
> 
> Thanks.

hi srini3463 , 
can you mention the steps and process for fixing this ? installing texlive-latex package
