### ISSUE TITLE
Can't change link address

### ISSUE THREAD

**Issue by mattroell** [IzakMarais/reporter#125]
For the most part everything is working, the only issue that I have is with "Links" in the dashboard settings. If I key in anything before (an IP or host-name with or without the port) /api/v5/report/6..... the report icon won't do anything. However if I don't key in an IP or host-name the link opens a new tap, but then I need to port to 8686, which then creates the report. Has anyone encountered this before? 

Grafana v6.1.6

**Comment by IzakMarais** [comment]
I suggest you ask this on the Grafana project page, or maybe even on their community forms; you might get better help there. You could basically replace the reporter URL with any website URL to reproduce this issue. I haven't used links with 6.1.6 yet; would have to spin up a version to check it out.

**Comment by mattroell** [comment]
Perfect, I'll go a head and ask on Grafana's page.

Thanks,
