### ISSUE TITLE
Reporter behind reverse proxy

### ISSUE THREAD

**Issue by PeterTSI** [IzakMarais/reporter#127]
Hello, we are using the reporter in a rancher environment. It connects to grafana and if I call the report directly from the container with curl I get a result - even from another container.
But we are using the build in rancher HA proxy as a reverse proxy and if we request the same report then we get a "404 page not found" message. We are using here a subpath /report. I think it has something to do with the HA proxy configuration and that we have to set some e.g. headers parameters.
Do you have any experience with this proxy server and how can we solve our problem?

**Comment by IzakMarais** [comment]
I'm afraid that doesn't sound familiar to me. My guess is an error in your HAproxy configuration (noting to do with headers though). I would watch both the reporter and HAproxy logs to see if any requests are getting through to the reporter.

**Comment by PeterTSI** [comment]
What we found out now is that everything is working fine if we setup the reporter as root. If we are using it as a subpath /report then we get the 404. We will investigate further in the HA settings.
