### ISSUE TITLE
Error generating report: error fetching dashboard qbkyEdWmk: error obtaining dashboard from http://10.64.11.144:3030/api/dashboards/uid/qbkyEdWmk. Got Status 403 Forbidden, message: {"message":"Access denied to this dashboard"}

### ISSUE THREAD

**Issue by babarsumit93** [IzakMarais/reporter#129]
I'm getting below error while fetching report, I've given all permissions to the user for this dashboard.

 "Error generating report: error fetching dashboard qbkyEdWmk: error obtaining  dashboard from http://10.64.11.144:3030/api/dashboards/uid/qbkyEdWmk. Got Status 403 Forbidden, message: {"message":"Access denied to this dashboard"}"

**Comment by IzakMarais** [comment]
Are you using an apitoken and passing it along as a query parameter to the reporter?

**Comment by IzakMarais** [comment]
See the apitoken section of the readme.
