### ISSUE TITLE
Error obtaining dashboard: {"message":"Unauthorized"}

### ISSUE THREAD

**Issue by ridhoyp** [IzakMarais/reporter#13]
Hi i got an error while obtaining dashboad

Error obtaining dashboard: {"message":"Unauthorized"}

![image](https://user-images.githubusercontent.com/28750276/27252751-444b27cc-5390-11e7-93cd-ef31b8edde40.png)

Regards,
RidhoYP

**Comment by IzakMarais** [comment]
Please see https://github.com/IzakMarais/reporter/issues/12 for more detailed help in using Auth tokens if the steps from the readme are not clear enough.

**Comment by ridhoyp** [comment]
Hi ,

I already test it, but got no dashboard 

![image](https://user-images.githubusercontent.com/28750276/27277912-1462c486-550a-11e7-9b3d-fd8671a9896a.png)

here is the api generated

![image](https://user-images.githubusercontent.com/28750276/27277924-1f86568e-550a-11e7-95d3-b267911d4b82.png)

**Comment by clarelewis73** [comment]
Instead of a '&' before the apitoken in the URL, try a '?' 
That worked for me

**Comment by ridhoyp** [comment]
it worked, thanks so much
