### ISSUE TITLE
Graphs empty for different datasource expect single stat panel.

### ISSUE THREAD

**Issue by Optimusbumble** [IzakMarais/reporter#130]
I am using multi datasource to create dashboard for different panels where Panels are empty if i use other than grafana as datasource . But to my surprise i see it work for single stat panel alone.
Any thoughts on this ?

Note : It is also empty if i tried testing via direct renderer image.

Updated the actual issue after my findings..

**Comment by Optimusbumble** [comment]
Graphs are empty for non native graph panels..Any idea on this ?

**Comment by IzakMarais** [comment]
> Note : It is also empty if i tried testing via direct renderer image.
> Graphs are empty for non native grafana panels..Any idea on this ?

This is typical yes. Non-native panels need to correctly support the Grafana GUI feature "Share Direct Rendered Image", since that is what the reporter relies on render. 

I suggest you ask this question on the Grafana project, or the specific panel's project.
