### ISSUE TITLE
templates path issue

### ISSUE THREAD

**Issue by plane-jobs** [IzakMarais/reporter#132]
2019/06/20 17:17:36 Called with template: templates/1.tex
2019/06/20 17:17:36 Error reading template file: "open templates/1.tex: no such file or directory"
2019/06/20 17:17:36 Connecting to dashboard at http://localhost:3000/api/dashboards/uid/YleEB9nZk

[root@  templates]# pwd
/bin/templates
[root@ templates]# ll
total 8
-rw-r--r-- 1 root root 726 Jun 20 17:13 1.tex

Where is the path?

**Comment by IzakMarais** [comment]
Strange, I tested this again just to be sure and it worked fine for me:

```bash
T:\repos\reporter\bin  
λ ls
grafana-reporter.exe*

T:\repos\reporter\bin  
λ mkdir templates

T:\repos\reporter\bin  
λ touch templates\1.tex

T:\repos\reporter\bin  
λ .\grafana-reporter.exe
2019/06/20 14:00:41 grafana reporter, version: 2.1-0 hash: 997082a234c053fad981efaccf3f2332c6ba5ed2
2019/06/20 14:00:41 serving at ':8686' and using grafana at 'localhost:3000'
2019/06/20 14:00:45 Reporter called
2019/06/20 14:00:45 Called with api Token:
2019/06/20 14:00:45 Called without variable
2019/06/20 14:00:45 Called with dashboard: Y4N5w6pmk
2019/06/20 14:00:45 Called with time range: {now-1h now}
2019/06/20 14:00:45 Called with template: templates\1.tex
2019/06/20 14:00:45 Connecting to dashboard at http://localhost:3000/api/dashboards/uid/Y4N5w6pmk
...
```

Did you perhaps execute the reporter from a different directory? The assumption is that `templates` is a relative path. However, you can override it to any (possible absolute) path using the command line argument `-templates`.  See `grafana-reporter --help`

**Comment by plane-jobs** [comment]
think you ,Can be shown

**Comment by IzakMarais** [comment]
Assuming you meant "Thank you, can be closed".
