### ISSUE TITLE
docker image for arm platform

### ISSUE THREAD

**Issue by pacEPMS** [IzakMarais/reporter#138]
I'd like to use the grafana-reporter docker image on a arm (32bit) platform.
Does such an image exists or can you build one ?
This would be very helpful.

Thanks a lot !
pac

**Comment by IzakMarais** [comment]
Do you mean that the docker image should be deployable to an arm platform? Are all docker images not deployable to any platform? What changes would be required. 

Such an image does not exist. The docker support was added via a PR by a community member; I do not deploy using docker myself. I would be open for a PR if you want to do this.

**Comment by IzakMarais** [comment]
This is not going to happen unless someone does a PR for it.
