### ISSUE TITLE
location of tex template file

### ISSUE THREAD

**Issue by pacEPMS** [IzakMarais/reporter#139]
What is the location of the tex template file on the docker image ?

Thanks for Your info.
pac

**Comment by IzakMarais** [comment]
Using custom templates with the docker image is not something I have tested yet. 
The default location is in the `templates` directory relative to the reporter binary. You could customise that location using the reporter commandline parameters. 

See here for details on how to use custom templates. 
https://github.com/IzakMarais/reporter/issues/50
