### ISSUE TITLE
Panels not loading

### ISSUE THREAD

**Issue by clarelewis73** [IzakMarais/reporter#14]
When generating my report from grafana im getting lots of panels that havent loaded fully yet.

![image](https://user-images.githubusercontent.com/24431531/27389738-262cd614-5697-11e7-9181-6d8c95d3da25.png)

Any idea how I would go about giving them more time, i.e. sleep function?

Thanks

**Comment by clarelewis73** [comment]
To clarify, some of my panels in grafana need to include data from the last 7 days so takes a while to load

I know what the delay function should be, just not sure exactly where to put it.
It needs to go before the panels are converted to PNGs

Any help would be appreciated.

Thanks

**Comment by IzakMarais** [comment]
I suspect this is not within the control of the grafana-reporter; it tries to download the panels using the grafana render panel api. See https://github.com/IzakMarais/reporter/blob/master/grafana/api.go#L126

Can you try to download the panels directly via this api, e.g. using wget? If you can reproduce the timeout problems, the issue should be logged with the grafana project. E.g:

    wget http://<grafana location>/render/dashboard-solo/db/<dashboard-name>?from=now-1d&height=150&panelId=<panel id>&theme=light&to=now&width=300

You can get the panel id by going to grafana and viewing the panel fullscreen. The URL should now contain something like:

    ...?panelId=217&fullscreen

**Comment by IzakMarais** [comment]
In the linked issue someone reported adding a 2 second sleep between the times to fetch the panel resolved the issue. There is even a diff if you want to try out that fix?
