### ISSUE TITLE
Set Grafana IP in Docker Container

### ISSUE THREAD

**Issue by jag3773** [IzakMarais/reporter#140]
I'm not seeing how I can specify options to the `grafana-reporter` command using `docker run`.  What I'd like to do is setup an environment variable for the options to `grafana-reporter` so that they are picked up automatically in the container, without having to build and maintain my own docker image.  Is this possible but just undocumented?

Here is what I would like to run:

```
/usr/bin/docker run --rm --name grafana-reporter \
  -p 8686:8686 \
  -e "IP=grafana:3000"
  -e "PROTO=https"
  izakmarais/grafana-reporter:latest
```

Without this ability, it looks like I either have to insert docker-compose (like [this](https://github.com/IzakMarais/reporter/issues/112)) in the middle (which seems like a silly requirement) or build my own container image with a custom `ip` argument.

FWIW, this is the same pattern that Grafana uses, see https://grafana.com/docs/installation/docker/#configuration for reference.

It could be that this is possible but I can't figure out, in which case some documentation would be great.  Either way, some notes in the README that explain how to set the IP in a docker container would be helpful.

Thanks for your work and your help!

**Comment by IzakMarais** [comment]
To be honest the docker support was added by a community member via a PR. I don't use it in my production setup. I recall that is was possible to add commandline parameters somehow, but I can't rememeber the details now. When I test this PR (https://github.com/IzakMarais/reporter/pull/135) I will experiment a bit to see if I can figure something out. 

I would suggest you experiment and also search through the repo history for the issues related to the PRs that added docker support.

**Comment by IzakMarais** [comment]
I simply use the command as in the readme. This is already successfully passing an option, namely `--help` to the reporter. 

    docker run izakmarais/grafana-reporter --help

The same works for other cmd line options:

    docker run izakmarais/grafana-reporter -ip localhost:1234
    2019/07/18 07:13:44 grafana reporter, version: 2.1-0 hash: 997082a234c053fad981efaccf3f2332c6ba5ed2
    2019/07/18 07:13:44 serving at ':8686' and using grafana at 'localhost:1234'
