### ISSUE TITLE
Timerange in reporter pdf is always in UTC

### ISSUE THREAD

**Issue by pacEPMS** [IzakMarais/reporter#147]
On my dashboard the timerange is in MEST (UTC+2h) witch is correct to my localtime.
When I generate a grafana-reporter pdf via grafana http link then timerange in the pdf
is always in UTC ! Why does grafana-reporter not use the localtime zone like grafana ?

[GrafanaReporter.pdf](https://github.com/IzakMarais/reporter/files/3432425/GrafanaReporter.pdf)
![Grafana dashboard](https://user-images.githubusercontent.com/52577036/61890852-a6876100-af08-11e9-80ec-e548638de1c0.png)

**Comment by IzakMarais** [comment]
See this issue https://github.com/IzakMarais/reporter/issues/43, where the behaviour is discussed. The reporter uses the timezone of the server it runs on. 

Are your grafana and reporter perhaps on two different servers? Are you running the reporter in a docker?

**Comment by pacEPMS** [comment]
I set the timezone on both servers (docker container grafana and reporter). Now it works fine,
Thanks!

**Comment by IzakMarais** [comment]
Glad to hear it is working now. I have just added a section to the readme under "Time span" to clarify this behaviour.
