### ISSUE TITLE
How remove time range within the report

### ISSUE THREAD

**Issue by apichartcs7** [IzakMarais/reporter#148]
![Uploading Screen Shot 2562-07-31 at 16.31.42.png…]()

**Comment by IzakMarais** [comment]
You can modify the report (e.g. removing the time range) by using a custom LaTeX template. Note that you would need to understand LaTeX markup to achieve this by yourself.  See the **template** section under [query parameters](https://github.com/IzakMarais/reporter#query-parameters) in the readme.

**Comment by apichartcs7** [comment]
I got an idea now, thank you.
