### ISSUE TITLE
feature request send var-server=$servername and maybe orgId=$number

### ISSUE THREAD

**Issue by sorenje** [IzakMarais/reporter#15]
First of all thanks for this great code you have created, thumbs up.

I have tried to modify this to send variable var-server=$servername with, but it's not working, this will be very useful in my business as i can create automatic reports for our customers.

var-server (server) is a dropdown menu inside grafana where i can select my server(s) and generate a report of the server(s) selected.

the problem is that i just get a 404 error when trying to send http://fqdn:8085/api/report/my-dashboard?var-server=myservername (grafana-reporter is running on port 8085)

below is what i have tried, also i have added 2 sec sleep between each image fetch, this eliminates panels not loading.

```
--- report.go	2017-08-06 10:46:31.450634557 +0200
+++ ~/src/github.com/izakmarais/reporter/report.go	2017-08-04 15:56:20.212954694 +0200
@@ -25,9 +25,10 @@
 	"path/filepath"
 	"sync"
 	"text/template"
-
+	"time"
 	"github.com/izakmarais/reporter/grafana"
 	"github.com/pborman/uuid"
 )
 
 type Report struct {
@@ -35,6 +36,7 @@
 	time        grafana.TimeRange
 	texTemplate string
 	dashName    string
+	assetName	    string
 	tmpDir      string
 }
 
@@ -44,13 +46,14 @@
 	reportPdf     = "report.pdf"
 )
 
+
 // New creates a new Report. If texTemplate is empty, a default tex template is used.
-func New(g grafana.Client, dashName string, time grafana.TimeRange, texTemplate string) Report {
+func New(g grafana.Client, dashName string, assetName string, time grafana.TimeRange, texTemplate string) Report {
 	if texTemplate == "" {
 		texTemplate = defaultTemplate
 	}
 	tmpDir := filepath.Join("tmp", uuid.New())
-	return Report{g, time, texTemplate, dashName, tmpDir}
+	return Report{g, time, texTemplate, dashName, assetName, tmpDir}
 }
 
 // Generate returns the report.pdf file.  After reading this file it should be Closed()
@@ -105,12 +108,15 @@
 				return
 			}
 		}(p)
+	time.Sleep(time.Second * 2)
 	}
 
 	wg.Wait()
 	return
 }
 
+
+
 func (rep *Report) renderPNG(p grafana.Panel) error {
 	body, err := rep.gClient.GetPanelPng(p, rep.dashName, rep.time)
 	if err != nil {
@@ -163,7 +169,7 @@
 }
 
 func (rep *Report) runLaTeX() (pdf *os.File, err error) {
-	cmd := exec.Command("pdflatex", "-halt-on-error", reportTexFile)
+        cmd := exec.Command("pdflatex", "-halt-on-error", reportTexFile)
 	cmd.Dir = rep.tmpDir
 	outBytes, err := cmd.CombinedOutput()
 	log.Println("Calling LaTeX")
@@ -175,3 +181,7 @@
 	pdf, err = os.Open(rep.pdfPath())
 	return
 }


--- cmd/grafana-reporter/main.go	2017-08-06 10:46:31.423634174 +0200
+++ ~/src/github.com/izakmarais/reporter/cmd/grafana-reporter/main.go	2017-08-04 10:53:35.954877283 +0200
@@ -44,15 +44,15 @@
 	log.Printf("serving at '%s' and using grafana at '%s'", *port, *ip)
 
 	router := mux.NewRouter()
+	router.Queries("var-server", "{assetName}")
 	router.HandleFunc("/api/report/{dashName}", serveReport)
-
 	log.Fatal(http.ListenAndServe(*port, router))
 }
 
 func serveReport(w http.ResponseWriter, req *http.Request) {
 	log.Print("Reporter called")
 	g := grafana.NewClient(*proto+*ip, apiToken(req))
-	rep := report.New(g, dashName(req), time(req), texTemplate(req))
+	rep := report.New(g, dashName(req), assetName(req), time(req), texTemplate(req))
 
 	file, err := rep.Generate()
 	if err != nil {
@@ -72,6 +72,13 @@
 	log.Println("Report generated correctly")
 }
 
+func assetName(r *http.Request) string {
+        vars := mux.Vars(r)
+        a := vars["assetName"]
+        log.Println("Called with assetName:", a)
+        return a
+}
+
 func dashName(r *http.Request) string {
 	vars := mux.Vars(r)
 	d := vars["dashName"]
```

i really hope you can help me, and again thanks for this great code.

**Comment by IzakMarais** [comment]
Can you do a separate pull request just for the 2 second sleep? That sounds like a good fix that should address https://github.com/IzakMarais/reporter/issues/14.

So, if I understand correctly, you are trying to support [query parameters in templated dashboards](https://github.com/grafana/grafana/issues/1078#issuecomment-63458678). 

The  query parameters will need to be passed along to the code that fetches the panel pngs. See https://github.com/IzakMarais/reporter/blob/master/grafana/api.go#L126. Perhaps start by doing manual tests with curl to see wether the Grafana panel API supports the query parameters feature. 

Also, you shouldn't use the Queries() call to gorilla mux. From the [docs](http://www.gorillatoolkit.org/pkg/mux):

> All variables defined in the route are required, and their values must conform to the corresponding patterns. These requirements guarantee that a generated URL will always match a registered route -- the only exception is for explicitly defined "build-only" routes which never match.

Since this feature is optional, we don't want to force it as requirements for all calls to the report generator.

**Comment by sorenje** [comment]
Thanks for your reply.

it's a 2 sec sleep between each image fetch, i have tried to generate a rapport for 30+ servers with CPU, MEM, SWAP, LOAD, DISKIO, DISK SPACE , and it's working fine, it takes about 3 minutes to generate a report for 30+ servers. (no big deal for me as this will be in a cronjob)

yes i am trying to support query parammeters in templated dashboards and it's working fine inside grafana.

when i access grafana/dashboard/db/my-dashboard?orgId=2&var-server=myserver this will give me my dashboard with only one server, and i can do &var-server=myserver&var-server=myserver2 and this will give me dashboard with 2 servers.

what i would really like to to parse var-server=myserver to /api/report/my-dashboard so i can create a pdf report for each server (without creating a dashboard for each server)

grafana panel api supports this, when i access grafana/api/dashboards/db/my-dashboard?orgId=2&var-server=myserver it gives me only 1 server i requested.

```
server": {
                "selected": true,
                "text": "myserver",
                "value": "myserver"
}

```
what will you suggest i use instead of Queries() call to gorilla mux ?

I understand, but if you would like to help you can maybe create a test branch for this.

thanks for your help it's much appreciated.

**Comment by IzakMarais** [comment]
At the moment query parameters are used by the reporter service for 
1. time range
2. Auth API Token

For this feature I suggest that all other query parameters are passed along to the panel fetch API. E.g. you should
1. Extract the remaining query parameters and pass them as url.Values type to report.New() in stead of a string type you had. 
2. Add all these paramateres to the panel api request in https://github.com/IzakMarais/reporter/blob/master/grafana/api.go#L126

You can create a pull request against the master branch, I don't think there is a need for a test branch on my side?

**Comment by sorenje** [comment]
thanks again, i will try that

**Comment by sorenje** [comment]
got it working thanks a lot for your help, i am share if others want the diff you the code.

**Comment by IzakMarais** [comment]
OK, if you want to do a pull request, you can. Otherwise, glad to help.
