### ISSUE TITLE
Change in grafana URLs

### ISSUE THREAD

**Issue by aayush-ag21** [IzakMarais/reporter#151]
I am currently using Grafana v6.3.After doing all the prerequisites when I run pdf generator
I get the error:
error fetching dashboard rvLNW0OWz: error obtaining dashboard from http://localhost:3000/api/dashboards/db/rvLNW0OWz. Got Status 404 Not Found, message: {"message":"Dashboard not found"} 
Which is justified as my dashboard URL is http://<IP:PORT>/d/rvLNW0OWz
There is a difference in the URL /d/ and /db/.
How do I solve this?

**Comment by IzakMarais** [comment]
If your request is going to the Grafana API at `/api/dashboards/db` it means you are calling the reporter on the [Deprecated endpoint](https://github.com/IzakMarais/reporter#deprecated-endpoint) intended to support older Grafana installations. You should use the [current (v5) endpoint instead](https://github.com/IzakMarais/reporter#endpoint).

**Comment by aayush-ag21** [comment]
Thank you, I was able to successfully able to solve the problem.
