### ISSUE TITLE
Service "activating" but doesnt' start

### ISSUE THREAD

**Issue by JoshHilliker** [IzakMarais/reporter#152]
The service keeps starting, goes into "activating" status & never truly starts.  Here's the service file I'm using.   **Active: activating (start)** & it hangs here.    I've checked permissions.   what am I missing?   

[Unit]
Description=grafana-reporter

[Service]
User=root
Type=notify
Restart=on-failure
ExecStart=/root/go/bin/grafana-reporter -ip=iPaddress:3000 -ssl-check=false
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target

**Comment by IzakMarais** [comment]
Thanks for posting the resolution. Glad you got it working.
