### ISSUE TITLE
Install without INTERNET access

### ISSUE THREAD

**Issue by sycoweb** [IzakMarais/reporter#153]
Hi  (French user),
I have the same problem as https://github.com/IzakMarais/reporter/issues/77.
The dowloaded  ZIP don't includes "...../vendor/github.com/IzakMarais/....", and I don't have any Internet access except from my PC. So, the install process dies saying :
"... reporter-master/cmd/grafana-reporter/handler.go:30:2: cannot find package "github.com/IzakMarais/reporter/grafana" in any of:  /usr/lib/golang/src/reporter-master/vendor/github.com/IzakMarais/reporter/grafana (vendor tree)
..."
So, what's the way to install 'reporter' without Internet access from Grafana APP server ?
Thanks for any help.
Syco.

**Comment by IzakMarais** [comment]
Hmm, it depends on what the reasons for the constraint of "no internet access" is. For example, if you want to make your work build pipeline robust against internet outages, you could use something like [Artifactory](https://jfrog.com/artifactory/) to mirror golang dependencies and host output binary artifacts. 

However, if you really want to compile from the zip, that should be possible (I have just downloaded the zip from [here](https://github.com/IzakMarais/reporter/releases) and it _does_ contain the vendored dependencies).

Since this project uses vendoring and has the dependencies checked into source control, everything needed for a build is contained in the github repo. So once you have the repo contents (which is contained in the zip file) there should be no reason to download anything from the internet. 

The key to getting it working would be to ensure that your GOPATH is set up correctly and that you extract the zip file contents to the correct place there.  It should be extracted to $GOPATH/src/github.com/IzakMarais/reporter/. Then you should be able to run `go install ./...` from that directory.

**Comment by sycoweb** [comment]
> Hmm, it depends on what the reasons for the constraint of "no internet access" is. 

I mean, our plateforms are 'bunkerised', on (very) Big and touchy dataCenters, and so not allowed to have any link to/from Internet.

- I installed GOLANG and texlive-latex
- I undertood the mechanic of GOPATH & ROOTPATH, and this not solves the problem.

Even in your link (https://github.com/IzakMarais/reporter/releases) there is no directory ".../github.com/IzakMarais/...." as called in cmd/handler.go.
Regards.
Syco

**Comment by IzakMarais** [comment]
Can't you compile the binary on a dev machine with Internet access and then distribute the binary? That is what we do at my work (package the binary as an rpm). You can even cross compile easily with go of needed.


________________________________

**Comment by sycoweb** [comment]
Hi Izak,
Unfortunately, our huge company does not allow direct contact with the WEB.
Our thousands of workstations are industrialized and do not allow a use of development.
Hummm ... I will try a cross-compilation; ... but this process seems to me too artisanal for a viable use in production

> Can't you compile the binary on a dev machine with Internet access and then distribute the binary? That is what we do at my work (package the binary as an rpm). You can even cross compile easily with go of needed.

**Comment by IzakMarais** [comment]
This repo isn't intended to encapsulate production build processes; you will have to wrap your own around the it. At wprk I have used git subtree to wrap the opensource github repository and host the production bundling code on an internal private repository. 

 My company deploys to remote air-gapped sites, so the binary gets packaged as a systemd service, wrapped in an rpm, which in turn is hosted on an artifactory server from where it gets bundled for deployment in a yum repository on an iso disk. 


    On Thursday, August 29, 2019, 8:36:04 AM GMT+2, sycoweb <notifications@github.com> wrote:  
 
 
Hi Izak,
Unfortunately, our huge company does not allow direct contact with the WEB.
Our thousands of workstations are industrialized and do not allow a use of development.
Hummm ... I will try a cross-compilation; ... but this process seems to me too artisanal for a viable use in production


Can't you compile the binary on a dev machine with Internet access and then distribute the binary? That is what we do at my work (package the binary as an rpm). You can even cross compile easily with go of needed.

**Comment by IzakMarais** [comment]
> Even in your link (https://github.com/IzakMarais/reporter/releases) there is no directory ".../github.com/IzakMarais/...." as called in cmd/handler.go.

Go will look for imports like `a/b` at `$GOPATH/src/a/b`, so, as explained [above](https://github.com/IzakMarais/reporter/issues/153#issuecomment-525762343), you need to check out the repo (or unzip the archive) at the correct relative location (`$GOPATH/src/github.com/IzakMarais/reporter/`) for the compiler to resolve imports correctly.

**Comment by sycoweb** [comment]
Finally I got it!
My ZIP was https://github.com/IzakMarais/reporter/archive/master.zip
, and gave the arbo *** "reporter-master" ***.
BUT the compilation included some import from *** "reporter" ***, hard coded in ......./cmd/ grafana-reporter/handler.go.
- under /usr/lib/golang/src/github.com/IzakMarais/ : I moved the arbo ....../reporter-master to ....../reporter
=> compilation and installation is OK
- I had to install some missing packages (texinfo, texlive-pdftex-def, texlive-tetex, texlive-tetex-bin, texlive-pdftex-def, ...)

And the PDFs are now built!
==> It remains to automate the start of Reporter with GRAFANA.
Thank you.
Syco.

**Comment by IzakMarais** [comment]
Glad you got it working.

**Comment by vanimesh** [comment]
Hi it would be really helpful if we have steps to install on the systems where there is no internet.
