### ISSUE TITLE
Make Reporter return a helpful message at root

### ISSUE THREAD

**Issue by gasolanki120** [IzakMarais/reporter#154]
Hello @IzakMarais 
I have implemented this grafana reporting service to my localhost. I followed each step and successfully installed everything.Then I executed command and it ran successfully but when I access it using http://localhost:8686/ it gave me error like "404 page not found" in browser. 

For this I also put video link below. Please check it and let me know why do I get this kind of issue.
https://www.screencast.com/t/AoEP1pa47zr

Actually my aim is to integrate this reporting service in grafana cloud.

Please help me to fix it out this issue so I can move forward in grafana.

Thanks

**Comment by IzakMarais** [comment]
The reporter does not serve anything at the root URL endpoint '/', which is what you would get if you only specify a host and port. You need to specify the endpoint as documented under the [Generate a report](https://github.com/IzakMarais/reporter#generate-a-dashboard-report) section of the readme.

**Comment by gasolanki120** [comment]
Hi @IzakMarais 
Thanks for your prompt response. I am very thankful to you. I got success to generate report.

Thanks again.

**Comment by gasolanki120** [comment]
Hi @IzakMarais 
One more thing I want to ask you that can we set timeout of request to generate pdf because I use this service from grafana cloud instance. Now my dashboard takes too much time to render and when i call this service from dashboard to generate pdf it shows error in command prompt like:
"Error obtaining render for panel"

So can you please assist me to solve out this issue?

I will really appreciate your help.

Thanks

**Comment by IzakMarais** [comment]
There is no built in solution to the reporter to achieve this. You can try to edit the source code to wait longer between retrieving panels and see if that helps. Have a look at [this](https://github.com/IzakMarais/reporter/issues/149#issuecomment-521254806) comment and the ones after it for tips how to do that.

**Comment by jnovack** [comment]
I was stuck on this for a bit.  While testing, it was just easy to see if networking and this application was working by testing the root, to which I was getting issues (not sure if it was the networking, proxy or load-balancer).

As a simple health-check, I do believe it should at least return a `200 OK` at the root, maybe even the version string or link to the README on how to form the URL. 

Just something, so derps like me don't waste time diagnosing the something when nothing is wrong. :)

**Comment by IzakMarais** [comment]
@jnovack That is a good idea, thanks. A 200OK with a link to [this section](https://github.com/IzakMarais/reporter#endpoint) of the readme sounds fine.
