### ISSUE TITLE
JPG render

### ISSUE THREAD

**Issue by aayush-ag21** [IzakMarais/reporter#156]
Hey, 
As a lot of graphs do not provide support for JPG render, can we have a flag which if enabled, just queries the dashboards and creates a pdf report in a simple table format?

**Comment by IzakMarais** [comment]
Sorry, but JPG render is the only method Grafana exposes for querying dashboard panel contents. There is no method for getting e.g. the panel contents in tabular from. 

You are welcome to have a look at the Grafana HTTP API and correct me if I am wrong.
