### ISSUE TITLE
PDF output generated by dockerized version of reporter contains nonsensical characters

### ISSUE THREAD

**Issue by vasanthv6** [IzakMarais/reporter#159]
Hi,
I've installed the docker version of grafana reporter (https://hub.docker.com/r/izakmarais/grafana-reporter/) and its running as a service. The reporter connects to my Grafana dashboard and downlloads images, but the PDF file that is generated contains non-sensical characters instead of the actual text used for the graph names, and the legends under the x and y axes. Only the title page is coming out correctly.

See this screenshot:

![image](https://user-images.githubusercontent.com/55719674/65467459-10e45100-de27-11e9-94ee-536c2c638d31.png)

Any idea what's causing the letters and numbers to appear garbled?

This is the command I'm running to issue a request to the reporter:

curl http://grafanareporter.default.svc.cluster.local:8686/api/v5/report/rN1_wCdWz?apitoken=eyJrIjoiOTZhVEtxYVVwSzJNQ2U1ZzVZZzBJYUlxaDZJNVdrczMiLCJuIjoiYXBpIiwiaWQiOjF9 > cmdperf.pdf

This is the log output I get when running the  tool. It does say that the report generation succeeded.

2019/09/23 20:50:01 Connecting to dashboard at https://10.99.37.181:32000/api/dashboards/uid/rN1_wCdWz
2019/09/23 20:50:01 Populated dashboard datastructure: {Title:CMDPerf Description:CMD Performance Metrics VariableValues: Rows:[] Panels:[{Id:14 Type:graph Title:Device table growth rate} {Id:12 Type:graph Title:Device deletion rate} {Id:10 Type:graph Title:Device creation rate} {Id:8 Type:graph Title:Number of users} {Id:6 Type:graph Title:Number of deleted devices} {Id:4 Type:graph Title:Number of active (not deleted) devices} {Id:2 Type:graph Title:CMD device count}]}
2019/09/23 20:50:01 Downloading image  14 https://10.99.37.181:32000/render/d-solo/rN1_wCdWz/_?from=now-1h&height=500&panelId=14&theme=light&to=now&width=1000
2019/09/23 20:50:01 Downloading image  12 https://10.99.37.181:32000/render/d-solo/rN1_wCdWz/_?from=now-1h&height=500&panelId=12&theme=light&to=now&width=1000
2019/09/23 20:50:01 Downloading image  10 https://10.99.37.181:32000/render/d-solo/rN1_wCdWz/_?from=now-1h&height=500&panelId=10&theme=light&to=now&width=1000
2019/09/23 20:50:01 Downloading image  8 https://10.99.37.181:32000/render/d-solo/rN1_wCdWz/_?from=now-1h&height=500&panelId=8&theme=light&to=now&width=1000
2019/09/23 20:50:01 Downloading image  6 https://10.99.37.181:32000/render/d-solo/rN1_wCdWz/_?from=now-1h&height=500&panelId=6&theme=light&to=now&width=1000
2019/09/23 20:50:02 Downloading image  4 https://10.99.37.181:32000/render/d-solo/rN1_wCdWz/_?from=now-1h&height=500&panelId=4&theme=light&to=now&width=1000
2019/09/23 20:50:02 Downloading image  2 https://10.99.37.181:32000/render/d-solo/rN1_wCdWz/_?from=now-1h&height=500&panelId=2&theme=light&to=now&width=1000
2019/09/23 20:50:03 Calling LaTeX - preprocessing
2019/09/23 20:50:04 Calling LaTeX and building PDF
2019/09/23 20:50:04 Extracted filename from dashboard title:  CMDPerf.pdf
2019/09/23 20:50:04 Report generated correctly

**Comment by vasanthv6** [comment]
And in case it helps, I copied the .pdf file that is produced from a linux environment onto a windows environment and I'm trying to view it using Acrobat in windows.

**Comment by vasanthv6** [comment]
When I point my browser to the URL below from which the reporter is downloading each image, the graphs appear in my browser with the same garbled characters. 
Yet in the main Grafana dashboard page, all the graphs all appear normal with proper text. Is there a grafana setting I need to tweak here or use a different URL than the below?
https://10.99.37.181:32000/render/d-solo/rN1_wCdWz/_?from=now-1h&height=500&panelId=8&theme=light&to=now&width=1000

**Comment by vasanthv6** [comment]
Issue resolved by updating to the latest version of Grafana.

**Comment by IzakMarais** [comment]
Thanks for reporting back with a solution.

**Comment by kkashyap1707** [comment]
Issue till exist. I am using the latest version of Grafana. Grafana v6.7.3 (a04ef6cefc)

After generating the report using docker it looks so wierd.

[keshavGrafana_1.pdf](https://github.com/IzakMarais/reporter/files/4630300/keshavGrafana_1.pdf)

Below is the screenshot of my grafana dashboard.

![Screenshot from 2020-05-15 00-20-14](https://user-images.githubusercontent.com/4715140/81973524-e0655780-9641-11ea-8e1f-612ee8bc5f94.png)

Please have a look and suggest.

**Comment by kkashyap1707** [comment]
@IzakMarais Please suggest.
