### ISSUE TITLE
LaTeX font problems

### ISSUE THREAD

**Issue by sanchomuzax** [IzakMarais/reporter#163]
I don't understand, what is the problem? Could you help me? Thank you!

The pdflatex is installed:

~~~
which pdflatex
/usr/bin/pdflatex
~~~

I tried it with cli, see end of the logs:

~~~
...
2019/10/15 22:03:06 Downloading image  14 http://localhost:3000/render/d-solo/QJgTn0Fmz/_?from=now-1w&height=500&panelId=14&theme=light&to=now&width=1000
2019/10/15 22:03:09 Calling LaTeX - preprocessing
2019/10/15 22:03:09 Error generating report: error calling LaTeX preprocessing: "exit status 1". Latex preprocessing failed with output: This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013)
 restricted \write18 enabled.
entering extended mode
(./report.tex
LaTeX2e <2011/06/27>
Babel <v3.8m> and hyphenation patterns for english, dumylang, nohyphenation, lo
aded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo
kpathsea: Running mktextfm cmr10
/usr/share/texlive/texmf/web2c/mktexnam: Could not map source abbreviation  for cmr10.
/usr/share/texlive/texmf/web2c/mktexnam: Need to update ?
mktextfm: Running mf \mode:=ljfour; mag:=1; nonstopmode; input cmr10
/usr/bin/mktextfm: line 96: mf: command not found
grep: cmr10.log: No such file or directory
mktextfm: `mf \mode:=ljfour; mag:=1; nonstopmode; input cmr10' failed to make cmr10.tfm.
kpathsea: Appending font creation commands to missfont.log.

! Font OT1/cmr/m/n/10=cmr10 at 10.0pt not loadable: Metric (TFM) file not found
.
<to be read again>
                   relax
l.64 \normalsize

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on report.log.
~~~

**Comment by Didr** [comment]
Are you using a custom LaTeX template?
What OS are you running this on?

**Comment by sanchomuzax** [comment]
> Are you using a custom LaTeX template?

I don't knwo, I think no.

> What OS are you running this on?

CentOS

**Comment by lynnsummersmell** [comment]
Helo,
I have the met some problem like this,error log as below:
error calling LaTeX preprocessing: "exit status 1". Latex preprocessing failed with output: This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./report.tex
LaTeX2e <2018-12-01>
(/opt/TinyTeX/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/opt/TinyTeX/texmf-dist/tex/latex/base/size10.clo))
(/opt/TinyTeX/texmf-dist/tex/latex/graphics/graphicx.sty
(/opt/TinyTeX/texmf-dist/tex/latex/graphics/keyval.sty)
(/opt/TinyTeX/texmf-dist/tex/latex/graphics/graphics.sty
(/opt/TinyTeX/texmf-dist/tex/latex/graphics/trig.sty)
(/opt/TinyTeX/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/opt/TinyTeX/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/opt/TinyTeX/texmf-dist/tex/latex/geometry/geometry.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/opt/TinyTeX/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
No file report.aux.
(/opt/TinyTeX/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/opt/TinyTeX/texmf-dist/tex/latex/oberdiek/grfext.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/kvdefinekeys.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)))
(/opt/TinyTeX/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty)
(/opt/TinyTeX/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex

! Package inputenc Error: Unicode character 物 (U+7269)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.11 \maketitle
               
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on report.log.

**Comment by lynnsummersmell** [comment]
cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by lynnsummersmell** [comment]
is seems that there is sth wrong in pdfTeX Or fonts?

**Comment by lynnsummersmell** [comment]
hope to get help,thanks!

**Comment by IzakMarais** [comment]
@lynnsummersmell: maybe this comment helps: https://github.com/IzakMarais/reporter/issues/46.

**Comment by IzakMarais** [comment]
@sanchomuzax : have you had success in solving this issue? This is definitely related to your LaTeX installation. See @Didr 's recommended method for using your Linux distro's package manager to ensure you have all the different LaTeX packages required.

**Comment by sanchomuzax** [comment]
Yes, tahnk you for your feedback! I tried it and solved my problems: https://gist.github.com/melvincabatuan/350f86611bc012a5c1c6

**Comment by lynnsummersmell** [comment]
> @lynnsummersmell: maybe this comment helps: #46.

thanks for your suggest,i tried to change my os language to zh_CH.UTF-8,still the same error..
![image](https://user-images.githubusercontent.com/39004114/69788282-2005c780-11f9-11ea-9549-38211df68848.png)

**Comment by lynnsummersmell** [comment]
2019/11/28 08:05:12 Downloading image  158 http://10.26.196.179:3000/render/d-solo/pO0gHO1Wz/_?from=now-24h&height=500&panelId=158&theme=light&to=now&width=1000
2019/11/28 08:05:12 Downloading image  156 http://10.26.196.179:3000/render/d-solo/pO0gHO1Wz/_?from=now-24h&height=500&panelId=156&theme=light&to=now&width=1000
2019/11/28 08:05:21 Calling LaTeX - preprocessing
2019/11/28 08:05:21 Error generating report: error calling LaTeX preprocessing: "exit status 1". Latex preprocessing failed with output: This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./report.tex
LaTeX2e <2018-12-01>
(/opt/TinyTeX/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/opt/TinyTeX/texmf-dist/tex/latex/base/size10.clo))
(/opt/TinyTeX/texmf-dist/tex/latex/graphics/graphicx.sty
(/opt/TinyTeX/texmf-dist/tex/latex/graphics/keyval.sty)
(/opt/TinyTeX/texmf-dist/tex/latex/graphics/graphics.sty
(/opt/TinyTeX/texmf-dist/tex/latex/graphics/trig.sty)
(/opt/TinyTeX/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/opt/TinyTeX/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/opt/TinyTeX/texmf-dist/tex/latex/geometry/geometry.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/opt/TinyTeX/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
No file report.aux.
(/opt/TinyTeX/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/opt/TinyTeX/texmf-dist/tex/latex/oberdiek/grfext.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/kvdefinekeys.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)))
(/opt/TinyTeX/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty)
(/opt/TinyTeX/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex

! Package inputenc Error: Unicode character 物 (U+7269)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.11 \maketitle

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on report.log.

==============
lilin0607@TPL-0000-163173  ~/ANSIBLE/GrafanaReport  locale
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:en_US:en
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
 lilin0607@TPL-0000-163173  ~/ANSIBLE/GrafanaReport 
