### ISSUE TITLE
Error "cannot unmarshal number"

### ISSUE THREAD

**Issue by jmsierra** [IzakMarais/reporter#168]
hi there,

When I try to generate a report, it's throwing this error:
`2019/11/14 13:00:55 Connecting to dashboard at http://**********:3000/api/dashboards/uid/Df07VyJWk?var-measures=bugs&var-measures=duplicated_blocks&var-measures=duplicated_lines_density&var-measures=vulnerabilities&var-project=*********&var-project=*********&var-project=*********&var-project=*********-catalog&var-project=*********-osv&var-version=4.0.0-SNAPSHOT
2019/11/14 13:00:55 http: panic serving *********:53401: json: cannot unmarshal number 4.8 into Go struct field GridPos.w of type int
goroutine 76 [running]:
net/http.(*conn).serve.func1(0xc4200d3540)
        /usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x7506e0, 0xc420418370)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/IzakMarais/reporter/grafana.NewDashboard(0xc42044e000, 0x5706, 0x7e00, 0xc42041bc20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/IzakMarais/reporter/grafana/dashboard.go:91 +0x201
github.com/IzakMarais/reporter/grafana.client.GetDashboard(0xc42041d2e0, 0x18, 0xc42041d300, 0xc42041d320, 0xc4200ed2e6, 0x60, 0xc42041bc20, 0x1, 0xc4200ed2d3, 0x9, ...)
        /go/src/github.com/IzakMarais/reporter/grafana/api.go:116 +0x949
github.com/IzakMarais/reporter/grafana.(*client).GetDashboard(0xc420229ec0, 0xc4200ed2d3, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        <autogenerated>:12 +0xb3
github.com/IzakMarais/reporter/report.(*report).Generate(0xc4201eb2d0, 0xc420229ec0, 0xc4200ed2d3, 0x9, 0xc4200ed34c)
        /go/src/github.com/IzakMarais/reporter/report/report.go:78 +0x5d
main.ServeReportHandler.ServeHTTP(0x7cbb08, 0x7cbb20, 0x93cf00, 0xc4200e48c0, 0xc4202aad00)
        /go/src/github.com/IzakMarais/reporter/cmd/grafana-reporter/handler.go:57 +0x2e5
main.(*ServeReportHandler).ServeHTTP(0xc4200613c0, 0x93cf00, 0xc4200e48c0, 0xc4202aad00)
        <autogenerated>:3 +0x74
github.com/IzakMarais/reporter/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200580e0, 0x93cf00, 0xc4200e48c0, 0xc4202aad00)
        /go/src/github.com/IzakMarais/reporter/vendor/github.com/gorilla/mux/mux.go:159 +0x101
net/http.serverHandler.ServeHTTP(0xc4200982c0, 0x93cf00, 0xc4200e48c0, 0xc4202aab00)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4200d3540, 0x93d5c0, 0xc420229b40)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce
`

I believe the problem is related to a conversion of this:
`"gridPos": {
        "h": 3,
        "w": 4.8,
        "x": 0,
        "y": 1
      },`

As "w" is not a int, but a float. 

I'm using latest docker version.
Many thanks,
Juanma

**Comment by IzakMarais** [comment]
@dwitzig this looks like a corner case related to https://github.com/IzakMarais/reporter/pull/164. Any chance that you could have a look at it?

**Comment by jmsierra** [comment]
I believe it's in file grafana/dashboard.go, lines 53-58:
`type GridPos struct {
        H int `json:"h"`
        W int `json:"w"`
        X int  `json:"x"`
        Y int `json:"y"`
}`

**Comment by dwitzig** [comment]
Sure I can take a look. Should not be an issue changing to a float.
Grafana panels snap to 24 column grid system so I did not think panel size could be a float

**Comment by IzakMarais** [comment]
Thanks! 

Yes it does seem surprising. It would be nice to add a test for this case as well.

**Comment by IzakMarais** [comment]
@dwitzig's PR has been merged and the fix is available in the latest release, v2.3.1.
