### ISSUE TITLE
Feature request: change graph when generating PDF

### ISSUE THREAD

**Issue by Zhenye-Na** [IzakMarais/reporter#169]
Hi @IzakMarais 

Thank you for making this project and we just used it and this is perfect for our own usage. As for a follow up, we may need one more feature.

I think it may be better to reach out to you first before we modified the code-base or even making PR in the future if this feature can be implemented.

We plan to modified the grafana dashboard graph when downloading the image from dashboard. Currently, I think this project is to download the images in parallel and then "insert" to the pdf generated by latex. We would like to achieve that before downloading the image, is there any way to modify the graph, ie, maybe there are 5 data points in this chart but we only want the most recent 4 or the data which differs from previous stage.

I am seeking your advice and to see if this can be realized by modifying your awesome project.

Thank you so much for your time!

👍

**Comment by IzakMarais** [comment]
Hi, 

Thanks for the compliments, I am glad you found it useful. I am always interested to know where it is being used. 

As for the request; I don't quite understand the use case you describe. The only way to control the rendered graphs is via the time range specified. Will this help you?

**Comment by Zhenye-Na** [comment]
Sorry for the confusion, it is a little bit tricky to express the idea. The thing is currently we would like to create a weekly report for our grafana board. But we expect (not require just to see if it is possible) the graph rendered or generated in the pdf report is not the same as grafana dashboard. We may wanna tweak some charts to hide some field and only display the field we are interested in.

But concerning you were saying that the only way to control in the `timespan` parameter we have, so I am thinking maybe is is not possible to do that?

**Comment by Zhenye-Na** [comment]
Also, we would like to try change the template for our own usage. But I did not find the `templates/templateName.tex` file nor the `texTemplate.go`. Are those files created by ourselves or it is in the project but I did not find them.

Thank you for your time and contribution again.

**Comment by Zhenye-Na** [comment]
never mind, find this useful issue https://github.com/IzakMarais/reporter/issues/50#issuecomment-378956538

**Comment by IzakMarais** [comment]
There are links to issues from the readme on how to change to provide a custom template. 
 > We may wanna tweak some charts to hide some field and only display the field we are interested in.
No this is not possible. The simplest way to do this would be to create a second dashboard that you use only to drive the report.
