### ISSUE TITLE
Add support for Pie Charts

### ISSUE THREAD

**Issue by cailen** [IzakMarais/reporter#17]
The reporter seems to fail on pie charts. Any advice on if these are able to be populated?

**Comment by IzakMarais** [comment]
Sorry, I developed the reporter before pie charts where introduced. If someone wants to do a pull request I'll, that would be great.

**Comment by clarelewis73** [comment]
You need to add a function for pie charts.

If you add in dashboard.go something like:

func (p Panel) IsPieChart() bool {
         if p.Type == "piechart" {
                  return true
         }
         return false 
}


I.e. Make it the same as the single stat one (you can add anything this way, any type of panel, or a particular panel ID etc.


Then in the texTemplate.go code. Add in a line after the singlestat function that is something like

[[else if .IsPieChart]]\begin{minipage}
\includegraphics etc etc
\end{minipage}


Hope that helps! I'm afk for until next week but I have a completely working code that doesn't have any timeouts any more, if you need a look of anything give me a shout!

Cheers

**Comment by IzakMarais** [comment]
@clarelewis73 Thanks for the feedback. A pull request would be much appreciated.

**Comment by clarelewis73** [comment]
No problem, when I'm back in the office I'll do it!

**Comment by IzakMarais** [comment]
Opened an issue with the grafana project, since I suspect PNG rendering support for plugin panels is lacking.

**Comment by JCN-9000** [comment]
I have Piecharts and Donuts working in my reports since I started using reporter.

**Comment by IzakMarais** [comment]
@JCN-9000 Interesting, which version of Grafana are you using? Sharing PNGs of pie charts is definitely not working in Grafana v5.0.0. (See linked issues in grafana/grafana and grafana/piechart-panel repos).

**Comment by JCN-9000** [comment]
@IzakMarais , production server is still on grafana-4.6.3-1 and Pie Chart plugin 1.1.5. 
I'v been lucky since PieChart indeed does not display unless you put the Legend on the Right Side, which is the only position that allows the panel to be downloaded and that was my choice when creating the dash, so it never happened to get into this Bug.

**Comment by IzakMarais** [comment]
OK, thanks for confirming. This is definitely not a problem with the grafana-reporter then. It should resolve once https://github.com/grafana/piechart-panel/issues/131 has been fixed.
