### ISSUE TITLE
Add latex packages to docker

### ISSUE THREAD

**Issue by beerygaz** [IzakMarais/reporter#172]
Is there a way to add additional latex packaged to the docker container so we can further customise the templates?

**Comment by IzakMarais** [comment]
I am not sure, the docker support has been added by other contributors. Presumably you should be able to use the docker [FROM](https://docs.docker.com/engine/reference/builder/#from) syntax to build your own image based on the existing one.

@sbaier1, do you have any tips?

**Comment by beerygaz** [comment]
@IzakMarais - Inexperience with Latex and Docker were to blame.  We've created our own docker container with the latex packages we need and it's working like a dream.
