### ISSUE TITLE
Table outputted to PDF missing half the table

### ISSUE THREAD

**Issue by lynskey08** [IzakMarais/reporter#176]
Hi Izak,
I've been having a problem with the output of the pdf data from my dashboard.
I have a table that has 22 rows, but when I export it to PDF, half the table data 
gets cut off. Here are screenshots to give you an idea of what's happening.<br>
Original table:<br>
<img width="527" alt="OriginalTable" src="https://user-images.githubusercontent.com/10612590/70801916-00010700-1da8-11ea-986c-ce4f8e0a7023.PNG">
<br>
Outputted PDF Table:<br>
<img width="306" alt="TablePDFOutput" src="https://user-images.githubusercontent.com/10612590/70801948-160ec780-1da8-11ea-854f-eba8e6a0ed91.PNG">
<br>
I was wondering would you know any solution to this? Is there something I would have
to change in the GO code?
Thanks for your time.

**Comment by lynskey08** [comment]
Issue solved: grafana-reporter -ip "..." -grid-layout=1

**Comment by IzakMarais** [comment]
Thanks for posting the solution for others to find.

**Comment by mrooke** [comment]
Hi, just to say thanks for leaving the solution - I'd tried using the "grid-layout" option but I think I'd put it too late in the options or something & it wasn't being picked up, don't know.  In any case, I moved it up front and now I'm getting the full tables being printed out!  
Thanks again, & thanks to Izak for this great tool.
