### ISSUE TITLE
Remove title and timestamp?

### ISSUE THREAD

**Issue by lynskey08** [IzakMarais/reporter#177]
Is it possible to remove the dashboard title and time range from the exported pdf as seen in the photo below?
<img width="403" alt="title" src="https://user-images.githubusercontent.com/10612590/71011474-5aba9b80-20e5-11ea-8c4e-147356b105cf.PNG">

**Comment by IzakMarais** [comment]
You could achieve this using a custom latex template. See the query parameters section of the readme. 

________________________________

**Comment by lynskey08** [comment]
Hi,
I have tried using the custom latex template example and looking at older issues related to this but i still can't seem to get it to work. I have created the /templates directory in the /bin dir. I have also added my newCustomTexFile.tex to that directory and ran my grafana-reporter command but it still seems to use the default template. I have tried running the grafana-reporter command with and without the '-template' flag, both of which don't seem to do anything. I have also tried to manually change the 'texTemplate.go' and 'texGridTemplate.go' files, but changes to these files still returns the default tex template. Is there anything I have to do to initialize changes to grafana-reporter before running it? Or Would you have any idea as to why none of the changes are registering?
Thanks for your time.

**Comment by IzakMarais** [comment]
In addition to creating the /templates directory in the /bin directory you also need to supply the file name as an html query parameter named 'template' as part of the GET request. 

If you can't get that working you can modify the source code as you suggest, but you would need to recompile the reporter binary for that to take effect. 

________________________________

**Comment by lynskey08** [comment]
That's after working for me now. I wasn't able to get the /templates directory to function correctly but I was able to get it to work by modifying the code and recompiling the reporter binary. Thank you very much.

**Comment by IzakMarais** [comment]
Glad you found a solution.
