### ISSUE TITLE
how to pass token id when run grafana-report

### ISSUE THREAD

**Issue by Frederic-de-Lavenne** [IzakMarais/reporter#18]
Hello,
i have a question if i deactivate authentication i can run the report as expected, but when i turn on i have authorization required.
How i can give a token id when i run go grafana-reporter?
thank you

**Comment by IzakMarais** [comment]
It is documented towards the bottom of the readme.  See *Query parameters* -> *apitoken*. 

If you want an example, browse through the closed issues where someone else also asked this question.

**Comment by Frederic-de-Lavenne** [comment]
thank you very much, i didn't see issues already closed.
Work like a charm, and awesome tool :)

**Comment by IzakMarais** [comment]
Glad to hear it. 

If you don't mind sharing: where are you from and what work do you do? It is always interesting for me to hear who is using my software ;). You can also send a message if you prefer to `izakmarais at yahoo dot com`.
