### ISSUE TITLE
How to set "orgId" in api URL?

### ISSUE THREAD

**Issue by hasmin2** [IzakMarais/reporter#188]
Hello, Thanks for providing good code for utilize grafana.
I am curious that some dashboards which is in different org. and found PDF is not showing with differ orgId.  I tried many things to resolve, but no improve.

Please kindly help if there is function to input "orgId"

**Comment by IzakMarais** [comment]
We do not use different orginisations at work, so I have no experience in this part of Grafana. 

The reporter has two steps:
1) it uses the Grafana Dashboard HTTP API to fetch the dashboad JSON 
2) It parses the dashboard and then goes through each panel and requests a png render using the Grafana "share direct rendered image" API. 

Do you have any ideas about how orgId interacts with these APIs? You might need to do some experiments and post results.

**Comment by hasmin2** [comment]
Thanks for your reply. I suspect that the Requesting grafana-report  REST API is like this.

    **http://{grafana-reporter-IP}:8686/api/v5/report/{Dashboard UID}?{timespan or etc}.**

then your code will convert into above rest API call as below I guess.

     **http://{grafana-server-IP}:{grafana-server-port}/api/dashboards/uid/{Dashboard UID}**
    this code will receive correct JSON data from grafana server because orgId=1 by default .

However if orgId is not "1"  the api should designate "orgId" for finding proper dashboard under "orgId"

I tested below rest api is returning correct JSON data from the dashboard unlikely above.
     **http://{grafana-server-IP}:{grafana-server-port}/api/dashboards/uid/{Dashboard UID}?{timespan etc}&_orgId=X_**

I tried to look the code, and added some function for adding "orgId" string as variable. But I have never used "GO" and tried to studying by very basic now.

attaching my screenshot about the test result.
![Screenshot from 2020-02-18 09-51-33](https://user-images.githubusercontent.com/29887012/74694671-510ffa00-5234-11ea-93ea-fc4784cedf05.png)
![Screenshot from 2020-02-18 09-51-07](https://user-images.githubusercontent.com/29887012/74694675-52d9bd80-5234-11ea-8f79-c74a68c480f9.png)

**Comment by hasmin2** [comment]
Dear sir, 

I modified your code for accepting "orgid" in dashURL string.
it is working properly. attaching my modification as below, if you feel interesting, you can reference

"api.go"
 39 type client struct {
 40         url              string
 41         getDashEndpoint  func(dashName string) string
 42         getPanelEndpoint func(dashName string, vals url.Values) string
 43         apiToken         string
 44         orgId            string
 45         variables        url.Values
 46         sslCheck         bool
 47         gridLayout       bool
 48 }

 73 func NewV5Client(grafanaURL string, apiToken string, orgId string, variables url.Values, sslCheck bool, gridLayout bool) Client {
 74         getDashEndpoint := func(dashName string) string {
 75                 dashURL := grafanaURL + "/api/dashboards/uid/" + dashName
 76                 if len(variables) > 0 {
 77                         dashURL = dashURL + "?" + variables.Encode() + "&orgId="+orgId
 78                 }else{
 79                         dashURL = dashURL + "?orgId=" + orgId
 80                 }
 81                 return dashURL
 82         }
 83 
 84         getPanelEndpoint := func(dashName string, vals url.Values) string {
 85                 return fmt.Sprintf("%s/render/d-solo/%s/_?%s", grafanaURL, dashName, vals.Encode())
 86         }
 87         return client{grafanaURL, getDashEndpoint, getPanelEndpoint, apiToken, orgId, variables, sslCheck, gridLayout}
 88 
 89 }

"handler.go"
added below func
/////////////////////////////////////////
func orgId(r *http.Request) string{
        orgId := r.URL.Query().Get("orgId")
        log.Println("Called with Organization ID:", orgId)
        return orgId
}
/////////////////////////////////////////

 37         newGrafanaClient func(url string, apiToken string, orgId string, variables url.Values, sslCheck bool, gridLayout bool) grafana.Client

**Comment by IzakMarais** [comment]
Thanks for the feedback.

**Comment by emanzx** [comment]
do this already committed into the docker image of the reporter?
