### ISSUE TITLE
401 Unauthorized with API Key?

### ISSUE THREAD

**Issue by AROAH1337** [IzakMarais/reporter#194]
I know there are a billion issues with 401 unauthorized errors, already, but I am passing the apitoken param and still getting an Unauthorized error. Maybe I'm doing something stupid in Grafana, but it's a fairly vanilla install with authorization enabled. Grafana is sitting behind a reverse proxy, but is technically serving over http.

I am using a reverse proxy via nginx to pass the URL to Reporter, but the apitoken is getting passed, because the log output from Reporter indicates it. This problem persists in command line mode, as well.

The URL I'm using is `https://portal.[project].com/pdf/api/v5/report/DCd9MgQWz?apitoken=eyJrIjoi[...]` which nginx should be rewriting to `http://localhost:8686/api/v5/report/DCd9MgQWz?apitoken=eyJrljoi[...]`
This gives me the response of `error fetching dashboard DCd9MgQWz: error obtaining dashboard from http://localhost:3000/api/dashboards/uid/DCd9MgQWz. Got Status 401 Unauthorized, message: {"message":"Unauthorized"}`

Reporter meanwhile outputs
`2020/02/13 10:09:53 Reporter called
2020/02/13 10:09:53 Called with api Token: eyJrIjoi[...]
2020/02/13 10:09:53 Called without variable
2020/02/13 10:09:53 Called with dashboard: DCd9MgQWz
2020/02/13 10:09:53 Called with time range: {now-1h now}
2020/02/13 10:09:53 Connecting to dashboard at http://localhost:3000/api/dashboards/uid/DCd9MgQWz
2020/02/13 10:09:53 Error generating report: error fetching dashboard DCd9MgQWz: error obtaining dashboard from http://localhost:3000/api/dashboards/uid/DCd9MgQWz. Got Status 401 Unauthorized, message: {"message":"Unauthorized"}`

Now, if I change the API token, it gives me a different "Invalid API key" error, so it really doesn't appear to be a problem with that. The Dashboard URL is `https://portal.[project].com/analytics/d/DCd9MgQWz` so I believe I'm getting the right UID for the Dashboard.

This is on Grafana v6.6.1.

Dashboard permissions: ![image](https://user-images.githubusercontent.com/7283348/74461123-9e1a5780-4e53-11ea-88b4-83959fb9e18a.png)

Any help is appreciated. I'm very thankful that this project exists, considering exporting specifically to PDF was the one major hangup on this project. I just don't understand what I'm doing wrong.

**Comment by AROAH1337** [comment]
Just had the thought to connect to the public URL by using `-ip portal.[project].com/analytics -proto https://` and that ended up working in command line mode, 

I realized I had the `enforce_domain` setting in grafana.ini turned on. That was the problem. Well, I feel dumb, now.

**Comment by IzakMarais** [comment]
Thanks for the feedback. It would be nice if you can have a look at some similar open issues and comment on them if you feel it is applicable.

**Comment by srkfru** [comment]
Hello @IzakMarais and @AROAH1337,, can you please help me with the below issue, which is related to the above one.

https://github.com/IzakMarais/reporter/issues/241#issue-669760611
