### ISSUE TITLE
How to  change the format of PDF

### ISSUE THREAD

**Issue by muqp** [IzakMarais/reporter#196]
hello everyone，
I want to know if it is possible to modify the format of PDF. If so, how.

**Comment by IzakMarais** [comment]
Yes it is possible, but not simple. It is described in the readme with a link to an issue with more details.

**Comment by muqp** [comment]
> Yes it is possible, but not simple. It is described in the readme with a link to an issue with more details.

Thanks,can you show me where the link is,i cant't find it.

**Comment by muqp** [comment]
> Yes it is possible, but not simple. It is described in the readme with a link to an issue with more details.

I have found it,thank you!
