### ISSUE TITLE
Panel Data is not rendered in PDF Generated

### ISSUE THREAD

**Issue by vijayakumarbathini** [IzakMarais/reporter#198]
Hi,

We are generating PDF for our Dashboard Panels, able to see PDF generated and shown in new Tab but in the generated PDF not able to see data rendered as graph

Dashboard Data
![Screenshot 2020-02-25 at 2 58 50 PM](https://user-images.githubusercontent.com/7524183/75234552-cfded700-57e0-11ea-8e80-f8b4235a42e2.png)

Generated PDF
![Screenshot 2020-02-25 at 2 59 03 PM](https://user-images.githubusercontent.com/7524183/75234592-dd945c80-57e0-11ea-8dd5-0119a6906de2.png)

Regards
Vijaya Kumar

**Comment by IzakMarais** [comment]
Is this using some non standard panel? Or is that the standard Grafana graph panel? Third party panels have been known to not work properly with grafana's png rendering api.

**Comment by vijayakumarbathini** [comment]
It is happening for data that is coming from custom datasources like AIOpsTAS. I wonder if any validation happening with datasource name specified in the plugin.json

**Comment by IzakMarais** [comment]
Does it render successfully if bypass the reporter and just use Grafana's UI to test? On the panel, try _share -> direct link rendered image_.

**Comment by vijayakumarbathini** [comment]
The issue is fixed now, It was the issue with PhantomJS we had.After upgrading and using Image renderer this issue is not happening
