### ISSUE TITLE
Graph image won't show the all table data, only show 6 row table data  

### ISSUE THREAD

**Issue by brucexie** [IzakMarais/reporter#199]
Hi all, 
Ask a question, how to adjust the download image High size? because my Grafana dashboard Graph added more than 6 row table data, but the download and generate the image only show 6 row, from 7 row table data won't be show and download into PDF report.

**Comment by IzakMarais** [comment]
You can use the -grid-layout flag of the reporter to solve table height problems.

**Comment by chamchenpion** [comment]
@IzakMarais 
Excuse me. How could I use the "-grid-layout" flag when I use the web API? 
Thanks for your response in advance.

**Comment by chelliwell** [comment]
> @IzakMarais
> Excuse me. How could I use the "-grid-layout" flag when I use the web API?
> Thanks for your response in advance.

I don't know if this helps in your situation, but we run the reporter as a Windows service using NSSM. I've just discovered/realised that '-grid-layout=1' can be set in the service exe settings.
