### ISSUE TITLE
Reporter doesnt get all the data

### ISSUE THREAD

**Issue by totalnooob** [IzakMarais/reporter#201]
Hello,
Is it possible to improve the reporter to get all the data from grafana like pictures and everything else? Not just graphs?
![AcroRd32_2020-03-06_09-11-18](https://user-images.githubusercontent.com/31215293/76064703-7b7aea80-5f8a-11ea-993a-c157de3d24ca.png)

**Comment by IzakMarais** [comment]
What types of panels are those that are not rendered correctly?

**Comment by totalnooob** [comment]
its text panel

**Comment by totalnooob** [comment]
`2020/03/06 10:58:13 Called with variable: var-group [Servisna_starostlivost]
2020/03/06 10:58:13 Called with variable: var-host [Gymnazium Ceska]
2020/03/06 10:58:13 Called with dashboard: yNbFTsHZk
2020/03/06 10:58:13 Called with time range: {1580528452828 1582969252828}
2020/03/06 10:58:13 Connecting to dashboard at http://94.130.151.159:3000/api/dashboards/uid/yNbFTsHZk?var-group=Se                                               rvisna_starostlivost&var-host=Gymnazium+Ceska&var-month=1m
2020/03/06 10:58:13 Populated dashboard datastructure: {Title:Servisna starostlivost Description: VariableValues:1m                                               , Servisna\_starostlivost, Gymnazium Ceska Rows:[] Panels:[{Id:19 Type:text Title: GridPos:{H:21 W:16 X:4 Y:0}} {Id                                               :2 Type:text Title: GridPos:{H:6 W:19 X:3 Y:21}} {Id:20 Type:text Title: GridPos:{H:10 W:19 X:3 Y:27}} {Id:18 Type:                                               text Title: GridPos:{H:13 W:19 X:3 Y:37}} {Id:14 Type:text Title: GridPos:{H:5 W:19 X:3 Y:50}} {Id:22 Type:grafana-                                               piechart-panel Title:Graf voľného miesta Disk C:/ GridPos:{H:7 W:8 X:9 Y:55}} {Id:9 Type:text Title: GridPos:{H:6 W                                               :19 X:3 Y:62}} {Id:6 Type:graph Title:Graf využitia procesora GridPos:{H:8 W:19 X:3 Y:68}} {Id:10 Type:text Title:                                                GridPos:{H:4 W:12 X:6 Y:76}} {Id:7 Type:graph Title:Graf teploty procesora GridPos:{H:9 W:19 X:3 Y:80}} {Id:11 Type                                               :text Title: GridPos:{H:4 W:12 X:6 Y:89}} {Id:12 Type:graph Title:Graf využitia RAM (\%) GridPos:{H:8 W:19 X:3 Y:93                                               }}]}
2020/03/06 10:58:13 Downloading image  2 http://94.130.151.159:3000/render/d-solo/yNbFTsHZk/_?from=1580528452828&he                                               ight=100&panelId=2&theme=light&to=1582969252828&var-group=Servisna_starostlivost&var-host=Gymnazium+Ceska&var-month                                               =1m&width=1000
2020/03/06 10:58:13 Downloading image  19 http://94.130.151.159:3000/render/d-solo/yNbFTsHZk/_?from=1580528452828&h                                               eight=100&panelId=19&theme=light&to=1582969252828&var-group=Servisna_starostlivost&var-host=Gymnazium+Ceska&var-mon                                               th=1m&width=1000
2020/03/06 10:58:13 Downloading image  20 http://94.130.151.159:3000/render/d-solo/yNbFTsHZk/_?from=1580528452828&h                                               eight=100&panelId=20&theme=light&to=1582969252828&var-group=Servisna_starostlivost&var-host=Gymnazium+Ceska&var-mon                                               th=1m&width=1000
2020/03/06 10:58:13 Downloading image  18 http://94.130.151.159:3000/render/d-solo/yNbFTsHZk/_?from=1580528452828&h                                               eight=100&panelId=18&theme=light&to=1582969252828&var-group=Servisna_starostlivost&var-host=Gymnazium+Ceska&var-mon                                               th=1m&width=1000
2020/03/06 10:58:13 Downloading image  14 http://94.130.151.159:3000/render/d-solo/yNbFTsHZk/_?from=1580528452828&h                                               eight=100&panelId=14&theme=light&to=1582969252828&var-group=Servisna_starostlivost&var-host=Gymnazium+Ceska&var-mon                                               th=1m&width=1000
2020/03/06 10:58:18 Downloading image  22 http://94.130.151.159:3000/render/d-solo/yNbFTsHZk/_?from=1580528452828&h                                               eight=500&panelId=22&theme=light&to=1582969252828&var-group=Servisna_starostlivost&var-host=Gymnazium+Ceska&var-mon                                               th=1m&width=1000
2020/03/06 10:58:18 Downloading image  9 http://94.130.151.159:3000/render/d-solo/yNbFTsHZk/_?from=1580528452828&he                                               ight=100&panelId=9&theme=light&to=1582969252828&var-group=Servisna_starostlivost&var-host=Gymnazium+Ceska&var-month                                               =1m&width=1000
2020/03/06 10:58:18 Downloading image  6 http://94.130.151.159:3000/render/d-solo/yNbFTsHZk/_?from=1580528452828&he                                               ight=500&panelId=6&theme=light&to=1582969252828&var-group=Servisna_starostlivost&var-host=Gymnazium+Ceska&var-month                                               =1m&width=1000
2020/03/06 10:58:18 Downloading image  10 http://94.130.151.159:3000/render/d-solo/yNbFTsHZk/_?from=1580528452828&h                                               eight=100&panelId=10&theme=light&to=1582969252828&var-group=Servisna_starostlivost&var-host=Gymnazium+Ceska&var-mon                                               th=1m&width=1000
2020/03/06 10:58:18 Downloading image  7 http://94.130.151.159:3000/render/d-solo/yNbFTsHZk/_?from=1580528452828&he                                               ight=500&panelId=7&theme=light&to=1582969252828&var-group=Servisna_starostlivost&var-host=Gymnazium+Ceska&var-month                                               =1m&width=1000
2020/03/06 10:58:22 Downloading image  11 http://94.130.151.159:3000/render/d-solo/yNbFTsHZk/_?from=1580528452828&h                                               eight=100&panelId=11&theme=light&to=1582969252828&var-group=Servisna_starostlivost&var-host=Gymnazium+Ceska&var-mon                                               th=1m&width=1000
2020/03/06 10:58:23 Downloading image  12 http://94.130.151.159:3000/render/d-solo/yNbFTsHZk/_?from=1580528452828&h                                               eight=500&panelId=12&theme=light&to=1582969252828&var-group=Servisna_starostlivost&var-host=Gymnazium+Ceska&var-mon                                               th=1m&width=1000
2020/03/06 10:58:27 Calling LaTeX - preprocessing
2020/03/06 10:58:28 Calling LaTeX and building PDF
2020/03/06 10:58:28 Extracted filename from dashboard title:  Servisna starostlivost.pdf
2020/03/06 10:58:28 Report generated correctly
`

**Comment by totalnooob** [comment]
@IzakMarais  can it copy images from html into the pdf?

**Comment by IzakMarais** [comment]
> 
> 
> its text panel

Have you tried adding the reporter command line flag `-grid-layout=1`

**Comment by IzakMarais** [comment]
> 
> 
> @IzakMarais can it copy images from html into the pdf?

I think so. It depends on whether Grafana supports this for its PNG rendering. You can test it without reporter by clicking on the Grafana UI for the _panel -> share -> direct link rendered image_.

**Comment by totalnooob** [comment]
> 
> 
> > @IzakMarais can it copy images from html into the pdf?
> 
> I think so. It depends on whether Grafana supports this for its PNG rendering. You can test it without reporter by clicking on the Grafana UI for the _panel -> share -> direct link rendered image_.
it show just black image so probably not

**Comment by totalnooob** [comment]
> 
> 
> > its text panel
> 
> Have you tried adding the reporter command line flag `-grid-layout=1`

yes with that it works fine

**Comment by totalnooob** [comment]
ok
