### ISSUE TITLE
Got Status 404 Not Found, message: {"message":"Dashboard not found"} 

### ISSUE THREAD

**Issue by bientt210** [IzakMarais/reporter#202]
Hi,
I have a problem when i export to file, in dashboard setting, option Variable values is Disable but on report always show as below:
![Screen Shot 2020-03-11 at 12 29 51](https://user-images.githubusercontent.com/47659964/76385889-80c6a380-6395-11ea-8a68-97e63bf098da.png)

Does someone get the same error?

**Comment by IzakMarais** [comment]
The error message says dashboard not found. Are you sure you are using the correct dashboard Id that matches a dashboard deployed on the production system?

**Comment by bientt210** [comment]
> The error message says dashboard not found. Are you sure you are using the correct dashboard Id that matches a dashboard deployed on the production system?

Thanks for answer, 

i was fixed that error but,

I have a problem when i export to file, in dashboard setting, option Variable values is Disable but on report always show as below:
![Screen Shot 2020-03-11 at 12 29 51](https://user-images.githubusercontent.com/47659964/76385889-80c6a380-6395-11ea-8a68-97e63bf098da.png)

Can you help me fix that?
