### ISSUE TITLE
Variable values can not disabled

### ISSUE THREAD

**Issue by bientt210** [IzakMarais/reporter#203]
I have a problem when i export to file, in dashboard setting, option Variable values is Disable but on report always show as below:
![Screen Shot 2020-03-11 at 12 29 51](https://user-images.githubusercontent.com/47659964/76385889-80c6a380-6395-11ea-8a68-97e63bf098da.png)

Does someone get the same error?

**Comment by mbanck** [comment]
That's the time range, not the variable(s) value I believe.

**Comment by bientt210** [comment]
> That's the time range, not the variable(s) value I believe.

Thanks for your answer,

But when i set time range on grafana to 3h, 6h, 12h, 24h ... I still get the same as above, So i want to hide that infomation, can you help me?

thanks you so much

**Comment by mbanck** [comment]
> But when i set time range on grafana to 3h, 6h, 12h, 24h ... I still get the same as above, So i want to hide that infomation, can you help me?

Are you saying the report always shows the above timerange (1h), no matter what Grafana is set to?

Or are you saying that you do not want the time ranges to be displayed? This could at least be solved with a custom report template, I do not have time right now to check if there is another way.

**Comment by dzbaby** [comment]
how to hide the time ranges? Sometimes need not this information. any one can support help?

**Comment by onefourfive** [comment]
You can customize the report's content using its TeX template.

Copy the LaTeX template out of either `report/texTemplate.go` or `report/texGridTemplate.go`, depending on whether you use grid layout or not, into a new file ie `newTemplate.tex`.

Edit your new TeX template to remove the `[[.fromFormatted]]\\to\\[[.ToFormatted]]` content.

Specify that template either with `&template=templateName` in your request or using the equivalent command line parameters.

**Comment by IzakMarais** [comment]
Thanks for the correct and appropriate answers @onefourfive .
