### ISSUE TITLE
Grafana-reporter configuration

### ISSUE THREAD

**Issue by Daly123456** [IzakMarais/reporter#206]
I'am new in using Github !
After downloading and installing grafana-reporter under /root/go/bin/ i got problem with configuring it !
How can i set it now to generate my report ! 
Some steps to follow to do that ! 
![image](https://user-images.githubusercontent.com/46686877/77901227-270c1780-7277-11ea-9c99-ad76b1a38b4e.png)

**Comment by IzakMarais** [comment]
Running the reporter like that starts it as a web server. As explained in the readme, the next step is to use the HTTP api (via the browser or curl) to download the report.

**Comment by Daly123456** [comment]
Hi it’s not solved beacause i Always got an empty report 

Provenance : Courrier pour Windows 10

De : Izak Marais
Envoyé le :jeudi 30 avril 2020 16:36
À : IzakMarais/reporter
Cc : Daly123456; Author
Objet :Re: [IzakMarais/reporter] Grafana-reporter configuration (#206)

Closed #206.
