### ISSUE TITLE
Configuration problems

### ISSUE THREAD

**Issue by Daly123456** [IzakMarais/reporter#207]
i have a problem in this step while executing grafana-reporter  
![image](https://user-images.githubusercontent.com/46686877/77915891-22079200-7290-11ea-9112-f01a72f384c9.png)
![image](https://user-images.githubusercontent.com/46686877/77916077-698e1e00-7290-11ea-92f2-8d22ca4f882a.png)

**Comment by IzakMarais** [comment]
What folder are you trying to run it from?

**Comment by IzakMarais** [comment]
I see you commented on another issue, so I assume this is solved.
