### ISSUE TITLE
Repeat panels issue ,some panels show and some don't

### ISSUE THREAD

**Issue by Clivimati** [IzakMarais/reporter#209]
I have a really weird issue with this Api. I need to create a rapports whit panels who have the same basic panel. But when i decide to export them in pdf sometime it's work and sometime it doesn't.
It's really weird because if the first time i do the export it show like 3 panels and if a second time i just want one the api just freeze infinitly. It's stuck on a number of panels and never allow to put more or less.  So i wanted to now what's the matter behind that because each panels have his own id so , i don't really know.
And no, it's not like the other issues because the repeat panels showed sometime...

EDIT: I find something, if i change the "Hover tooltip" in the visualisation, it will take the number of values i chose.  So i need to always go in the edit and save for this to function. But it's stupid to do that by hand what can i do? 

Thanks for your answers!

**Comment by IzakMarais** [comment]
Glad you found a workaround. Yes repeated panels in the dashboard are returned from Grafana via its API to the reporter based on the value the panel was saved with if I recall correctly.
