### ISSUE TITLE
Dashboard not found

### ISSUE THREAD

**Issue by johnnyflame** [IzakMarais/reporter#21]
Hi Izak,

Thanks for making this. The demo looks really good but I'm having some issues getting it going. 

After installing and running the reporter from the terminal, I cannot seem to figure out how to launch it in the browser. The terminal says "serving at ':8686' and using grafana at 'localhost:3000'". 

When I try to open http://localhost:3000/dashboard/db/backend-dashboard, Grafana gives the error message "Dashboard not found". 

When I try to access http://localhost:8686, I get a 404 page not found error. 

Any help on these issues would greatly appreciated :) 

Thanks,
Johnny

**Comment by IzakMarais** [comment]
Hi Johnny,

The reporter doesn't have a UI that it serves at root; it only servers reports at the `/api/report` endpoint explained [here](https://github.com/IzakMarais/reporter#generate-dashboard) in the readme. 

So the example assumes you have a dashboard called `backend-dashboard` but you should replace that string with the actual name of one of your dashboards, lets say `foo`. If you can load http://localhost:3000/dashboard/db/foo in Grafana, then that means your dashboard's name is `foo`. Then going to http://localhost:8686/api/report/foo should serve you a pdf report of that dashboard.

**Comment by VOrlyanchik** [comment]
Hi Izak,

I'm using Grafana on EC2 instance and trying to generate reports. Unfortunately, http://AWSPublicDNS:8686/api/report/XyzXyz cannot be reached (grafana is on port 3000 and could be seen at http://AWSPublicDNS:3000/d/XyzXyz... )  Is there something I'm missing in configuration?

Thanks,
Vlad

**Comment by thiagocorredor** [comment]
Hi. Same issue from @VOrlyanchik Is there some update on this?

Getting the error:

error fetching dashboard 000000075: error obtaining dashboard from https://XXXXXXXXXXXXX:443/api/dashboards/uid/000000075. Got Status 404 Not Found, message: {"message":"Dashboard not found"}

**Comment by IzakMarais** [comment]
@thiagocorredor . Have you had any luck resolving your issue? You should be able to debug it by issuing the same request contained in the error message from the reporter host. Compare that the result you would get if you make the same request from your browser.

**Comment by shilpad** [comment]
Hi, in my case i am getting - Got Status 401 Unauthorized, message: {"message":"Unauthorized"}.
This is when the reporter queries grafana with the uid i.e. http://localhost:3000/api/dashboards/uid/{uid}. When i pass Authorization header like this 
curl -H "Authorization: Bearer {apikey}" http://localhost:3000/api/dashboards/uid/{uid}, the error goes away. How can i achieve this via Settings->Links->New option where i configure the reporter.

**Comment by IzakMarais** [comment]
@shilpad: See https://github.com/IzakMarais/reporter/issues/69.
