### ISSUE TITLE
When Grafana using Nginx DNS reverse resolution, the Grafana-report generate traffic incorrect.

### ISSUE THREAD

**Issue by brucexie** [IzakMarais/reporter#212]
Hi, 

I used the Nginx to reverse resolution like localhost:3000 to resolution the http://www.abc.com/grafana/

But I don't know how to change the Grafana-report configuration file and Grafana Dashboard link url settings. the Grafana-report using default 8686 port, when I set the Dashboard link using http://IP:8686/api/v5/report/{UID}, but get the incorrect the traffic image. could you help me how to fix this issue?
![image](https://user-images.githubusercontent.com/2329489/78656500-13595480-78fa-11ea-95cb-212b75b084d8.png)

**Comment by IzakMarais** [comment]
I'm afraid I can't help here. The reporter only fetches data from grafana. If you hit grafana with that UID, you should get the same information on the dashboard that you do on the report.

**Comment by fadjar340** [comment]
I've done before, below the step:

1. create new reverse proxy in the web server such as: (in httpd)
```
   <Location /report >
     ProxyPass  http://127.0.0.1:8086 retry=0
     ProxyPassReverse  http://127.0.0.1:8086
   </Location>
```
2. Build systemd file for grafana-reporter at /etc/systemd/system/multi-user.target.wants/grafana-reporter.service
3. Build the file grafana-reporter.service as follow:
```
# -*- mode: conf -*-

[Unit]
Description=The Grafana Reporter.
Documentation=
After=network.target

[Service]
EnvironmentFile=-/etc/default/grafana-reporter
User=root
ExecStart=/root/go/bin/grafana-reporter \
          $REPORTER_OPTS
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```
4. Build file grafana-reporter at /etc/default/ with content as follow:
```
REPORTER_OPTS='-grid-layout=1 -ip ipaddress.hostname.of.webserver -port :8086 -proto http:// -ssl-check false'
```
5. Enable the systemd
```
systemctl enable grafana-reporter
```
6. Start grafana-reporter
```
systemctl start grafana-reporter
```
This configuration will automate your grafana-reporter when the server restart

7. Put the URL in the grafana link as follow
![image](https://user-images.githubusercontent.com/1247073/85199705-deb34180-b31b-11ea-86b6-c88314530773.png)
The URL is the webserver that you have http://www.abc.com/report/.....  <= follow location in point 1, following by the standard grafana-reporter URL for the api, dashboard and apitoken.

Then you can use it from the grafana dashboard.

Regards,
Fadjar Tandabawana

**Comment by IzakMarais** [comment]
Thanks for the help @fadjar340 .
