### ISSUE TITLE
unable to generate report of custom panels

### ISSUE THREAD

**Issue by venkatBG** [IzakMarais/reporter#214]
I am using certain customised plugins/panels such as "data table panel" for which the reporter is not able to generate the pdf reports.
The error shown is "Error obtaining render for panel {Id:4 Type:briangann-datatable-panel".
Is there a way to fetch the data from customised panels/plugins?
Adding one more question to the above thread:
The dashboard consists of several panels, is there a way to fetch particular panels from the dashboard? or any way to remove particular panel from the report?

**Comment by venkatBG** [comment]
Adding one more question to the above thread:
The dashboard consists of several panels, is there a way to fetch particular panels from the dashboard? or any way to remove particular panel from the report?

**Comment by IzakMarais** [comment]
This is an issue with the panel author not supporting grafana's PNG rendering. So it is an interaction between the panel and grafana. You can test it via the grafana UI by using the panel->share->direct-link-rendered-image functionality. You can log a bug with the panel authors.

**Comment by venkatBG** [comment]
Hi IzakMarais,
I tried rendering the grafana UI using panel->share->direct-link-rendered-image functionality and able to render the image. so the panel is able to render the image. Do I need to make any changes in the reporter to address this issue?

**Comment by IzakMarais** [comment]
> I tried rendering the grafana UI using panel->share->direct-link-rendered-image functionality and able to render the image. so the panel is able to render the image

This is surprising. You could compare the URL used in the browser when you see the render to the URL from the reporter log ouput when it tries to read the panel. If those two are the same, they should work the same.
