### ISSUE TITLE
Newbie Go building question

### ISSUE THREAD

**Issue by chelliwell** [IzakMarais/reporter#218]
Go is totally new to me lol. I've followed the Readme to build and install reporter, no problem.
But if I download the repository and want to modify/build it 'locally', what's the go command to do this? Thanks.

**Comment by IzakMarais** [comment]
If you've built it locally following the instructions you have already downloaded the source and compiled the source. You can navigate to it, modify it and then complie again. It should be in your GOPATH (I think this defaults to your user home directory /go on the latest release of you haven't set it) under src/github.com/izakmarais/reporter.

**Comment by chelliwell** [comment]
Ah ok - I was misunderstanding the reference to github.com in the 'install' command (assumed it meant some more fetching would happen). More studying of the Go infrastructure needed by me :) Thanks for pointing me in the right direction.

**Comment by IzakMarais** [comment]
Yes the go command both downloads the source and compiles it.
