### ISSUE TITLE
Cant add custom latex template Invalid API key

### ISSUE THREAD

**Issue by totalnooob** [IzakMarais/reporter#221]
Hello,
i try to add custom latex template to generate pdf and im getting error
` Got Status 401 Unauthorized, message: {"message":"Invalid API key"}`
link in grafana

http://1.1.1.1:8686/api/v5/report/yNbFTsHZk?apitoken=api key=?template=landscapeTemplate

without the ?template=landscapeTemplate it works fine and downloads the pdf. i have it in /usr/bin/templates/landscapeTemplate.text

**Comment by IzakMarais** [comment]
You are using URL query parameters incorrectly. To when using more than one parameter, they should be separated by `&` not by adding more `?`. This is the way standard URLs in the browser also work .

**Comment by totalnooob** [comment]
oh ok there was no & at https://github.com/IzakMarais/reporter/issues/50 is the /usr/bin/templates correct?

**Comment by totalnooob** [comment]
nevermind got it working with https://github.com/IzakMarais/reporter/issues/132
