### ISSUE TITLE
Unable to install the grafana-reporter 

### ISSUE THREAD

**Issue by laxman2785** [IzakMarais/reporter#223]
Hello Team,

we are looking to have this feature of having the pdf converter for the grafana. As part of it  I have downloaded the zip file reporter.2.3.1 version. 

As mentioned in the readme file for setting it up .we have installed go language and set the path to $GOPATH. 
when we tried to install the grafana-reporter  as $GOPATH/go install -v  reporter2.3.1/cmd/grafana-reporter/main.go 

but loos like paths are hardcoded in all the .go files as below

"github.com/IzakMarais/reporter/grafana"
 "github.com/IzakMarais/reporter/report"
 "github.com/gorilla/mux"

we tried to give the obsolute path in all the .go files under igrafana-reporter dir (ex absolutepath/reporter2.3.1/cmd/grafana-reporter/main.go)  and when we ran it it says we cannot put the obsolute path.

so request you please provide the installation steps in simple way.

your help is very much appreciable.

Thanks

**Comment by IzakMarais** [comment]
The `go install` command already fetches the data from github. You don't need to download the zip file first. If you follow the command exactly it should work.
