### ISSUE TITLE
Command not found, but report is generated

### ISSUE THREAD

**Issue by Coreeze** [IzakMarais/reporter#224]
Hi, I looked on other issues as well, but didnt manage to solve this.

**Environment:**
- Ubuntu
- grafana-reporter added to `gopath` in `home/go`
- reports are generated, so all is ok here

**Problem:**
- I want to modify the template and the commands are not working with the err `command not found`
- Also when looking at running services with the command `systemctl list-units --type service`, I dont see `grafana-reporter` running, even though reports are generated
- there are more files called `texTemplate.go`. Could you tell me please which one is the reporter using?

Any ideas? Thanks!

**Comment by IzakMarais** [comment]
Getting custom reports working is a pretty advanced feature. I suggest you look at the issue linked from the readme section on custom templates. 

> Also when looking at running services with the

If you didn't wrap the reporter binary in a service yourself then it won't be running as a service. The readme instructions just create an executable binary. I suggest you read up on the difference between the two. 

> there are more files called texTemplate.go
This is the default built in template. If you can't figure out custom templates on your own, you might also try modifying the source code here and rebuilding the application.
