### ISSUE TITLE
 Report not able to generate using Kubernetes 

### ISSUE THREAD

**Issue by sonnyboii** [IzakMarais/reporter#225]
Hi, 

I have deployed grafana and grafana-reporter pods in the kubernetes cluster as separate instance. 
i am trying to generate the report from the grafana UI, i am not able to get it ..
Error: 
error fetching dashboard vd06Nv6Wk: error executing getDashboard request for http://localhost:3000/api/dashboards/uid/vd06Nv6Wk: Get http://localhost:3000/api/dashboards/uid/vd06Nv6Wk: dial tcp [::1]:3000: getsockopt: connection refused

Kubernetes grafana-reporter logs 

kubectl logs grafana-reporter-6885679455-jvv85
2020/04/30 21:27:21 grafana reporter, version: 2.3-1 hash: 6cfc3e220dc4f8fc0175ae0ec8698d35546d8c10
2020/04/30 21:27:21 serving at ':8686' and using grafana at 'http://localhost:3000'
2020/04/30 21:27:21 SSL check enforced
2020/04/30 21:27:21 Using sequential report layout. Consider enabling 'grid-layout' so that your report more closely follow the dashboard layout.
2020/04/30 21:46:11 Reporter called
2020/04/30 21:46:11 Called with api Token: eyJrIjoiMzNPSldWRThuaTRvM1pOczc2RWtyRVkyNnRtVmVWekgiLCJuIjoiamRoIiwiaWQiOjF9
2020/04/30 21:46:11 Called without variable
2020/04/30 21:46:11 Called with dashboard: vd06Nv6Wk
2020/04/30 21:46:11 Called with time range: {now-6h now}
2020/04/30 21:46:11 Connecting to dashboard at http://localhost:3000/api/dashboards/uid/vd06Nv6Wk
2020/04/30 21:46:11 Error generating report: error fetching dashboard vd06Nv6Wk: error executing getDashboard request for http://localhost:3000/api/dashboards/uid/vd06Nv6Wk: Get http://localhost:3000/api/dashboards/uid/vd06Nv6Wk: dial tcp [::1]:3000: getsockopt: connection refused..

Note : Even if i have pass grafana-reporter ip with port ( from the ingress) in Grafana UI - link tab, i see the http://localhost:3000 in the logs .

Also, if i pass grafana ip with port ( from the ingress) in Grafana UI - link tab, i received 404 error. 

Please  help me to find the solution on this !!

Thanks..

**Comment by sbaier1** [comment]
sounds like you aren't running a local `kubectl port-forward`, since your port isn't being listened on locally.
You need to forward your local port 3000 to the grafana pod directly to access its API.
(I guess you could also use an ingress instead, but it's usually a pain with rewrite rules for grafana specifically)

**Comment by sonnyboii** [comment]
I could able to generate the report by passing grafana IP(ingress) in the src code and building the docker image.  this is pain when the grafana goes down or scales up and new Ip generates then again we need to pass the new grafana Ip (ingress) in src code and build.  
is there a way to overcome this in the yaml file in k8s?

**Comment by IzakMarais** [comment]
I have never worked with kubernetes. This seems like a networking/environment problem and not a reporter problem.

**Comment by shqnayaz** [comment]
@sonnyboii , 
How did you pass the IP string to point grafana in your yaml file ?, appreciate if you can share the code.
