### ISSUE TITLE
Grafana reporter not capturing all the data's in the table.

### ISSUE THREAD

**Issue by venkatBG** [IzakMarais/reporter#226]
I am using a customised plugins/panels named "Brian Gann datatable panel" for which the reporter iniatially was not able to generate the pdf reports.
This was because the panel was not rendering PNG images, but now it has been fixed from the panel author and I able to generate the PDF.
But the problem is, it is not fetching all the values from the table as table has many records with scrollable option. Is there a way to capture to all the records from the table?
I have already used -grid-layout=1 which doesn't solve the issue.

**Comment by gabrieln97** [comment]
I have the same problem here, were you able to fix it?

**Comment by RidolfoFabien** [comment]
Hello,

I have the same issue!! 
Did you find a solution ?!

**Comment by IzakMarais** [comment]
Sorry, if `-grid-layout=1` does not fix it, I don't think there is a solution.
