### ISSUE TITLE
About PDF -- its not like a screenshot of dashboard - exporting panels separately

### ISSUE THREAD

**Issue by softwareklinic** [IzakMarais/reporter#229]
Why is the tool exporting panels chart separately in pdf - I thought it would export dashboard as a screenshot type pdf so we can see the way we see it in the dashboard.?

thoughts?

**Comment by sonnyboii** [comment]
Hi , 

i am also facing the same issue, i don't see the PDF report as same as Dashboard. data is not correctly generated in the report(PDF) as dashboard. 
is this some bug in the code?

Thanks!!

**Comment by Coreeze** [comment]
Take a look at this: https://gist.github.com/svet-b/1ad0656cd3ce0e1a633e16eb20f66425

**Comment by IzakMarais** [comment]
It works the way it was designed. 

Thanks to @Coreeze  for the link to an alternative solution.
