### ISSUE TITLE
Add author

### ISSUE THREAD

**Issue by Coreeze** [IzakMarais/reporter#230]
Hi, Im looking through your code wanting to add the `username` as `author` of the PDF. Maybe you have an idea how? 

Thanks!

**Comment by IzakMarais** [comment]
This would require modifying the source code to 
* fetch the username from Grafana (that is if there is an API call for that). Or inject the username as a command line parameter.
* pass the username to the LaTeX templating code as part of the template data struct
* update the tex template to use this new data.

I don't plan on adding this functionality.
