### ISSUE TITLE
502 Proxy Error

### ISSUE THREAD

**Issue by Midas1989** [IzakMarais/reporter#231]
Hello I have a problem with the report generation.

I am using zabbix 5 with grafana 7 (up to date)
with some Grafana dashboards i get an error when i start the PDF report via grafana.
It has nothing to do with the panel type. I think it has to do with the number of panels.  Anybody got an idea?

Web:
error rendering PNGs in parralel for dash {Title:Meets test Description: VariableValues:meet.example.at, MEETS Rows:[] Panels:[{Id:27 Type:stat Title:Total memory GridPos:{H:2 W:4 X:0 Y:1}} {Id:2 Type:singlestat Title:Uptime GridPos:{H:2 W:16 X:4 Y:1}} {Id:24 Type:stat Title:Total cpu GridPos:{H:2 W:4 X:20 Y:1}} {Id:12 Type:singlestat Title: GridPos:{H:2 W:16 X:4 Y:3}} {Id:5 Type:singlestat Title:Memory Available GridPos:{H:8 W:4 X:0 Y:6}} {Id:9 Type:graph Title:Memory / CPU GridPos:{H:8 W:16 X:4 Y:6}} {Id:4 Type:singlestat Title:CPU utilization GridPos:{H:8 W:4 X:20 Y:6}} {Id:41 Type:stat Title:Total Conferences GridPos:{H:4 W:3 X:0 Y:15}} {Id:42 Type:stat Title:Total Conferences Time GridPos:{H:4 W:3 X:3 Y:15}} {Id:44 Type:stat Title:Largest Conferences GridPos:{H:4 W:3 X:6 Y:15}} {Id:46 Type:stat Title:Total participants GridPos:{H:4 W:3 X:9 Y:15}} {Id:48 Type:stat Title:Endpoints sending video GridPos:{H:4 W:3 X:12 Y:15}} {Id:40 Type:graph Title:Conferences GridPos:{H:7 W:18 X:0 Y:20}} {Id:47 Type:stat Title:Endpoints sending audio GridPos:{H:4 W:3 X:18 Y:20}} {Id:45 Type:stat Title:Active participants GridPos:{H:4 W:3 X:21 Y:20}} {Id:49 Type:stat Title:Videostreams GridPos:{H:3 W:6 X:18 Y:24}} {Id:52 Type:stat Title:RTT Aggregate GridPos:{H:3 W:5 X:0 Y:27}} {Id:53 Type:stat Title:Loss rate download GridPos:{H:3 W:5 X:5 Y:27}} {Id:54 Type:stat Title:Loss rate upload GridPos:{H:3 W:5 X:10 Y:27}} {Id:22 Type:graph Title:Average disk queue length GridPos:{H:6 W:9 X:0 Y:31}} {Id:32 Type:graph Title:Free disk space GridPos:{H:6 W:9 X:9 Y:31}} {Id:15 Type:table-old Title:Free disk space GridPos:{H:6 W:6 X:18 Y:31}} {Id:18 Type:graph Title:Network Traffic GridPos:{H:5 W:16 X:0 Y:37}} {Id:19 Type:stat Title:Incoming Traffic GridPos:{H:5 W:4 X:16 Y:37}} {Id:21 Type:stat Title:Outgoing Traffic GridPos:{H:5 W:4 X:20 Y:37}}]}: error getting panel {Id:12 Type:singlestat Title: GridPos:{H:2 W:16 X:4 Y:3}}: Error obtaining render: 502 Proxy Error

grafana.log:
t=2020-06-19T14:07:07+0200 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/render/d-solo/41URQF7dmzd/_ status=500 remote_addr=10.34.32.45 time_ms=60026 size=1731 referer=
t=2020-06-19T14:07:09+0200 lvl=eror msg="Render request failed" logger=plugins.backend pluginId=grafana-image-renderer url="http://localhost:3000/d-solo/41URQF7dmzd/_?from=now-6h&height=80&panelId=12&theme=light&to=now&var-Group=MEETS&var-Hosts=meet.example.at&width=640&render=1" error="TimeoutError: waiting for function failed: timeout 60000ms exceeded"

I have a second system with the same configuration and version, where it works without problems.

Thanks

**Comment by IzakMarais** [comment]
From the grafana logs it looks like an internal grafana error. I am not 100% up to date with how the panel rendering changed in the recent garafana releases, but I think it now uses a configurable plugin for rendering. Perhaps you can investigate that. 

Closing this issue since the Grafana logs indicate it is not within the reporter's responsibility.
