### ISSUE TITLE
How to enable the grid layout in grafana-reporter

### ISSUE THREAD

**Issue by SahilDadarya** [IzakMarais/reporter#234]
Where to do changes to enable grid layout format like dashboard.

**Comment by IzakMarais** [comment]
From the readme (also if you run `reporter --help`):

> -grid-layout
      Enable grid layout (-grid-layout=1)

**Comment by joe00712** [comment]
Hi @IzakMarais ,

I am using it as pod. So how should i pass this query param.

my podman command is : podman run -d -p 8686:8686 --network=host izakmarais/grafana-reporter

Can you please share some example how should update the grid layout in my pod.
