### ISSUE TITLE
Boom plugin clashes with grafana reporter

### ISSUE THREAD

**Issue by Coreeze** [IzakMarais/reporter#235]
Hi there, great tool, thanks!

I want to customize the looks of our Grafana instance and I treid this: https://grafana.com/grafana/plugins/yesoreyeram-boomtheme-panel. There only problem is when generating a report; it fails with the following error: `error rendering PNGs in parralel for dash`. The problem is getting the render of the panel containg the theme selection: ` error getting panel {Id:17 Type:yesoreyeram-boomtheme-panel`

I can see the images of the dashboards be correctly saved in the `tmp` folder, but it doesnt work. As soon as I remove the dashboard from this plugin with the theme selection the report works.

Any idea if there is a fix?

EDIT: I just read [here](https://github.com/yesoreyeram/yesoreyeram-boomtheme-panel/issues/12) that exports are not expected to work. Is there a to make it work though?

**Comment by IzakMarais** [comment]
> EDIT: I just read here that exports are not expected to work. Is there a to make it work though?

Thanks for the link. No if not png rendering is not supported by the panel, it will not work.
