### ISSUE TITLE
unable to use reporter in dark theme with grafana v 6.5.3

### ISSUE THREAD

**Issue by vmanju123** [IzakMarais/reporter#236]
all our grafana dashboards are in dark them when we export to pdf using reporter it always exports in light theme

**Comment by IzakMarais** [comment]
Yes the reporter only [supports the light theme](https://github.com/IzakMarais/reporter/blob/31bbb4b01fc317b0137eedb68c1f0e507a443fa1/grafana/api.go#L167).
