### ISSUE TITLE
Explaination/legend is not rendered in Grid-Mode

### ISSUE THREAD

**Issue by it-native** [IzakMarais/reporter#238]
In the PDFs at least on legend has missing line colors. It seems to be completely random which & how many are missing. 
I've tried this with grid mode on & off
![grafana_export_grid](https://user-images.githubusercontent.com/5801642/88102650-34d80680-cba0-11ea-8b99-2676cd4658c8.png)
![grafana_export_nogrid](https://user-images.githubusercontent.com/5801642/88102654-37d2f700-cba0-11ea-9bd3-937bf1b81a0c.png)

any help is appreciated
BR 
Oliver

**Comment by IzakMarais** [comment]
All of the rendering is handled by Grafana itself. You should try to reproduce this behaviour using the Grafana UI: Panel>Share>Direct Rendered PNG. Then you can log a bug with the grafana project.

**Comment by it-native** [comment]
Thanks for the hint ... I couldn't reproduce it by rendering single panels, maybe it's fixed with another version (using 6.7.3) at the moment
