### ISSUE TITLE
gridlayout is not compatible with grafana4.6,the pdf file is empty.

### ISSUE THREAD

**Issue by hujunfeng-gitbub** [IzakMarais/reporter#240]
gridlayout is not compatible with grafana4.6,the pdf file is empty.

**Comment by IzakMarais** [comment]
Yup, that is correct. 

If you like you could submit a PR to improve the documentation? You could add "Not compatible with Grafana versions older than 5" [here](https://github.com/IzakMarais/reporter/blob/master/cmd/grafana-reporter/main.go#L35).
