### ISSUE TITLE
Import Logos in the report

### ISSUE THREAD

**Issue by sanemogi** [IzakMarais/reporter#243]
Hello and thank you for the very useful tool. Now it would be great if we could add an image logo in  the pdf output.  
Is that possible ?

**Comment by IzakMarais** [comment]
You could do that with custon template, but that is pretty advanced. 

________________________________

**Comment by sanemogi** [comment]
Thanks for the answer Izak. I managed to do it using custom template and it works fine. Now the problem I have is that some 3rd party custom dashboard panels (i.e zabbix alarms panel) cause the pdf script to throw errors and does not produce a report. Is there anything we could do about this ?

**Comment by sanemogi** [comment]
I checked with Share->Direct Link Rendered Image and it does not render either....

**Comment by IzakMarais** [comment]
Yes that is a known issue without any solution I am afraid. Those third party panels don't support grafana PNG rendering, which the reporter relies on.
