### ISSUE TITLE
Hey i am new to go so how to run this go program for grafana

### ISSUE THREAD

**Issue by wrongown** [IzakMarais/reporter#25]
when after two step like - 
step - 1 go get github.com/izakmarais/reporter/...
step 2 - go install -v github.com/izakmarais/reporter/cmd/grafana-reporter
step 3 - grafana-reporter
 when i hit step 3 then i got error that    **bash: grafana-reporter: command not found**
How do i solve this . 
i am running this three step from root and ubuntu 16.04 systek

**Comment by IzakMarais** [comment]
`go install` should create a binary and place it in your GOBIN directory; which defaults to GOPATH/bin/
https://stackoverflow.com/questions/24069664/what-does-go-install-do

If that is not in you system PATH you will need to cd there and execute it.

**Comment by wrongown** [comment]
ooh thanks but when i hit link on grafana report ( like http://hostname/api/
which you provide in gif on your repo) its show me unauthorised .  (so here
we need to pass any api token if not then how grafana know that i am
authorised)
Thanks for helping me to out of this.

**Comment by IzakMarais** [comment]
Yes, this is documented in the readme:
https://github.com/IzakMarais/reporter#query-parameters

You need to pass the api token a as a query paramter. eg. `/api/report/<dashBoardName>?apitoken=<token>`
