### ISSUE TITLE
Template documentation

### ISSUE THREAD

**Issue by onefourfive** [IzakMarais/reporter#253]
Is there a resource available to help edit Templates?

The example kind of shows but does not tell, in that it works but I'm not sure how.

In particular, I'd like to know if [[if .variable]] statements can be tested conditionally, ie something like `[[if .Id ==45]]\LaTeX Stuff[[end]]`.

**Comment by IzakMarais** [comment]
Yes, this is a pretty advanced feature and its documentation could be improved. It uses standard go templating, so you can have a look a the [documentation there ](https://golang.org/pkg/text/template/)to see how one could do conditional logic.

I would be open to accept a PR to improve the documentation, but I am not going to do so myself.
