### ISSUE TITLE
Error obtaining render for panel -  500 Internal Server Error

### ISSUE THREAD

**Issue by gui-sousa** [IzakMarais/reporter#265]
I am constantly facing a problem with rendering the panels. I trigger daily reports using the grafana report, but usually after a week I run into 500 Internal Server Error on all panels. Has anyone been through something similar?

![Captura de tela 2020-11-24 145653](https://user-images.githubusercontent.com/72104673/100133291-53f3e700-2e65-11eb-8184-e9f0b541b430.jpg)

**Comment by JanKraljic** [comment]
afaik: you cannot use grafana-clock-panel

**Comment by vijayvj6796** [comment]
I do have the Same issue

**Comment by gui-sousa** [comment]
Thank you @JanKraljic ! is functional! In fact it does not work with elements such as clockwork or others other than the native basics of graphane
