### ISSUE TITLE
Show all rows of the table in report and grid-layout in web api?

### ISSUE THREAD

**Issue by chamchenpion** [IzakMarais/reporter#277]
Is there any chance to show all rows of the table in the pdf?

The other question is that how to use grid-layout in the web API?

Thanks for your response in advance.

**Comment by IzakMarais** [comment]
> Is there any chance to show all rows of the table in the pdf?

This is not possible in the reporter. A comment [here](https://github.com/IzakMarais/reporter/issues/296#issuecomment-844739125) hints at a way it might be done via Granfana, but does not provide details.
