### ISSUE TITLE
Support Grafana 5.0 API changes

### ISSUE THREAD

**Issue by cchance27** [IzakMarais/reporter#28]
Has this been tested against the 5.0 rework? As i know the dashboard permalinks have been changed etc. I'm gonna prep a box to test it but was wondering if the devs have checked it for compatability yet?

**Comment by IzakMarais** [comment]
Nope, sorry. I have not checked yet. 

A PR would be welcome. I wonder what would be the best approach to handle such a breaking change? One could release a new version that only works with 5.0 and have the old version work with pre 5.0 grafana. Or it could support both via a grafana-version flag...

**Comment by h4cc** [comment]
Does not work directly. I am trying to figure out whats going on.

**Comment by IzakMarais** [comment]
I just downloaded grafana 5.0 and tested against the latest master of grafana-reporter. Everything seems to work fine. Closing this issue until I get some concrete examples to the opposite.

**Comment by IzakMarais** [comment]
Hmm [from the docs](http://docs.grafana.org/guides/whats-new-in-v5/#api-changes) I see:

> New uid-based routes in the dashboard API have been introduced to retrieve and delete dashboards. The corresponding slug-based routes have been deprecated and will be removed in a future release.

**Comment by HighKeep** [comment]
Not the greatest workaround, but I didn't have time to look for a better working solution at the moment. I personally left in the original for backwards compatibility. Regardless, it does look like rows are being fazed out.

```
type dashContainer struct {
	Dashboard struct {
		Title       string
		Description string
		Rows        []Row
		Panels      []Panel
	}
	Meta struct {
		Slug string
	}
}

func (dc dashContainer) NewDashboard(variables url.Values) Dashboard {
	var dash Dashboard
	dash.Title = sanitizeLaTexInput(dc.Dashboard.Title)
	dash.Description = sanitizeLaTexInput(dc.Dashboard.Description)
	dash.VariableValues = sanitizeLaTexInput(getVariablesValues(variables))

	if len(dc.Dashboard.Rows) == 0 {
		for _, p := range dc.Dashboard.Panels {
			p.Title = sanitizeLaTexInput(p.Title)
			dash.Panels = append(dash.Panels, p)
		}
		return dash
	}
	for _, row := range dc.Dashboard.Rows {
		row.Title = sanitizeLaTexInput(row.Title)
		dash.Rows = append(dash.Rows, row)
		for _, p := range dc.Dashboard.Panels {
			p.Title = sanitizeLaTexInput(p.Title)
			dash.Panels = append(dash.Panels, p)
		}
	}
        return dash
}
```

**Comment by IzakMarais** [comment]
bq.  Regardless, it does look like rows are being fazed out.

Yes and this type of solution for supporting both seems to be required, since old imported dashboards still return rows when fetched via the new API Grafana 5.

**Comment by IzakMarais** [comment]
> `Dashboard Dashboard // This seemed to make more sense to me.`

I missed this bug (was introduced in a recent PR).  Luckily it seems harmless. Fixed it now while making the other changes.

**Comment by IzakMarais** [comment]
The v2.0.0 release addresses this issue. 

https://github.com/IzakMarais/reporter/releases/tag/v2.0.0
