### ISSUE TITLE
Error obtaining render: 500 Internal Server Error

### ISSUE THREAD

**Issue by PePoDev** [IzakMarais/reporter#286]
### Error messaage
```
error rendering PNGs in parralel for dash {Title:AWS Billing Description:Visualize estimated AWS charges per AWS resource (EC2, S3, ...) VariableValues:CloudWatch Rows:[] Panels:[{Id:1 Type:graph Title:Estimated charges GridPos:{H:15 W:24 X:0 Y:0}} {Id:3 Type:graph Title:Estimated daily charges GridPos:{H:10 W:24 X:0 Y:15}}]}: error getting panel {Id:3 Type:graph Title:Estimated daily charges GridPos:{H:10 W:24 X:0 Y:15}}: Error obtaining render: 500 Internal Server Error
```

### Example dashboard
![image](https://user-images.githubusercontent.com/15852891/112786643-ebba4980-9080-11eb-9bd0-759e21ba9419.png)

**Comment by mankuuuuu** [comment]
Hi @PePoDev I was facing the same issue while rendering please check if all the dependent libraries are installed - https://grafana.com/docs/grafana/latest/administration/image_rendering/#troubleshoot-image-rendering.

I installed the rendering libraries for Ubuntu and it worked fine for me.

**Comment by PePoDev** [comment]
@mankuuuuu I don't know this is a problem on Grafana. Thanks a lot.
