### ISSUE TITLE
Zabbix trigger panel not showing up

### ISSUE THREAD

**Issue by ATECU** [IzakMarais/reporter#29]
I'm using the Zabbix plugin in Grafana, and when I try to render a pdf, the Triggers Panel won't show up, it's appears empty like this:
![imagem](https://user-images.githubusercontent.com/28969174/36332309-95e4ec64-1369-11e8-9d79-87300415d609.png)
I tried giving it a delay, but still wouldn't load.

Any help would be appreciated.

Thanks

**Comment by IzakMarais** [comment]
Sorry for the dealy, I somehow missed this issue. 

I have never used Zabbix; 
* do any of its other panels show up? Or does it only support a Trigger panel?
* If you try using curl to make a similar GET request to the one the reporter makes [here](https://github.com/IzakMarais/reporter/blob/master/grafana/api.go#L112), do you get a result?

**Comment by IzakMarais** [comment]
My guess is that since Zabix is a plugin, this is related to https://github.com/IzakMarais/reporter/issues/17. Will have to investigate whether there is a generic way to add support for all panels.

**Comment by IzakMarais** [comment]
Opened an issue with the grafana project, since I suspect PNG rendering support for plugin panels is lacking.

**Comment by IzakMarais** [comment]
@ATECU In the latest Grafana, can you share the Zabbix panel as a PNG? (It is an option that is available via the Grafana UI in the _panel options->Share->Direct link rendered image_)

**Comment by ATECU** [comment]
@IzakMarais just tested with the latest grafana, can't export the panel to .PNG also using /render/ doesn't work too, the other panels work fine.

![imagem](https://user-images.githubusercontent.com/28969174/37146076-a8eb9988-22ba-11e8-9b48-9d1fbf971544.png)

**Comment by IzakMarais** [comment]
Thanks for confirming, I suggest you log an issue at the zabbix plugin then.
