### ISSUE TITLE
Grafana reporter is cutting my  table

### ISSUE THREAD

**Issue by DjangoDani** [IzakMarais/reporter#296]
Hello,

First of all, thank you very much for developing such tool freely.

I'm facing an issue when i download the report itself, it is cutting part of my table when i use grid-layout. Is there a way to solve this issue by changing something or change the width which the table is generated?

Thanks in advance,
Daniel Nascimento

**Comment by love01211** [comment]
In the default options, the width of the output table is 1000 and the height is 500, so you can adjust the width of each column of your table through grafana, or modify the value in the code

**Comment by therus000** [comment]
with which option i can use it?
can u share please. what should i run in docker file to change this defualt settings

**Comment by rllyryan** [comment]
Hi @love01211 ,

I would also like to see where is this "default settings" that you mentioned.

**Comment by IzakMarais** [comment]
Duplicates https://github.com/IzakMarais/reporter/issues/277
