### ISSUE TITLE
grafana-reporter: command not found

### ISSUE THREAD

**Issue by drled** [IzakMarais/reporter#301]
I'm trying to install the reporter in a Ubuntu envirement: upon entering the "grafana-reporter" command i get:
ubuntu@:~/go/bin$ grafana-reporter
**grafana-reporter: command not found**

Any ideas? There were no errors during installation.

**Comment by ghost** [comment]
Is `$GOPATH/bin` (e.g `/root/.go/bin`) in you system path?

**Comment by drled** [comment]
![grafana_reporter_error](https://user-images.githubusercontent.com/9850136/123659248-c29d8680-d832-11eb-8d13-791155e62a7e.png)

if i navigate to the folder i still get this issue

**Comment by ghost** [comment]
To execute a file in the same folder you have to `./grafana-reporter`

Anyways, you can `export PATH=$PATH:/path/to/go/bin` so the command is now in your path and your terminal will be able to locate it! In this case, you should do:

    export PATH=$PATH:$GOPATH/bin

**Comment by drled** [comment]
This did the trick for me, is working fine now. Thank you!
