### ISSUE TITLE
PDF graph not complete with selected time range

### ISSUE THREAD

**Issue by smarkm** [IzakMarais/reporter#319]
Anyone face this issue
1. this is not always reappear
2. grafana show well, but in export pdf sometime some graph have little gaps in front or end of graph
![image](https://user-images.githubusercontent.com/5517120/153820787-dfc11200-95a6-40b5-8bf4-da2bb7d8246a.png)
grafana

![image](https://user-images.githubusercontent.com/5517120/153821216-65f0e78c-8fcf-4d2d-882e-e54321420abb.png)
pdf

**Comment by IzakMarais** [comment]
I don't have a solution for this.
