### ISSUE TITLE
Unable to Organize my Panels

### ISSUE THREAD

**Issue by afonsomarquesersc** [IzakMarais/reporter#323]
Hi, can someone tell me if I can organize my panels per page? Example: I want one panel in a page and then two panels in another page.

**Comment by IzakMarais** [comment]
No this is not possible. 

    On Monday, April 11, 2022, 05:38:00 PM GMT+2, afonsomarquesersc ***@***.***> wrote:  
 
 


Hi, can someone tell me if I can organize my panels per page? Example: I want one panel in a page and then two panels in another page.

**Comment by afonsomarquesersc** [comment]
Hi, i was able to organize it by creating a new template, but my graphs keep coming duplicated. 
My template(without packages and title page):
documentclass is defined as a report not as an article, but using article type the problem remains.
%%%%%
\chapter{Text}
\begin{figure}[!htpb]
    \centering
    \includegraphics[width=\textwidth]{image[[38]]}
\end{figure}
\FloatBarrier
\newpage
\section{Norte}
\begin{figure}[!htpb]
    \centering
    \includegraphics[width=\textwidth]{image[[4]]}
\end{figure}
\begin{figure}[!htpb]
    \centering
    \includegraphics[width=\textwidth]{image[[5]]}
\end{figure}
\newpage
\section{Sul}
\begin{figure}[!htpb]
    \centering
    \includegraphics[width=\textwidth]{image[[6]]}
\end{figure}
\begin{figure}[!htpb]
    \centering
    \includegraphics[width=\textwidth]{image[[7]]}
\end{figure}

**Comment by IzakMarais** [comment]
Jup, custom templates might help, bit this is pretty advanced, so you are on your own with debugging.
