### ISSUE TITLE
go get doent work

### ISSUE THREAD

**Issue by dustennL** [IzakMarais/reporter#325]
Im getting a issue that "go get -v url" doesnt do anything. i have go installed and i tryied to use go get in other projects and works.
I have git 2.20.1 installed in the machine, but i dont think this version is old enough to cause this problem.
Any tips ?

**Comment by dustennL** [comment]
turns out go its fine, but when i run the go install comand , doesnt install anything

**Comment by NoelzeN** [comment]
I thought I had the same issue, because it didn't show anything being installed and also the grafana-reporter command didn't work. However then I found the binary in 

/home/XXXX/go/bin/grafana-reporter

which simply wasn't in my path. Did you check that? Maybe it's the same for you

**Comment by IzakMarais** [comment]
Thanks for the feedback @NoelzeN
