### ISSUE TITLE
Dockerfile build not working

### ISSUE THREAD

**Issue by brionholland** [IzakMarais/reporter#329]
I followed along with the issues from #322 and while the perl-switch now works, tinytxx is having an issue when building from http://raw.githubusercontent.com/rstudio/tinytex/main/tools/install-unx.sh.  

#7 8.521 OK: 48 MiB in 27 packages
#7 9.754 mv: can't rename 'texlive/*': No such file or directory

This is referencing this line..

mv texlive/* $TEXDIR

on the above install.sh link.  I don't know much of anything about tinyTeX.  Any help would be apprciated.

**Comment by IzakMarais** [comment]
May be related to https://github.com/IzakMarais/reporter/pull/304
