### ISSUE TITLE
Add query parameters to include theme

### ISSUE THREAD

**Issue by henjoe** [IzakMarais/reporter#330]
Hi, I wonder if there is an option to make the report in Dark theme? 
I am using grafana in dark theme, but the report outputs in light theme.

Thank and regards,
Henjoe

**Comment by IzakMarais** [comment]
I'm not actively accepting feature requests for the reporter, so this is unlikely.

**Comment by henjoe** [comment]
Hi @IzakMarais no problem, and I understand. 
Thanks for confirming. 

Regards,
Henjoe
