### ISSUE TITLE
Error obtaining render for panel [..]Retrying after 10s - Error 500

### ISSUE THREAD

**Issue by subodh2711** [IzakMarais/reporter#337]
Hi @IzakMarais 

I am getting this issue which everybody reported:https://github.com/IzakMarais/reporter/issues/39

My grafana version is 8.4.1

Error obtaining render for panel {Id:7 Type:graph Title:Test Graph GridPos:{H:11 W:12 X:0 Y:22}}, Status: 500, Retrying after 20s...

**Comment by subodh2711** [comment]
`error rendering PNGs in parralel for dash {Title:: VariableValues: Rows:[] Panels:[{Id:2 Type:graph Title: GridPos:{H:11 W:12 X:0 Y:0}} {Id:4 Type:piechart Title: GridPos:{H:11 W:12 X:12 Y:0}} {Id:5 Type:graph TitleGraph GridPos:{H:11 W:12 X:0 Y:11}} {Id:6 Type:piechart Title:Graph( Pie Chart) GridPos:{H:11 W:12 X:12 Y:11}} {Id:7 Type:graph Title:Graph GridPos:{H:11 W:12 X:0 Y:22}} {Id:8 Type:piechart Title Graph( Pie Chart) GridPos:{H:11 W:12 X:12 Y:22}}]}: error getting panel {Id:2 Type:graph Title: Graph(From 4th March) GridPos:{H:11 W:12 X:0 Y:0}}: Error obtaining render: 500 Internal Server Error`

**Comment by ItsABug123** [comment]
Did you find a solution on this? I have tried various data types, graph, chart, stat ect but still getting the same error. 
I installed the image render Grafana plug in, which was mentioned a few times to fix the issue but now I cannot even get the PDF to open.

**Comment by Dariod9** [comment]
I had the same error for a while. After looking into my Grafana Server, the error originated from missing libraries regarding the Image Rendering Plugin. It seemed like Grafana still couldn't render images even with the plugin.

As such, I installed all dependencies related to that subject (seen on a project called "Puppeteer") and it worked! :)

Dependencies:
`ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils`

(from https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix or )

**Comment by IzakMarais** [comment]
THanks for the feedback @Dariod9 .
