### ISSUE TITLE
Default features of reporter 

### ISSUE THREAD

**Issue by ItsABug123** [IzakMarais/reporter#339]
I have a dashboard with populated data from a CANN message however it doesn't matter what type of visualisation I used I still receive the below error message. 

```
2022/10/18 14:29:13 Populated dashboard datastructure: {Title:Battery Build Description: VariableValues: Rows:[] Panels:[{Id:8 Type:bargauge Title:Station 3 Serial number GridPos:{H:4 W:18 X:0 Y:0}}]}
2022/10/18 14:29:13 Downloading image  8 http://localhost:3000/render/d-solo/JFwlGBWnz/_?from=now-5m&height=160&panelId=8&theme=light&to=now&width=720
2022/10/18 14:29:13 Error obtaining render for panel {Id:8 Type:bargauge Title:Station 3 Serial number GridPos:{H:4 W:18 X:0 Y:0}}, Status: 500, Retrying after 10s...

```

is there a way of finding out what definitely can be used to generate a report please?

**Comment by ItsABug123** [comment]
I am also currently trying to get access to our Grafana log on the server and I have been using the panel share> direct image rendered cheat to see if would render any but no visualization works.

**Comment by IzakMarais** [comment]
The reporter does not support non-standard panels.
