### ISSUE TITLE
How to change images size that are rendered using '-grid-layout'?

### ISSUE THREAD

**Issue by giuliomagnifico** [IzakMarais/reporter#342]
Hi,
as the title, using normal layout I've done it, but when I switch to the grid layout the size are always the same, every value I use/change inside the api.go. That's weird because the other changes (i.e. `int(p.GridPos.W * 40)` are affecting the pdf layout obviously, but not the value inside the image size parameters, they work only in not grid layout.

Thanks

**Comment by IzakMarais** [comment]
Sorry but getting back into the code to find an answer to this is not something I have time for now. No community feedback, so closing the issue.
