### ISSUE TITLE
Openshift Grafana route addr update instead of Grafana IP and port into Grafana reporter.

### ISSUE THREAD

**Issue by joe00712** [IzakMarais/reporter#345]
Hi Izak,
I'm running Grafana over openshift with external Grafana-Reporter using "podman run -d -p 8686:8686  --network=host izakmarais/grafana-reporter".
Grafana is served from openshift route 
and Grafana reporter had only flag "-ip string"  which takes Grafana IP and port. (default "localhost:3000").

So is there any way that i can give openshift route to it ?

**Comment by joe00712** [comment]
@IzakMarais , Do we have some solution regarding the same ?

**Comment by joe00712** [comment]
@IzakMarais, 

Seeking your support for this point.

**Comment by IzakMaraisTAL** [comment]
I don't have experience with openshift or its routing. As I recall the ip string is just passed to the Go standard http library, so it should be pretty general (be able to resolve DNS names).  

If that does not work, I suggest changing your network configuration or forking and modifying the reporter source code.
