### ISSUE TITLE
Grafana device or resource busy

### ISSUE THREAD

**Issue by DulceMgb256** [IzakMarais/reporter#346]
Before it did not show the message and it worked excellently I have used it for a year but when I generate a report and I have an error, this is the message:

error fetching dashboard ZMaqtZL8z: error executing getDashboard request for http://localhost:3000/api/dashboards/uid/ZMaqtZL8z?var-customer=AD&var-filesystem=All&var-server=AFRGHSDRWE&var-total_filesystem=All: Get http://localhost:3000/api/dashboards/uid/ZMaqtZL8z?var-customer=AD&var-filesystem=All&var-server=AFRGHSDRWE&var-total_filesystem=All: dial tcp: lookup localhost: device or resource busy

**Comment by IzakMarais** [comment]
I don't know. My guess is a networking problem unrelated to the reporter.
