### ISSUE TITLE
Variables for Repeating Panels

### ISSUE THREAD

**Issue by n3k232** [IzakMarais/reporter#36]
Hey,

i got the Issue in Version 1.0 when i use the Variables like "&var-Hostname=Host1&var-Hostname=Host2" for my Dashboard wich is configure to use repeating Panels by Hostname, the generated report shows my two variables, but only shows Images from the first Host.

**Comment by IzakMarais** [comment]
I'm not sure that the reporter plays nicely with repeating panels; I haven't used that feature myself. See [this comment](https://github.com/IzakMarais/reporter/issues/23#issuecomment-356584735) for a more detailed explanation on why I think this is unlikely to work. 

Furthermore, multiple variable support does not imply you can provide conflicting values for the same variable. Rather, if you have a dashboard that takes two different variables as input, e.g. `var-hostname=host1&var-port=eth0`, both of these would be passed through to Grafana when fetching the each png panel. 

I suggest you look at the Grafana dashboard data model and HTTP API and play around with curl or wget and see if you can get all access the panels you anticipate. I don't think it is possible, but If I am missing something, please re-open this issue.
