### ISSUE TITLE
Run grafana-reporter in the background

### ISSUE THREAD

**Issue by JJ24093006** [IzakMarais/reporter#361]
@IzakMarais  please can you help me here: I want to run grafana-reporter in the background. I need it because I restart my pc frequently and I want to get rid of the process where I have to open terminal and need to type "grafana-reporter". how can I do it? does it possible?

**Comment by IzakMarais** [comment]
Sure, you can run it in the background just like any other process. There are many different ways to do that depending on your OS. However, that is not a feature of the process (grafana-reporter) but of the OS. Do an internet search for running a process in the background. Options that come to mind are bash `&`, screen or systemd.

**Comment by JJ24093006** [comment]
Hi I have tried it with batch file. It starts the grafana-reporter but it is not hiding the console. Do you know, can we hide grafana-reporter process ?

**Comment by JJ24093006** [comment]
I am able to minimze the command prompt. if anyone will have a soltuion to hide it, please update it here. For a moment I am closing this issue.

start /min cmd /c "your batch file".

use this in your new batch file and run it with startup.
