### ISSUE TITLE
not available on hub?

### ISSUE THREAD

**Issue by cchance27** [IzakMarais/reporter#37]
Any reason this isn't already on the dockerhub, seems insanely useful, i saw you already did the dockerfile/compose for it but checked on hub and its not present yet

**Comment by IzakMarais** [comment]
Thanks for the suggestion; the docker support was added in a PR by @chiefy, I don't use it myself. 

I suppose uploading it to dockerhub should be easy. If you think it will be useful, I can do it. 

The texlive installation balloons the size of the docker image to 2.8Gb. Is that acceptable? 

@chiefy: is there any Docker magic, or other way of installing texlive (I see you used wget in stead of a repository) that could bring the size down?

**Comment by chiefy** [comment]
I setup a project [for my fork on quay.io](https://quay.io/repository/chiefy/grafana-reporter).

@IzakMarais if you create a project on quay or docker hub, if you add me I can hook everything up. 

For now:

```
docker pull quay.io/chiefy/grafana-reporter:latest
```
is a build off `master`

```
docker pull quay.io/chiefy/grafana-reporter:2.0.0
```
is tag `v2.0.0`

**Comment by IzakMarais** [comment]
@chiefy Thanks. I created the project on docker hub and added you as collaborator. May its worth while to add a docker-publish task to the Makefile too?
