### ISSUE TITLE
Custom latex report 

### ISSUE THREAD

**Issue by goks69** [IzakMarais/reporter#371]
Team,

Am having custom latex file along with it's required images and file and it's already working in my monolithic Grafana reporter service. Now we're planning to migrate in to Docker setup where we are facing difficulties mapping the custom template directory to my own template directory.

Please provide workaround to fix this . Am not sure if this require any source code changes or Dockerfile changes.

Thanks,
Gokul

**Comment by IzakMaraisTAL** [comment]
You could build a custom docker image with reporter and your template. Or you  could mount your report in the existing docker image. However, you will have to figure out the details yourself, I don't have capacity to provide such support.

**Comment by goks69** [comment]
Hi IzakMarais,

Thanks for the response.

As per the documentation given below, I've passed the -cmd_template flag (to define custom default .Tex template) and -templates flag (to define custom template path).

Note: Yes, as you said I've already mounted the template as persistent volume in container with correct permission.

![image](https://github.com/user-attachments/assets/ecc68921-bff1-4b0e-8bfa-d3fd2c02f589)

Even though th e above configuration I tried, the reporter is still using default template.

**Comment by IzakMaraisTAL** [comment]
Have you got this working without the custom docker container? If so, the arguments should be exactly the same in both cases. You should focus your attention on confirming that that the volume mount is visible from within the container and present at the path you expect.
