### ISSUE TITLE
Reporter should not try to download panel images for panels with type "row"

### ISSUE THREAD

**Issue by n3k232** [IzakMarais/reporter#38]
Hi,

like in the titel when i use the reporter it trys do download 7 images when i only got 6 Images.
It looks like it trys to download the row as a PNG.
For exampe it trys to Download the Panel with id 12 but the only thing with the id 12 is the Row

**Comment by IzakMarais** [comment]
Could you please provide the following?
* exported dashboard json 
* which reporter endpoint was used
* which grafana version was used

**Comment by n3k232** [comment]
exported dashboard json:
[dashboard.txt](https://github.com/IzakMarais/reporter/files/1784891/dashboard.txt)

which reporter endpoint was used:
http://localhost:8686/api/v5/report/000000005

which grafana version was used: v.5.0.0 Stable

**Comment by IzakMarais** [comment]
Thanks for the examples.

I suspect that this is a grafana v4 dashboard imported into Grafana v5? Regardsless, the json structure shows 7 Panels, but one has type "row" as opposed to type "graph".
