### ISSUE TITLE
VariableValues supress when Variable is hidden

### ISSUE THREAD

**Issue by sorenje** [IzakMarais/reporter#41]
Hi
Thanks for updating grafana-reporter to version 2, much appreciated.

I have a small request, is it possible not to show hidden Variables in VariableValues.

example i have 

$server
$path (it's hidden and always displaying All)

This generates
VariableValues:serverFQDN, All 

where ", All" is because i display all mountpoints, but i really don't need ", All" printed in pdf.

it's the same when i choose to hide my Variable

using [[.VariableValues]] to display servername in the report as generating pictures from text $server is not transparent in version 5.

**Comment by sorenje** [comment]
it's not that important for now, currently i just removed ", All" using latex xstring package.

\StrDel{[[.VariableValues]]}{, All}

**Comment by IzakMarais** [comment]
Glad you found a workaround to your problem. Thanks for letting me know.

I'm going to close this for now, but will consider reopening it if other people also have interest in this use case.
