### ISSUE TITLE
Grafgana reporter on AWS EC2

### ISSUE THREAD

**Issue by VOrlyanchik** [IzakMarais/reporter#45]
Hi Izak,

I'm using Grafana on EC2 instance and trying to generate reports. Unfortunately, http://AWSPublicDNS:8686/api/report/XyzXyz cannot be reached (grafana is on port 3000 and could be seen at http://AWSPublicDNS:3000/d/XyzXyz... ) Is there something I'm missing in configuration?

Thanks,
Vlad

**Comment by IzakMarais** [comment]
From your example url it seems like you using grafana v5, but still using the report endpoint for an older grafana. Your report endpoint should look like thes: https://github.com/IzakMarais/reporter#endpoint
However, this should still render something or return an error, so I doubt it is the cause of your problem. 

Apart from that your port numbers look good. What debugging steps have you tried? Have you confirmed that the reporter is running and serving on :8686 (`netstat -tlnp`). I haven't used EC2, so I don't know whether there are specific configuration options you might need on that side, but if both applications are running on the same node, it should work easily.

**Comment by VOrlyanchik** [comment]
I've tried container version and it worked just fine. Thanks for your help and very nice and useful Grafana feature!!!
