### ISSUE TITLE
CJK character support

### ISSUE THREAD

**Issue by tj13** [IzakMarais/reporter#46]
As the title said. 
If the grafana dashboard contains Chinese character, it will be empty in the ouput PDF.

**Comment by IzakMarais** [comment]
Could you provide an example dashboard.json file and PDF?

**Comment by CarrotCL** [comment]
Hi there, I found that the problem could be solved simply by installing Chinese fonts on the OS! 
![image](https://user-images.githubusercontent.com/52305869/60314641-e99bf600-9995-11e9-9525-352ab833fb42.png)

**Comment by IzakMarais** [comment]
Excellent, thanks for the feedback.

**Comment by lynnsummersmell** [comment]
> Hi there, I found that the problem could be solved simply by installing Chinese fonts on the OS!
> ![image](https://user-images.githubusercontent.com/52305869/60314641-e99bf600-9995-11e9-9525-352ab833fb42.png)

helo,
can you remember how you install chinese fonts on os,thanks?

i have met the same Promblem，i have installed all chinese but the error still appear.
========================================================================
lilin0607@TPL-0000-163173  ~  dpkg -l |grep -i latex |grep chin
ii  latex-cjk-chinese                          4.8.4+git20170127-2                          amd64        Chinese module of LaTeX CJK
ii  latex-cjk-chinese-arphic-bkai00mp          1.23                                         all          AR PL KaitiM Big5 fonts for CJK
ii  latex-cjk-chinese-arphic-bsmi00lp          1.23                                         all          AR PL Mingti2L Big5 fonts for CJK
ii  latex-cjk-chinese-arphic-gbsn00lp          1.23                                         all          AR PL SungtiL GB fonts for CJK
ii  latex-cjk-chinese-arphic-gkai00mp          1.23                                         all          AR PL KaitiM GB fonts for CJK
 lilin0607@TPL-0000-163173  ~  dpkg -l |grep -i texlive |grep chin
ii  texlive-lang-chinese                       2017.20180305-1                              all          TeX Live: Chinese
 lilin0607@TPL-0000-163173  ~  locale
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:en_US:en
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
 lilin0607@TPL-0000-163173  ~  

2019/11/28 09:15:05 Calling LaTeX - preprocessing
2019/11/28 09:15:05 Error generating report: error calling LaTeX preprocessing: "exit status 1". Latex preprocessing failed with output: This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./report.tex
LaTeX2e <2018-12-01>
(/opt/TinyTeX/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/opt/TinyTeX/texmf-dist/tex/latex/base/size10.clo))
(/opt/TinyTeX/texmf-dist/tex/latex/graphics/graphicx.sty
(/opt/TinyTeX/texmf-dist/tex/latex/graphics/keyval.sty)
(/opt/TinyTeX/texmf-dist/tex/latex/graphics/graphics.sty
(/opt/TinyTeX/texmf-dist/tex/latex/graphics/trig.sty)
(/opt/TinyTeX/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/opt/TinyTeX/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/opt/TinyTeX/texmf-dist/tex/latex/geometry/geometry.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/opt/TinyTeX/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
No file report.aux.
(/opt/TinyTeX/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/opt/TinyTeX/texmf-dist/tex/latex/oberdiek/grfext.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/kvdefinekeys.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)))
(/opt/TinyTeX/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/opt/TinyTeX/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty)
(/opt/TinyTeX/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex

! Package inputenc Error: Unicode character 物 (U+7269)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.11 \maketitle

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on report.log.

**Comment by lynnsummersmell** [comment]
> installing Chinese fonts on the OS

What is 'installing Chinese fonts on the OS' mean ?
linux font,latex font,texlive font？
I have installed all three type fonts，still error。。
Thank you

**Comment by IzakMarais** [comment]
@CarrotCL , do you have more detail?
