### ISSUE TITLE
Add Support for discrete panel

### ISSUE THREAD

**Issue by jreineke-nli** [IzakMarais/reporter#47]
Hi,

at first, thank you for the great plugin. I am trying to use the reporter with the [discrete panel](
https://grafana.com/plugins/natel-discrete-panel) for grafana. But currently I think this panel is not implemented yet.
Is it possible to add the support for this panel? It would be very useful for me because i have to report the availabilty of services which I can get from the discrete panel.

Regrads
Jonas

**Comment by IzakMarais** [comment]
It should work without any special support in the reporter *if* it works properly with PNG sharing. You can test this from the grafana GUI: _Share_ the panel and view the _Direct link rendered image_. If that works and it does not work en reporter, please reopen this issue. Else, it is a bug in the panel itself that you should log there.
