### ISSUE TITLE
Text panel too large

### ISSUE THREAD

**Issue by Knaky41** [IzakMarais/reporter#52]
Hi,

I've implemented the reporter with success with Grafana 4.X

I've migrated to V5, and I’m unable to set the size of the text panel, it takes a large space on the PDF.

I've tried to change the properties of the JSON dashboard but without success.

Do you have a solution to have the text panel to be as large as one line of text?

Thanks in advance,

Cheers

**Comment by herrkutt** [comment]
I’ve had similar issues and it seems all of the panel values are hard coded
for a certain height. I’ve been trying to work on a way to pass in height
values for certain panels via the link URL but haven’t had much time.
However I think if parameters like this could be added it would make it
more customizable.
panel_<panelName>_height=200
panel_text_height=200

**Comment by IzakMarais** [comment]
Yes, the panels are currently hardcoded [here](https://github.com/IzakMarais/reporter/blob/master/grafana/api.go#L160). Single stat panels are rendered slightly smaller and all other panels are rendered in a size: 1000x500 (the default size when using the `Share direct link rendered image` from the Grafana UI).

I've done some quick tests using the Grafana UI: setting the height for text panels to 100 seems to work nicely. If the text block small, it doesn't render a lot of empty space. If the text block is large, Grafana ignores the hight restriction and renders it large enough to display all the text. 

I will implement this improvement when I have some time.

**Comment by Knaky41** [comment]
Thanks for the quick answers :)

Could you please define how I setthe text panels to 100?

Cheers,

**Comment by IzakMarais** [comment]
> Could you please define how I set the text panels to 100?
Currently the height is hard coded (see the link to the source code in the previous post). Setting it to 100 will require source code modifications that I hope to get to before long. 

If you don't want to wait, you can create a PR, making the changes at the location linked to above. You will have to add an `if` and the ability to test for text panels and set the height accordingly.

**Comment by Knaky41** [comment]
Ok thanks 👍 

I'll wait for your clean version :p 

Cheers
