### ISSUE TITLE
how to install pdflatex in PATH

### ISSUE THREAD

**Issue by ZycesZ** [IzakMarais/reporter#53]
Hey Guy's, 
First of im using centos 7 minimal and everything is working right. Even the pdflatex is installed, but if i wanna create a PDF for my Graphs in grafana i'm getting this one here;
"error calling LaTeX preprocessing: "exit status 1". Latex preprocessing failed with output: This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013)
 restricted \write18 enabled.

kpathsea: Running mktexfmt pdflatex.fmt
I can't find the format file `pdflatex.fmt'!"

It seems that pdflatex need something more then just the installation it self.. Or this is the wrong pdflatex...

Anyone any ideas?
Thanks!

**Comment by IzakMarais** [comment]
I'm afraid I don't have any experience installing pdflatex on minimal fedora 7. To aid debugging, I suggest you create a simple Tex file based on [the template](https://github.com/IzakMarais/reporter/blob/master/report/texTemplate.go) and try to use pdfLatex to make a pdf from it using the command line. 

Maybe something like:

```
\documentclass{article}
\usepackage{graphicx}
\usepackage[margin=1in]{geometry}
\graphicspath{ {images/} }
\begin{document}
\title{Dummy text}
\date{Dummy text}
\maketitle
\begin{center}
\begin{minipage}{0.3\textwidth}
\includegraphics[width=\textwidth]{dummy_image_file_you_should_create}
\end{minipage}
\end{center}
\end{document}
```

**Comment by IzakMarais** [comment]
Maybe this link has some help: https://unix.stackexchange.com/questions/91729/question-about-using-pdflatex-on-redhat-in-centos

**Comment by ZycesZ** [comment]
CentOS 7 not Fedora 7....
I've tried that one but no success.
Anyway, thank you!

**Comment by IzakMarais** [comment]
> CentOS 7 not Fedora 7....
Whoops, typo. Yes Fedora 7 would be ancient. 

Actually, come to think of it, you could try the same approach used in the Docker image [here](https://github.com/IzakMarais/reporter/blob/master/Dockerfile#L14). @chiefy downloaded a tar in stead of trying to use the texlive installation that comes with the package manager. 

Good luck. Please post back here if you find a solution.
