### ISSUE TITLE
Grabbing nonexistent panels, variables issue?

### ISSUE THREAD

**Issue by cchance27** [IzakMarais/reporter#55]
I have a dashboard, with 2 variables
$Location | label_values(sysLocation{job="canopy450"}, sysLocation) 
$IPAddress | label_values(sysLocation{sysLocation=~"$Location.*", job="canopy450"}, instance) | normally just set to all for repeating panels

I pass the grafanareporter the variables from the dashboard and whats funny is it works for the default view, like if location=xxxxxx by default (dashboard saved with xxxxx selected) and thats whats saved, i can call the grafanareporter for xxxxxx, but if i try to change location=yyyyyy i get the errors below and grafana ends up in a nasty long loop of phantamjs crashes

Whats also very VERY odd, is that in the call below you'll notice "panelid=10" and "panelid="22"

The report this partial debug below is from, should have only had 9 panels total... 

It kind of feels like somehow grafanareporter is not handling this sort of nested variables properly

4/13/2018 1:52:44 PMDBUG[04-13|17:52:44] [phantom] ERROR: null is not an object (evaluating 'e.panel')
4/13/2018 1:52:44 PMhttp://localhost:3000/public/build/0.2ba40e7163b7f9a6ed4b.js:15
4/13/2018 1:52:44 PMTRACE:
4/13/2018 1:52:44 PM -> : 0 (in function "apply")
4/13/2018 1:52:44 PM
4/13/2018 1:52:44 PM  phantomjs://code/render.js:48 in onError logger=png-renderer
4/13/2018 1:52:44 PMDBUG[04-13|17:52:44] [phantom] Loading a web page: http://localhost:3000/d-solo/wiFGLNqzz/_?from=now-7d&height=500&panelId=10&theme=light&to=now&var-IPAddress=All&var-Location=XXXXXXXXXXX&width=1000&render=1 status: success 60000 logger=png-renderer
4/13/2018 1:52:44 PMDBUG[04-13|17:52:44] [phantom] ERROR: null is not an object (evaluating 'e.panel')
4/13/2018 1:52:44 PMhttp://localhost:3000/public/build/0.2ba40e7163b7f9a6ed4b.js:15
4/13/2018 1:52:44 PMTRACE:
4/13/2018 1:52:44 PM -> : 0 (in function "apply")
4/13/2018 1:52:44 PM
4/13/2018 1:52:44 PM  phantomjs://code/render.js:48 in onError logger=png-renderer
4/13/2018 1:52:44 PMDBUG[04-13|17:52:44] [phantom] Loading a web page: http://localhost:3000/d-solo/wiFGLNqzz/_?from=now-7d&height=500&panelId=22&theme=light&to=now&var-IPAddress=All&var-Location=XXXXXXXXXXX&width=1000&render=1 status: success 60000 logger=png-renderer
4/13/2018 1:52:44 PMDBUG[04-13|17:52:44] [phantom] ERROR: null is not an object (evaluating 'e.panel')
4/13/2018 1:52:44 PMhttp://localhost:3000/public/build/0.2ba40e7163b7f9a6ed4b.js:15
4/13/2018 1:52:44 PMTRACE:
4/13/2018 1:52:44 PM -> : 0 (in function "apply")
4/13/2018 1:52:44 PM
4/13/2018 1:52:44 PM  phantomjs://code/render.js:48 in onError logger=png-renderer

**Comment by cchance27** [comment]
Ok i just grabbed

http://192.168.a.a:9000/api/v5/report/wiFGLNqzz?apitoken=xxxxxxxxxxxxxxxxxx=&template=fit&from=1523035282798&to=1523638750639&var-Location=yyyyyyyyyyyyyyyyyy&var-IPAddress=All

from my browser (logged into grafana), it loads fine and i get a pdf.

I opened up command line to download the pdf directly, and did a download via my command line (powershell/curl), and it failed, i checked on the grafana server and its doing the weird, panel id's...

4/13/2018 2:56:08 PMDBUG[04-13|18:56:08] [phantom] Loading a web page: http://localhost:3000/d-solo/wiFGLNqzz/_?from=1523035282798&height=500&panelId=14&theme=light&to=1523638750639&var-IPAddress=All&var-Location=xxxxxxxxxxxxxxx&width=1000&render=1 status: success 60000 logger=png-renderer
4/13/2018 2:56:09 PMDBUG[04-13|18:56:09] [phantom] ERROR: Maximum call stack size exceeded.
4/13/2018 2:56:09 PMhttp://localhost:3000/public/build/vendor.2c3c591224fb193f7fd3.js:15
4/13/2018 2:56:09 PMTRACE:
4/13/2018 2:56:09 PM -> : 0 (in function "apply")
4/13/2018 2:56:09 PM
4/13/2018 2:56:09 PM  phantomjs://code/render.js:48 in onError logger=png-renderer

**Comment by cchance27** [comment]
This is a problem in the API from grafana, it appears when templated variables return less values than the default saved variables (less repeated panels), then the api fills in the missing panels with the ones from the default variables

**Comment by IzakMarais** [comment]
Thanks for clarifying. Could you think of a workaround for your use case?
