### ISSUE TITLE
grafana-reporter as Systemd Service

### ISSUE THREAD

**Issue by n3k232** [IzakMarais/reporter#56]
Hey,
do you know a way to let the reporter run as a systemd-services, because i tried it and systemd keeps restarting the reporter.

here is my Service file

[Unit]
Description=Grafana Reporter
Wants=network-online.target
After=network-online.target

[Service]
User=grafana
Group=grafana
Type=notify
Restart=on-failure
WorkingDirectory=/opt/grafana-reporter
ExecStart=/opt/grafana-reporter/grafana-reporter

LimitNOFILE=10000
TimeoutSec=600

[Install]
WantedBy=multi-user.target

it seems that systemd i ignoring the timout setting of 600 because it keeps restarting the service every 30 seconds beacause of a timeout.

thanks and gereetings

**Comment by IzakMarais** [comment]
We run the reporter using systemd, but our file is a lot simpler:

```
[Unit]
Description=Grafana-reporter service. Creates pdf reports from grafana dashboards.

[Service]
Type=simple
WorkingDirectory=/opt/vastech/bin
ExecStart=/opt/vastech/bin/grafana-reporter -ip=localhost:2999
Restart=on-failure
```
Maybe there are some user permission problems on you system? I suggest simplifying you file as an aid to debugging.
