### ISSUE TITLE
Error getting grafana-clock plugin images

### ISSUE THREAD

**Issue by platnorm** [IzakMarais/reporter#57]
Hi Izak, thanks for your awesome tool.

I am getting this error when trying to get get a pdf for my dashboards which contains a granafa-clock panel. Apparently there is some issues getting the image.

 {Id:16 Type:graph Title:Interface Gi0/0/0(Connected-to-INWI):}]}: error getting panel {Id:18 Type:grafana-clock-panel Title:Time Clock}: Error obtaining render: 500 Internal Server Error

![image](https://user-images.githubusercontent.com/16169427/39527313-05498a80-4e19-11e8-851e-4df4dc6c816e.png)

I tried removing the clock panel and it worked.

Can you help please.

Thank you.

**Comment by IzakMarais** [comment]
It is likely that the clock panel does not work properly with PNG sharing. You can test this from the grafana GUI: _Share_ the panel and view the _Direct link rendered image_. If that works and it does not work in reporter, please reopen this issue. Else, it is a bug in the panel itself that you should log there.
