### ISSUE TITLE
Unauthorized during fetching dashboard

### ISSUE THREAD

**Issue by lorenzoguglielmo** [IzakMarais/reporter#59]
Hi,
we are using this pattern: 
Grafana 5.1.2 with LDAP auth
We have installed reporter, launched with go, created Report link in the dashboard. When we click on Report button, this error appears:

error fetching dashboard xxxxxxxxx: error obtaining dashboard from http://xxxxx.xxx.xx:3000/api/dashboards/uid/xxxxxxxxx?var-Host=xxxx.xxx.xx&var-datasource=telegraf_posta&var-inter=30s&var-server=xxxx.xx.xx%3A3334. Got Status 401 Unauthorized, message: {"message":"Unauthorized"}

Any suggestions?

Thank you so much.

**Comment by IzakMarais** [comment]
I'm not sure about the LDAP part, but you should generate an authorisation  apitoken in the grafana User interface and pass that along as decribed in the readme [here](https://github.com/IzakMarais/reporter#query-parameters).

**Comment by ZaheerFreeLancerAdmin** [comment]
try with apitoken.
/api/v5/report/{dashboardUID}?apitoken=12345
i have faced the same issue..
