### ISSUE TITLE
error calling LaTeX preprocessing: "exit status 1"

### ISSUE THREAD

**Issue by dbosanzio** [IzakMarais/reporter#60]
Hi,
we are using this pattern:
Grafana 5.1.2, CentOS Linux release 7.5.1804 (Core)
We have installed reporter, launched with go, created Report link in the dashboard. When we click on Report button, this error appears:

error calling LaTeX preprocessing: "exit status 1". Latex preprocessing failed with output: This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013)
 restricted \write18 enabled.

kpathsea: Running mktexfmt pdflatex.fmt
/usr/share/texlive/texmf/texconfig/tcfmgr: the command line utility of the fixed-length database API

usage:
  /usr/share/texlive/texmf/texconfig/tcfmgr create path [width [limsiz]]
  /usr/share/texlive/texmf/texconfig/tcfmgr inform [-nl|-nb] path
  /usr/share/texlive/texmf/texconfig/tcfmgr put [-nl|-nb] [-sx] [-dk|-dc|-dai|-dad] path key value
  /usr/share/texlive/texmf/texconfig/tcfmgr out [-nl|-nb] [-sx] path key
  /usr/share/texlive/texmf/texconfig/tcfmgr get [-nl|-nb] [-sx] [-px] [-pz] path key
  /usr/share/texlive/texmf/texconfig/tcfmgr list [-nl|-nb] [-m num] [-pv] [-px] [-rb lkey ukey] [-ri str] path
  /usr/share/texlive/texmf/texconfig/tcfmgr optimize [-nl|-nb] path [width [limsiz]]
  /usr/share/texlive/texmf/texconfig/tcfmgr importtsv [-nl|-nb] [-sc] path [file]
  /usr/share/texlive/texmf/texconfig/tcfmgr version

fmtutil: config file `fmtutil.cnf' not found.
I can't find the format file `pdflatex.fmt'!

 rpm -qa | grep -i texlive
texlive-pdftex-doc-svn29585.1.40.11-38.el7.noarch
texlive-amsmath-svn29327.2.14-38.el7.noarch
texlive-amsfonts-svn29208.3.04-38.el7.noarch
texlive-kastrup-svn15878.0-38.el7.noarch
texlive-bera-svn20031.0-38.el7.noarch
texlive-pst-coil-svn24020.1.06-38.el7.noarch
texlive-xcolor-svn15878.2.11-38.el7.noarch
texlive-latex-bin-svn26689.0-38.el7.noarch
texlive-ifxetex-svn19685.0.5-38.el7.noarch
texlive-chngcntr-svn17157.1.0a-38.el7.noarch
texlive-fp-svn15878.0-38.el7.noarch
texlive-breakurl-svn15878.1.30-38.el7.noarch
texlive-showexpl-svn27790.v0.3j-38.el7.noarch
texlive-l3packages-svn29361.SVN_4467-38.el7.noarch
texlive-url-svn16864.3.2-38.el7.noarch
texlive-mparhack-svn15878.1.4-38.el7.noarch
texlive-luaotfload-svn26718.1.26-38.el7.noarch
texlive-pst-fill-svn15878.1.01-38.el7.noarch
texlive-l3kernel-svn29409.SVN_4469-38.el7.noarch
texlive-pdfpages-svn27574.0.4t-38.el7.noarch
texlive-kpathsea-svn28792.0-38.el7.noarch
texlive-etex-pkg-svn15878.2.0-38.el7.noarch
texlive-carlisle-svn18258.0-38.el7.noarch
texlive-qstest-svn15878.0-38.el7.noarch
texlive-underscore-svn18261.0-38.el7.noarch
texlive-latex-fonts-svn28888.0-38.el7.noarch
texlive-luatex-svn26689.0.70.1-38.el7.noarch
texlive-xunicode-svn23897.0.981-38.el7.noarch
texlive-thumbpdf-svn26689.3.15-38.el7.noarch
texlive-pst-3d-svn17257.1.10-38.el7.noarch
texlive-pst-tree-svn24142.1.12-38.el7.noarch
texlive-filehook-svn24280.0.5d-38.el7.noarch
texlive-latex-bin-bin-svn14050.0-38.20130427_r30134.el7.noarch
texlive-tools-svn26263.0-38.el7.noarch
texlive-etoolbox-svn20922.2.1-38.el7.noarch
texlive-footmisc-svn23330.5.5b-38.el7.noarch
texlive-index-svn24099.4.1beta-38.el7.noarch
texlive-marginnote-svn25880.v1.1i-38.el7.noarch
texlive-filecontents-svn24250.1.3-38.el7.noarch
texlive-pdftex-bin-svn27321.0-38.20130427_r30134.el7.x86_64
texlive-memoir-svn21638.3.6j_patch_6.0g-38.el7.noarch
texlive-hyperref-svn28213.6.83m-38.el7.noarch
texlive-listings-svn15878.1.4-38.el7.noarch
texlive-pst-plot-svn28729.1.44-38.el7.noarch
texlive-lualatex-math-svn29346.1.2-38.el7.noarch
texlive-pdfpages-doc-svn27574.0.4t-38.el7.noarch
texlive-base-2012-38.20130427_r30134.el7.noarch
texlive-tetex-svn29585.3.0-38.el7.noarch
texlive-multido-svn18302.1.42-38.el7.noarch
texlive-psnfss-svn23394.9.2a-38.el7.noarch
texlive-soul-svn15878.2.4-38.el7.noarch
texlive-ifetex-svn24853.1.2-38.el7.noarch
texlive-algorithms-svn15878.0.1-38.el7.noarch
texlive-luatexbase-svn22560.0.31-38.el7.noarch
texlive-pgf-svn22614.2.10-38.el7.noarch
texlive-pst-text-svn15878.1.00-38.el7.noarch
texlive-koma-script-svn27255.3.11b-38.el7.noarch
texlive-oberdiek-svn26725.0-38.el7.noarch
texlive-pdftex-def-svn22653.0.06d-38.el7.noarch
texlive-kpathsea-bin-svn27347.0-38.20130427_r30134.el7.x86_64
texlive-xkeyval-svn27995.2.6a-38.el7.noarch
texlive-colortbl-svn25394.v1.0a-38.el7.noarch
texlive-sauerj-svn15878.0-38.el7.noarch
texlive-pst-math-svn20176.0.61-38.el7.noarch
texlive-float-svn15878.1.3d-38.el7.noarch
texlive-luatex-bin-svn26912.0-38.20130427_r30134.el7.x86_64
texlive-tipa-svn29349.1.3-38.el7.noarch
texlive-geometry-svn19716.5.6-38.el7.noarch
texlive-pst-node-svn27799.1.25-38.el7.noarch
texlive-pst-eps-svn15878.1.0-38.el7.noarch
texlive-currfile-svn29012.0.7b-38.el7.noarch
texlive-kpathsea-doc-svn28792.0-38.el7.noarch
texlive-hyphen-base-svn29197.0-38.el7.noarch
texlive-booktabs-svn15878.1.61803-38.el7.noarch
texlive-subfig-svn15878.1.3-38.el7.noarch
texlive-setspace-svn24881.6.7a-38.el7.noarch
texlive-enumitem-svn24146.3.5.2-38.el7.noarch
texlive-varwidth-svn24104.0.92-38.el7.noarch
texlive-babelbib-svn25245.1.31-38.el7.noarch
texlive-luaotfload-bin-svn18579.0-38.20130427_r30134.el7.noarch
texlive-latex-svn27907.0-38.el7.noarch
texlive-fancyvrb-svn18492.2.8-38.el7.noarch
texlive-pstricks-svn29678.2.39-38.el7.noarch
texlive-fontspec-svn29412.v2.3a-38.el7.noarch
texlive-kpathsea-lib-2012-38.20130427_r30134.el7.x86_64
texlive-lm-svn28119.2.004-38.el7.noarch
texlive-parallel-svn15878.0-38.el7.noarch
texlive-thumbpdf-bin-svn6898.0-38.20130427_r30134.el7.noarch
texlive-pst-grad-svn15878.1.06-38.el7.noarch
texlive-unicode-math-svn29413.0.7d-38.el7.noarch
texlive-graphics-svn25405.1.0o-38.el7.noarch
texlive-caption-svn29026.3.3__2013_02_03_-38.el7.noarch
texlive-paralist-svn15878.2.3b-38.el7.noarch
texlive-pdftex-svn29585.1.40.11-38.el7.noarch
texlive-attachfile-svn21866.v1.5b-38.el7.noarch
texlive-pstricks-add-svn28750.3.59-38.el7.noarch
texlive-eso-pic-doc-svn21515.2.0c-38.el7.noarch
texlive-tetex-bin-svn27344.0-38.20130427_r30134.el7.noarch
texlive-csquotes-svn24393.5.1d-38.el7.noarch
texlive-latexconfig-svn28991.0-38.el7.noarch
texlive-babel-svn24756.3.8m-38.el7.noarch
texlive-eso-pic-svn21515.2.0c-38.el7.noarch
texlive-ms-svn24467.0-38.el7.noarch
 rpm -qa | grep -i latex
texlive-latex-bin-svn26689.0-38.el7.noarch
texlive-latex-fonts-svn28888.0-38.el7.noarch
texlive-latex-bin-bin-svn14050.0-38.20130427_r30134.el7.noarch
texlive-lualatex-math-svn29346.1.2-38.el7.noarch
texlive-latex-svn27907.0-38.el7.noarch
texlive-latexconfig-svn28991.0-38.el7.noarch

Any suggestions?

Thank you so much.

**Comment by IzakMarais** [comment]
I suspect this is some issue with the pdflatex you installed on centos. It seems incomplete.

You should narrow down your debugging process by just trying to run pdflatex from the command line on your sever.

**Comment by IzakMarais** [comment]
Seems related to https://github.com/IzakMarais/reporter/issues/53. See that issue for some suggestions. Unfortunately that user never reported back on how he resolved his problem with pdflatex on centos.

**Comment by IzakMarais** [comment]
See also this comment: https://github.com/IzakMarais/reporter/issues/61#issuecomment-393349800 on how @4rCh3r got pdflatex working on his older version of centos.

**Comment by IzakMarais** [comment]
I am closing this, but please report back for future reference what you had to do to get pdflatex working on centos.

**Comment by DMBuce** [comment]
> I am closing this, but please report back for future reference what you had to do to get pdflatex working on centos.

I was able to get grafana-reporter working on CentOS 7 by installing packages:

    yum install texlive-latex-bin-bin texlive-cm texlive-pdftex-def texlive-ifluatex
