### ISSUE TITLE
Grafana Reporter command is not found

### ISSUE THREAD

**Issue by vanajavamsi** [IzakMarais/reporter#61]
I have installed grafana reporter in clients prod cluster but i am facing the issue , after installing the grafana reporter i triggered grafana-reporter command its showing command not found.
Could you please provide me the solution on this issue ASAP.

**Comment by IzakMarais** [comment]
As mentioned in the [readme](https://github.com/IzakMarais/reporter#getting-started), after running `go install` to install, the reporter binary will be in $GOPATH/bin. You should have received some error from the go compiler if it is not there.

**Comment by IzakMarais** [comment]
I don't think a missing reporter command is necessarily related to pdflatex. In that case you will get an error message like the one from #60.

 Please comment on that issue of you manage to get pdflatex working on centos what steps you had to follow.

**Comment by 4rCh3r** [comment]
My problem with Centos was the version of "tex live" I update manually from 2013 to 2016 do the following (download size 4.5GB aprox)
# yum erase texlive texlive*
Download the package from: https://www.systutorials.com/go/texlive-download/
Install with:
# ./install-tl
And set the path in "~/.bashrc"
export PATH=/usr/local/texlive/2018/bin/x86_64-linux:$PATH

**Comment by 4rCh3r** [comment]
@vanajavamsi If you still without see the application, you can do the next:
Run directly from:

> /root/go/bin/grafana-reporter

Assign the permissions:

> chmod 4755 /root/go/bin/grafana-reporter

I create a service on systemd (Im using Centos 7).

> /usr/lib/systemd/system/grafana-reporter.service

> [Unit]
> Description=grafana-reporter
> Wants=network-online.target
> After=network-online.target
> 
> [Service]
> User=root
> Type=notify
> Restart=on-failure
> ExecStart=/root/go/bin/grafana-reporter
> TimeoutStartSec=0
> 
> [Install]
> WantedBy=multi-user.target

Enable on startup:

> systemctl enable grafana-reporter
> systemctl start grafana-reporter

**Comment by IzakMarais** [comment]
Thanks for the extra help, @4rCh3r . 
No more feedback from original poster, closing issue.

**Comment by JoshHilliker** [comment]
very helpful.  Thank you.

**Comment by Daly123456** [comment]
Hi thanks for you solution @4rCh3r  ! but the file out.pdf generated was empty 
So how can i mention which Server i want to display on my generated report ?
![image](https://user-images.githubusercontent.com/46686877/77940497-ac5fee00-72b0-11ea-8095-d3797a96dc6b.png)

**Comment by korimeab** [comment]
Trying to get this running on windows,  any idea how can I get pdflatex?


2021/04/21 14:12:59 Calling LaTeX - preprocessing
2021/04/21 14:12:59 Error generating report: error calling LaTeX preprocessing: "exec: \"pdflatex\": executable file not found in %PATH%". Latex preprocessing failed with output:
