### ISSUE TITLE
Zabbix Thresholds arent included in the generated graph.

### ISSUE THREAD

**Issue by linuxtechie** [IzakMarais/reporter#65]
Zabbix Thresholds arent included in the generated graph. How can they be enabled? If you can hint me to the api code.

**Comment by IzakMarais** [comment]
The reporter renders the panel to PNG using the same functionality available from the user interface by going to _Panel > Share > Direct link rendered images_.  You can test that via the UI. 

This is probably a bug in the Zabix panel (similar to #63, a bug with image rendering in the text panel). If your UI test confirms this, please log a bug at that project.

**Comment by IzakMarais** [comment]
Duplicates https://github.com/IzakMarais/reporter/issues/29
