### ISSUE TITLE
How to print in landscape mode?

### ISSUE THREAD

**Issue by linuxtechie** [IzakMarais/reporter#66]
Didnt find any option to print in landscape mode or with different page size. How do I add them?

**Comment by IzakMarais** [comment]
You could achieve this by providing your own custom LaTeX template.

**Comment by IzakMarais** [comment]
See https://github.com/IzakMarais/reporter/issues/50 for a more detailed explanation.

**Comment by IzakMarais** [comment]
No further feedback from user. I assume the instructions from the linked issue were sufficient to resolve the question.
