### ISSUE TITLE
Error Obtaining Dashboard

### ISSUE THREAD

**Issue by FluffyAlpaca** [IzakMarais/reporter#67]
Hi, 

I'm running Grafana version 5.0.4 and grafana-reporter version 2.0.1. 
When I'm launching grafana-reporter, I got the error 

> error fetching dashboard znqUlOSiz: error obtaining dashboard from http://localhost:8000/api/dashboards/db/znqUlOSiz. Got Status 404 Not Found, message: {"message":"Dashboard not found"} 

When I try in a different tab, I can access it by modifying the URL : 

> http://localhost:8000/api/dashboards/uid/znqUlOSiz

I made grafana-reporter access to the dashboard by not using the uid but the slug, as explained here : 

> http://docs.grafana.org/http_api/dashboard/#get-dashboard-by-slug

so the URL looks like : 

> http://localhost:8686/api/report/dashboard_name?apitoken=XXX=

It's working, but not for too long I believe, as the doc explains the API function by slug is deprecated and will be removed. 

However, I saw that the support for grafana 5.0 has been released with the 2.0 version. So maybe I misconfigured my installation? Don't hesitate to tell me if you need any more information.

**Comment by IzakMarais** [comment]
Yes, grafana-reporter 2.0.x should support grafana 5.0 syntax. 
The reporter decides which version of the Grafana API to use based on which endpoint you invoke on the reporter. See [this section](https://github.com/IzakMarais/reporter#endpoint) of the readme. Did perhaps use the [deprecated grafana-reporter endpoint](https://github.com/IzakMarais/reporter#deprecated-endpoint)?

**Comment by FluffyAlpaca** [comment]
Aaa indeed thank you! It was a mistake from me, I took the deprecated path! 
Thank you for your help, have a nice day.
