### ISSUE TITLE
Unauthorized access in a reverse proxy with docker setup

### ISSUE THREAD

**Issue by andreasbrh** [IzakMarais/reporter#69]
Hello Izak. I am in the process of using your plugin on Grafana 4.6.2. Grafana is hosted on a seperate linux server, which we access through a virtual machine. 

After downloading the docker image we ran the docker run command as described in the readme and got the reporter up and running. Since grafana was installed with default ports, I think this should be enough for it to be good.

After setting up the link, we're unable to open it. If we open in the same tab nothing happens if we open in a new tab we get the error:

error fetching dashboard name-of-dashboard: error obtaining dashboard http://localhost:3000/api/dashboards/db/name. Got status 401 Unauthorized, message: {"message" : "Unauthorized"}

This tells me at least it connects to grafana, but might be some issue due to it running on a separate server (We replace localhost in with the IP of the server in the URL)

Appreciate any help to solve this issue!

EDIT: Appears I was a bit quick in opening this, as there are several other issues up and we've been able to solve some of the issues after following steps there. You can safely close this issue.

**Comment by IzakMarais** [comment]
Hello. 

You should generate an authorisation apitoken in the grafana user interface and pass that along as described in the readme [here](https://github.com/IzakMarais/reporter#query-parameters).

Hope that helps.

**Comment by IzakMarais** [comment]
Confirmed that issue has been solved.
