### ISSUE TITLE
.zip file with all dashboards as PNG's

### ISSUE THREAD

**Issue by HeaverNothing** [IzakMarais/reporter#73]
Hi,
I was wondering if it is possible to pull the images used in the creation of the PDF and zip them all up into one file? It would be helpful where the PDF may not be suitable.

**Comment by IzakMarais** [comment]
I think a collection of images in a zip file might be too far removed from a "report" for me to consider adding it as a feature here. I would need to see support from other users to consider this. 

Can you elaborate a bit on the use case?

**Comment by IzakMarais** [comment]
Closing this for now. It should be pretty easy to fork and modify the existing source code to do this. 

If more people are interested I might re-open this issue.
