### ISSUE TITLE
Scripted dashboard reporting

### ISSUE THREAD

**Issue by tomasbastien** [IzakMarais/reporter#75]
Hi,

I’m trying to get scripted dashboard working with this GitHub project.

Everything is working like a charm using classic dashboard, with uid XXXX and api access : localhost:3000/api/dashboards/uid/XXXX but when it comes to scripted dashboards (instant-generated non-persitant dashboards), things turn out to be more complicated, as I get :
_error fetching dashboard 4000: error obtaining dashboard from http://localhost:3000/api/dashboards/uid/4000. Got Status 404 Not Found, message: {“message”:“Dashboard not found”}_

I tried for set uid in my scripted dashboard script (dashboard.uid is correctly set after this) but it did’nt worked.

UID forced setup :
_dashboard = {
_ rows : [],_
_ uid : XXXX_
};_

Does anyone already tried this and managed to get it functionnal ?

Question will be also ask on a Grafana community for scripted dashboards api access and uid gestion : https://community.grafana.com/t/scripted-dashboard-api-access/9578

Regards,

**Comment by IzakMarais** [comment]
Thanks to @torkelo for his [comment](https://community.grafana.com/t/scripted-dashboard-api-access/9578/2) on the Grafana community: scripted dashboards can't be fetched by API, so the grafana-reporter won't be able to work with them. The suggestion there of generating and importing dashboards will fix this problem.
