### ISSUE TITLE
Reporter over Secure Grafana

### ISSUE THREAD

**Issue by adansbrow** [IzakMarais/reporter#76]
Hi everyone, 

I'm using Granafa with HTTPS and when I try to take report apper the following message: 
![image](https://user-images.githubusercontent.com/40041361/44030643-cac0357a-9ed7-11e8-87ca-46acee599149.png)

Grafana-reporter is opened by the following command line in Debian: 
"grafana-reporter -ip "MYGRAFANASERVERNAME:3000" -port ":8686" -proto "https://"

 Reporter is in version "2.0-1" and Grafana in v5.2.2

Someone know how to fix this? 
Thanks!

**Comment by adansbrow** [comment]
Thanks for the answer @IzakMarais 
It's not running in a docker. It is in a Debian 9. Reporter and Grafana run in the same server too.

**Comment by adansbrow** [comment]
Thanks for the answer @IzakMarais 
It's not running in a docker. It is in a Debian 9. Reporter and Grafana run in the same server too.

**Comment by IzakMarais** [comment]
So my guess is either the grafana server or the http client in the reporter needs ca-certificates to correctly serve or request https. 

Do you see any warning messages about unsigned certificates when you viewing your grafana dashboards in you browser? Of have you maybe added an exception for those and forgot about it?

Looking at this PR commit: https://github.com/IzakMarais/reporter/pull/74/commits/feb715302151f4d745a7759a00eb69cd42cc9d07#diff-3254677a7917c6c01f55212f86c57fbfL13, maybe you can try installing the ca-certificates package on debian?

**Comment by adansbrow** [comment]
Sorry, I really beginner in Linux, the CA-Certificates package are already installed, and the certificates in /etc/ssl/cacerts are up-to-date. 
Any other idea to how fix this?

**Comment by IzakMarais** [comment]
> I haven't do any exception for the certificates.
Did you generate your own (self-signed) certificates for your Grafana? If so, where on the host did you install them?

**Comment by adansbrow** [comment]
@IzakMarais my certificate is generated by Comodo and I already check Root and intermediate in /etc/ssl/cacerts

**Comment by adansbrow** [comment]
@IzakMarais 
Wow, I did not consider that GO Client search in another folder. I'm sorry to suppose this.
In / etc / ssl / certs / has a link for every certificate in Mozilla certs store, but, COMODO intermediate was not there.
After I put certificate inside of the right repository, worked fine.
Thank you so much for all the help, you're the best!

**Comment by IzakMarais** [comment]
Glad to help.
