### ISSUE TITLE
Is there an updated readme file

### ISSUE THREAD

**Issue by devcode2** [IzakMarais/reporter#77]
```
Thanks for taking the time to create this software but I cannot get it installed.

Steps taken are below:
```

`* Download the file`
wget https://github.com/IzakMarais/reporter/archive/master.zip

`* Uncompress the file`
unzip master.zip

`* Change directories`
cd reporter-master

`* Change the default port of 3000 to port **** and port 8686 to ****`
vi cmd/grafana-reporter/main.go

var proto = flag.String("proto", "https://", "Grafana Protocol. Change to 'https://' if Grafana is using https. Reporter will still serve http.")
var ip = flag.String("ip", "mydomain.com:<port_number>", "Grafana IP and port")
var port = flag.String("port", ":<port_number>", "Port to serve on")

`* Add ip to the iptables`
sudo iptables -A INPUT -p tcp -m tcp --dport <port_number> -j ACCEPT
sudo semanage port -a -t http_port_t -p tcp <port_number>
sudo /sbin/service iptables save

`# Set GOPATH in terminal`
set GOPATH=T:/var/lib/grafana/plugins/reporter

vi util/docker-compose.yml
version: '3.2'

services:

  grafana:
    image: grafana/grafana:latest
    environment:
#      GF_USERS_ALLOW_SIGN_UP: "false"
#      GF_AUTH_DISABLE_LOGIN_FORM: "false"
#      GF_AUTH_DISABLE_SIGNOUT_MENU: "false"
#      GF_AUTH_ANONYMOUS_ENABLED: "false"
#      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
    expose:
      - <port_number> 
    ports:
      - "<port_number>:<port_number> "

  reporter:
    image: izakmarais/grafana-reporter:${gr_version:-latest}
    command: "-ip grafana:<port_number> "
    ports:
      - "<port_number> :<port_number>"

`* Create google firewall rule for port `

Name: grafana-reporter
Type: Ingress
Targets: https-server
Filters: IP ranges: 0.0.0.0/0
Protocols / ports: tcp:<port_number>
Action: Allow

`* change the permissions from 0777 to 0775 in report/report.go`
report/report.go:172:   err = os.MkdirAll(rep.imgDirPath(), 0777)
report/report.go:197:   err := os.MkdirAll(rep.tmpDir, 0777)

vi report/report.go

# Set GOPATH in terminal
set GOPATH=T:/var/lib/grafana/plugins/reporter

`* Install golang`
sudo yum install golang

mkdir /usr/lib/golang/src/cmd/grafana-reporter
cp * -R /usr/lib/golang/src/cmd/grafana-reporter

`* Replace the lines below with the directory location because the files cannot be found at the url`

vi grafana-reporter/main.go
vi grafana-reporter/handler.go

#"github.com/IzakMarais/reporter/grafana"
"/usr/lib/golang/src/cmd/grafana-reporter/grafana"
# "github.com/IzakMarais/reporter/report"
"/usr/lib/golang/src/cmd/grafana-reporter/report"
# "github.com/gorilla/mux"
"/usr/lib/golang/src/cmd/grafana-reporter/vendor/github.com/gorilla/mux"

go install -v
handler.go:30:2: import "/usr/lib/golang/src/cmd/grafana-reporter/grafana": cannot import absolute path
handler.go:31:2: import "/usr/lib/golang/src/cmd/grafana-reporter/report": cannot import absolute path
handler.go:32:2: must be imported as github.com/gorilla/mux

**Comment by devcode2** [comment]
Sorry about the big fonts.

**Comment by devcode2** [comment]
I was trying to download the files to my computer so I could change the settings but after many hours today and many hours a few months ago, I cannot get this to install.

I tried to move the code the the plugins directory because I do not want it installed in root's bin.

`GOPATH="/var/lib/grafana/plugins/reporter/cmd/grafana-reporter"`


vi /var/lib/grafana/plugins/reporter/cmd/grafana-reporter/main.go
vi /var/lib/grafana/plugins/reporter/cmd/grafana-reporter/handler.go  

        "cmd/grafana-reporter"
        "cmd/grafana-reporter"
        "../vendor/github.com/gorilla/mux"


go install -v /var/lib/grafana/plugins/reporter/cmd/grafana-reporter/main.go 
cmd/grafana-reporter/main.go:27:2: must be imported as github.com/gorilla/mux
cmd/grafana-reporter/main.go:25:2: cannot find package "cmd/grafana-reporter" in any of:
	/usr/lib/golang/src/cmd/grafana-reporter (from $GOROOT)
	/var/lib/grafana/plugins/reporter/cmd/grafana-reporter/src/cmd/grafana-reporter (from $GOPATH)
[root@pro reporter]# go install -v /var/lib/grafana/plugins/reporter/cmd/grafana-reporter/
can't load package: package /var/lib/grafana/plugins/reporter/cmd/grafana-reporter: import "/var/lib/grafana/plugins/reporter/cmd/grafana-reporter": cannot import absolute path

**Comment by IzakMarais** [comment]
Sorry, but it is difficult to figure out exactly what you want to achieve based on these descriptions. 

The steps in the readme should work, I have recently tested them again.  Have you managed to get it to compile before you start making any changes? Try to just follow the steps in the readme: 
* first set your GOPATH. 
* then use `go get` to fetch the code in stead of `wget` on the release zip file. 
* then install. That will give you a binary image that you can move to where-ever you want it.

**Comment by devcode2** [comment]
Thanks.  I'll try to recall.  I use to be a software engineer where I developed software in C, Perl and Assembly, so I understand some terms and Makefiles but I have not used golang.  Maybe I should read about it.  I think the instructions want to put the files in root's bin but I wanted to place the code in my home directory, then compile the binaries to be placed in the grafana / plugins directory.   

I wanted to edit the configuration files before compiling because some of the permissions are set to 0777, I use https, different ports, and I wanted to change login settings in util/docker-compose.yml
 
My notes above are hard to understand because of the big fonts and some text is not formatted nicely.  Sorry.

I appreciate your help.
Thanks

**Comment by IzakMarais** [comment]
OK, thanks for explaining. Can you confirm that you can get the something running without any modifications?

Most of the things you want to modify seem to be configurable already. For you can use command line flags to change the the port numbers and use https for communicating with the Grafana server. The docker-compose.yml is not dependant on the golang source files directly, it assumes that docker images for grafana and grafana-reporter already exist. So once you have working docker images, you could easily create your own docker compose with the parameters you prefer. 

However if you want to modify the source code, and have the code live live in your home directory, the simplest solution would be to set [GOPATH](https://github.com/golang/go/wiki/GOPATH) to your home directory, then follow the readme instructions, which would output in the binary at $GOPATH/bin. Then you can simply copy the binary from there to where you want it as a post build step.

**Comment by IzakMarais** [comment]
Any further feedback? Have you tried my suggestions?
