### ISSUE TITLE
LaTeX error

### ISSUE THREAD

**Issue by liwei225** [IzakMarais/reporter#78]
hi.
i use docker image to export grafana report,when the report is all in English,it's works well.but some Chinese character in my report.when i export those report,it's fail,
error log like below,how can  i  fix it?

error calling LaTeX preprocessing: "exit status 1". Latex preprocessing failed with output: This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex) restricted \write18 enabled.entering extended mode(./report.texLaTeX2e <2018-04-01> patch level 5(/usr/local/texlive/texmf-dist/tex/latex/base/article.clsDocument Class: article 2014/09/29 v1.4h Standard LaTeX document class(/usr/local/texlive/texmf-dist/tex/latex/base/size10.clo))(/usr/local/texlive/texmf-dist/tex/latex/graphics/graphicx.sty(/usr/local/texlive/texmf-dist/tex/latex/graphics/keyval.sty)(/usr/local/texlive/texmf-dist/tex/latex/graphics/graphics.sty(/usr/local/texlive/texmf-dist/tex/latex/graphics/trig.sty)(/usr/local/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)(/usr/local/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))(/usr/local/texlive/texmf-dist/tex/latex/geometry/geometry.sty(/usr/local/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)(/usr/local/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)(/usr/local/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty))No file report.aux.(/usr/local/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii[Loading MPS to PDF converter (version 2006.09.02).]) (/usr/local/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty(/usr/local/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)(/usr/local/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty(/usr/local/texlive/texmf-dist/tex/generic/oberdiek/kvdefinekeys.sty(/usr/local/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)))(/usr/local/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty(/usr/local/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty(/usr/local/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty(/usr/local/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))(/usr/local/texlive/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty)(/usr/local/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))*geometry* driver: auto-detecting*geometry* detected driver: pdftex! Package inputenc Error: Unicode character ҵ (U+4E1A)(inputenc)                not set up for use with LaTeX.See the inputenc package documentation for explanation.Type  H <return>  for immediate help. ...                                                                                                l.11 \maketitle               !  ==> Fatal error occurred, no output PDF file produced!Transcript written on report.log.

**Comment by IzakMarais** [comment]
> Package inputenc Error: Unicode character ҵ (U+4E1A)(inputenc) not set up for use with LaTeX

Interseting. This will have to be investigated.

**Comment by IzakMarais** [comment]
Possibly related to #46

**Comment by xiaoyao1114** [comment]
The same problem,How to solve?

**Comment by IzakMarais** [comment]
This is still an open bug. If you want to do a PR for a fix I am open to that. Alternatively it will have to wait until I find time to have a look. I do not have a schedule in mind for that.

**Comment by IzakMarais** [comment]
See this comment for the fix: https://github.com/IzakMarais/reporter/issues/46#issuecomment-506584203
