### ISSUE TITLE
There is no HTTP status code check

### ISSUE THREAD

**Issue by msoedov** [IzakMarais/reporter#8]
I have a case when grafana returns 404 for some reason and it causes panics in the png processing. I guess it would be nice to skip panel if grafana api returns bad response.
The piece of code I'm talking about: https://github.com/IzakMarais/reporter/blob/master/grafana/api.go#L79

**Comment by IzakMarais** [comment]
Yes, I have been encountering this issue as well. It will be addressed in the next release.

**Comment by IzakMarais** [comment]
Fixed by https://github.com/IzakMarais/reporter/pull/3
