### ISSUE TITLE
Dashboard unauthorized

### ISSUE THREAD

**Issue by HKby** [IzakMarais/reporter#83]
Hi I have received the error message as below: 

Any idea how to fix it? many thanks

error fetching dashboard yf8ixI0iz: error obtaining dashboard from http://localhost:3000/api/dashboards/uid/yf8ixI0iz. Got Status 401 Unauthorized, message: {"message":"Unauthorized"}

**Comment by PiotrekOpole** [comment]
Hi. The answer is in topic https://github.com/IzakMarais/reporter/issues/49

**Comment by HKby** [comment]
Opppsss, my bad. I haven't checked the previous answer carefully. Many thanks

**Comment by IzakMarais** [comment]
@PiotrekOpole Thanks for answering.
