### ISSUE TITLE
error creating img directory:mkdir tmp: not a directory

### ISSUE THREAD

**Issue by HKby** [IzakMarais/reporter#84]
Hi anyone know how to fix this issue

error rendering PNGs in parralel for dash {Title:test Description: VariableValues: Rows:[] Panels:[{Id:4 Type:graph Title:Panel Title}]}: error creating img directory:mkdir tmp: not a directory

**Comment by IzakMarais** [comment]
Interesting, I have never seen this error message in practice before. It gets generated from [here](https://github.com/IzakMarais/reporter/blob/1d545455069343801e1c250cbab2787dc16498a5/report/report.go#L174). It should be trying to create a local directory `tmp-<some-uuid>/images`. 

1. Are you getting this error consistently? 
2. What OS are you using? 
3. Are you sure the reporter process is being executed from a drive where it has write access?

**Comment by HKby** [comment]
Hi @IzakMarais , After I pull down the docker, just make our OS consistent. It works perfect! Many thanks.
