### ISSUE TITLE
report not working

### ISSUE THREAD

**Issue by yuvarajanlga** [IzakMarais/reporter#85]
Hi

Not able to download the pdf , but  i am able to access the dashboard using "http://publicip:3000/api/dashboards/uid/****?var-dstip=xxx.xxx.xxx.xxx%2F28"

Please let me know, what could be the issues ?

<p>2018/09/25 11:33:32 Reporter called
2018/09/25 11:33:32 Called with api Token: ***************
2018/09/25 11:33:32 Called with variable: var-dstip [xxx.xxx.xxx.xxx/28]
2018/09/25 11:33:32 Called with dashboard: *****
2018/09/25 11:33:32 Called with time range: {now-7d now}
2018/09/25 11:33:32 Connecting to dashboard at http://publicip:3000/api/dashboards/uid/****?var-dstip=xxx.xxx.xxx.xxx%2F28
2018/09/25 11:34:02 Error generating report: error fetching dashboard *****: error executing getDashboard request for http://publicip:3000/api/dashboards/uid/****?var-dstip=xxx.xxx.xxx.xxx%2F28: Get http://publicip:3000/api/dashboards/uid/*****?var-dstip=xxx.xxx.xxx.xxx%2F28: dial tcp publicip:3000: i/o timeout </p>

**Comment by yuvarajanlga** [comment]
fixed by myself.

steps:- 

1. ran grafana-reporter service with grafana ip as localhost
2. phantomjs binary file was not present under  grafana phantomjs directory.

**Comment by IzakMarais** [comment]
Glad to hear you got it working.
