### ISSUE TITLE
GO variable name for logged in user

### ISSUE THREAD

**Issue by yuvarajanlga** [IzakMarais/reporter#87]
Hi,

I want to display the loggedin user on the report. is there any go variable that i can use in my template to show the loggedin user on my report ?

**Comment by IzakMarais** [comment]
No that is not currently possible. It also doesn't seem like a common request so I doubt I will add it.

**Comment by yuvarajanlga** [comment]
is there any way to we can retrive the class name  ? could you please let me know the concept, then we will try ourself.

**Comment by IzakMarais** [comment]
Sure, you will have to understand golang text templating (see [here](https://golang.org/pkg/text/template/) and [here](https://dlintw.github.io/gobyexample/public/text-template.html)). Then you just need to pass the data you want into the template. In the reporter source code, this is done [here](https://github.com/IzakMarais/reporter/blob/master/report/report.go#L207)

**Comment by yuvarajanlga** [comment]
thank you. 

i m wondering how to fetch the loggedin username ? 

As per grafana docs, need to use "contextSrv.user" to fetch the logged in user. But it will work only with javascript.  And other way to fetch the username is from nginx header information.   Both the solution doesnt work for me. 

i have gone through report.go , from the below struct i need to add username . but i dont know what to do here. can you guide me in the correct path. 

type templData struct {
		grafana.Dashboard
		grafana.TimeRange
		grafana.Client
	}

**Comment by IzakMarais** [comment]
Yes you would need to add the username to that sctruct and then reference the variable it in the LaTex template.

The reporter interfaces with Grafana exclusively via the Grafana HTTP API. I don't think it is possible to retrieve the logged in user via an external API since that question wouldn't make sense (there could be multiple users logged in).

**Comment by yuvarajanlga** [comment]
Yes thats right. But is there any way we can achieve this ?

**Comment by IzakMarais** [comment]
> Below one will fetch the actual user using API

Interesting, I was not aware of that end point. It will only show the "grafana-reporter" user which I assume is not what you want. 

I don't think what you are trying to achieve is possible by modifying only the reporter source code. If you want the user logged into grafana who clicked on a "generate dashboard" link you will need to also modify grafana source code. It should retrieve the current logged in user and pass along that as an extra query parameter to the reporter. Then you will have to modify the reporter to accept that extra query parameter and use it in the text template struct.

**Comment by yuvarajanlga** [comment]
thanks.. i am not sure whether grafana will access my request.
