### ISSUE TITLE
Worldmap panel not displaying properly.

### ISSUE THREAD

**Issue by yuvarajanlga** [IzakMarais/reporter#88]
![screen shot 2018-10-02 at 2 57 01 pm](https://user-images.githubusercontent.com/21257627/46333648-abb2b100-c653-11e8-8911-478b4e8e4486.png)

Worldmap panel is not displaying properly in the report.  Please let me know how to fix it.

**Comment by IzakMarais** [comment]
This is likely an issue with the panel itself. Many of the third party panels do not render nicely when used with the Grafana direct link rendered image feature. You can test completely without the reporter and then log a bug with the panel maintainers. 

To test it, in the Grafana UI, click on the _panel heading -> share -> direct link rendered image_.

**Comment by yuvarajanlga** [comment]
yes i tried as you suggested. i will update the grafana worldmap panel community .

**Comment by IzakMarais** [comment]
Thanks, I'm closing this issue for now. Please link here if you create a github issue with the Worldmap panel. Then others can know which issue to follow.
