### ISSUE TITLE
Templating init failed : network error

### ISSUE THREAD

**Issue by Sha90** [IzakMarais/reporter#89]
I followed the read me steps, able to start up the docker container. My grafana shows the values. however, when report generated, all panels are in report, but no data. And below error is shown. 
Could you please help me on this.

Thanks.
![image](https://user-images.githubusercontent.com/14327712/46365674-20481880-c671-11e8-8016-c9befbc28160.png)

**Comment by IzakMarais** [comment]
Interesting, I have never seen that before. 
* If you try to render the images from the grafana GUI by clicking _Panel heading -> Share -> direct link rendered image_ , does it give the same error? 
* Are there any clues in the Grafana server log file?

**Comment by Sha90** [comment]
Hey,
Thanks for your response. I tried the above, share -> direct link step. it worked fine. Didn't receive any errors. Also in the grafana and and pdf generator logs no clues.

Another thing I observed is,
I have multiple dashboards with different data sources like prometheus and influxdb.  It is not able to generate the pdf for the corresponding dashboard. It always generates for the default dashboard.
Ex - 
1) have pdf generator link on dashboard 1 and dashboard 2
2) generate a pdf from dashboard 1 - panels are generated in pdf with network error for dashboard 1
3) generate a pdf from dashboard 2 - panels are generated in pdf for dashboard 1. there seems to be some caching issue here.

To provide context on my setup and different ways I tried so far,
1) I am running prometheus, influxdb and grafana as docker containers.
2) All my containers are running in default docker network bridge.
3) pdf generator container is running in host network.
4) All iptable rules are default, so no issues in communicating between networks (i.e., between host and bridge)

Another way I tried is,
Attached the pdf generator container to bridge network and passed the ip string of grafana. Still no luck.

Apologies for long message.
Thanks in Advance.

**Comment by Sha90** [comment]
Final config used with docker containers.
1) all data sources in grafana should use proxy(default) access.
2) all data source containers (like influxdb and prometheus) and grafana need to be in same network.

Closing this bug now. Thank you.

**Comment by IzakMarais** [comment]
Thanks for giving feedback, hopefully others will find it useful if they have similar problems. I have never used grafana with non-proxy datasource or datasources on different networks.
