### ISSUE TITLE
Values are different from grafana panels

### ISSUE THREAD

**Issue by gaetanquentin** [IzakMarais/reporter#93]
I just noticed that table values printed on pdf were  very different from grafana dashboard.

Versions:
-----------
grafana 5.2
grafana-reporter 2.1-0 

look specialy at the total on the table:

here are screenshots to compare:

time in grafana:
![image](https://user-images.githubusercontent.com/5774881/46609437-2eca8000-cb08-11e8-835f-f2daf9befc6a.png)

panel in grafana:
![image](https://user-images.githubusercontent.com/5774881/46609425-23775480-cb08-11e8-8f39-8588263fdec7.png)

time in grafana-reporter:
![image](https://user-images.githubusercontent.com/5774881/46609496-62a5a580-cb08-11e8-9d2c-46f8ec3a62d9.png)

panel in grafana-reporter:
![image](https://user-images.githubusercontent.com/5774881/46609516-76e9a280-cb08-11e8-99e6-c1ec25acd31d.png)

**Comment by IzakMarais** [comment]
Hmm this is strange. Looking through the code there is no difference in the way tables are handled compared to other panels w.r.g. time range. 

Have you observed this behaviour across mulitple different reports and time ranges?

Can you test the rendering of this panel using the Grafana UI directly? The reporter uses the _Direct link rendered image_ share functionality to request the pngs. You can access this for the various panels in the report from the Grafana UI by clicking on the _panel heading -> share -> direct link rendered image_. It will be interesting to see if the same differences are observed there too.

**Comment by gaetanquentin** [comment]
yes all panels and time range are concerned.

with direct link, no problem

**Comment by gaetanquentin** [comment]
i have tested this solution:
 https://gist.github.com/svet-b/1ad0656cd3ce0e1a633e16eb20f66425

and it works fine too

**Comment by gaetanquentin** [comment]
FYI the problem is not  only in table content, in graph values too.

**Comment by IzakMarais** [comment]
> yes all panels and time range are concerned. with direct link, no problem
> FYI the problem is not only in table content, in graph values too.

This is a first. 

So are the time ranges different in the direct link rendered image compared to the report panels? If it is in the graph  values too, lets focus on those, since it is easier to see the time range. 

Can you post some more images or explanations showing clearly on a graph panel how the values and time range differ form the dashboard / direct link image compared to the report? In you original image, it looks like the time range and values in the graph is good.

Do you think it might be related to the timezone on the server?

**Comment by IzakMarais** [comment]
Any further feedback? Have you had time to look at the questions from my previous post?
