### ISSUE TITLE
Timeout when Grafana dashboard is generated by Zabbix

### ISSUE THREAD

**Issue by mrbitsdcf** [IzakMarais/reporter#97]
Hello, @IzakMarais

Thanks a lot for develop this nice tool. Hope you can help me.

When trying to generate a dashboard using Zabbix API in Grafana, we got the following errors:

2018/11/11 11:34:23 Reporter called
2018/11/11 11:34:23 Called with api Token: 
2018/11/11 11:34:23 Called with variable: var-host [customerbla-web-1]
2018/11/11 11:34:23 Called with variable: var-netif [All]
2018/11/11 11:34:23 Called with variable: var-disk [dm-]
2018/11/11 11:34:23 Called with variable: var-partition [/]
2018/11/11 11:34:23 Called with variable: var-hostinfo [Vendor]
2018/11/11 11:34:23 Called with variable: var-group [CustomerBla]
2018/11/11 11:34:23 Called with dashboard: 000000176
2018/11/11 11:34:23 Called with time range: {now-24h now}
2018/11/11 11:34:23 Connecting to dashboard at http://localhost:3000/api/dashboards/uid/000000176?var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F
2018/11/11 11:34:23 Populated dashboard datastructure: {Title:System Description: VariableValues:All, dm-, /, Vendor, CustomerBla, customerbla-web-1 Rows:[] Panels:[{Id:10 Type:text Title:} {Id:98 Type:singlestat Title:Instance Provider} {Id:99 Type:singlestat Title:Instance Type} {Id:100 Type:singlestat Title:Instance ID} {Id:4 Type:singlestat Title:System uptime} {Id:6 Type:singlestat Title:Available RAM} {Id:7 Type:singlestat Title:Swap Free} {Id:13 Type:grafana-piechart-panel Title:Disk Space (\$partition)} {Id:5 Type:singlestat Title:Process Running} {Id:1 Type:graph Title:CPU} {Id:12 Type:table Title:CPU Operation} {Id:34 Type:graph Title:Available RAM} {Id:2 Type:graph Title:System load} {Id:88 Type:table Title:Top CPU Consumers} {Id:89 Type:table Title:Top RAM Consumers} {Id:90 Type:table Title:Top SWAP Consumers} {Id:3 Type:graph Title:Network traffic on \$netif} {Id:35 Type:graph Title:Packets on \$netif} {Id:36 Type:graph Title:Packet Loss on \$netif interface (incremental)} {Id:37 Type:graph Title:Packet loss on \$netif interface (delta)} {Id:8 Type:graph Title:I/O Activity (ops) (\$disk)} {Id:82 Type:graph Title:Disk utilization queue (\%) [\$disk]} {Id:86 Type:graph Title:Disk Average wait [\$disk]} {Id:87 Type:graph Title:Disk Ops Average [\$disk]} {Id:91 Type:graph Title:Volume Growth [\$partition]} {Id:14 Type:alexanderzobnin-zabbix-triggers-panel Title:Last Events}]}
2018/11/11 11:34:23 Downloading image  10 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=100&panelId=10&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:23 Downloading image  98 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=150&panelId=98&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=300
2018/11/11 11:34:23 Downloading image  99 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=150&panelId=99&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=300
2018/11/11 11:34:23 Downloading image  100 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=150&panelId=100&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=300
2018/11/11 11:34:23 Downloading image  4 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=150&panelId=4&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=300
2018/11/11 11:34:27 Downloading image  6 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=150&panelId=6&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=300
2018/11/11 11:34:27 Downloading image  7 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=150&panelId=7&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=300
2018/11/11 11:34:27 Downloading image  13 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=13&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:27 Downloading image  5 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=150&panelId=5&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=300
2018/11/11 11:34:29 Downloading image  1 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=1&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:29 Downloading image  12 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=12&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:30 Downloading image  34 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=34&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:30 Downloading image  2 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=2&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:32 Downloading image  88 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=88&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:32 Downloading image  89 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=89&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:33 Downloading image  90 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=90&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:33 Downloading image  3 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=3&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:35 Downloading image  35 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=35&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:35 Downloading image  36 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=36&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:36 Downloading image  37 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=37&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:36 Downloading image  8 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=8&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:37 Error obtaining render: <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <meta name="theme-color" content="#000">

    <title>Grafana - Error</title>

    <base href="/" />

    <link rel="stylesheet" href="public/build/grafana.dark.css?v">

    <link rel="icon" type="image/png" href="public/img/fav32.png">
    <link rel="mask-icon" href="public/img/grafana_mask_icon.svg" color="#F05A28">

  </head>

  <body class="theme-dark">
    <div class="main-view">
      <div class="page-container">
        <div class="page-header">
          <div class="page-header__inner">
            <span class="page-header__logo">
              <i class="page-header__icon fa fa-frown-o"></i>
            </span>
            <div class="page-header__info-block">
              <h1 class="page-header__title">
                <a class="text-link" href="login">Grafana</a><span> / Server Error</span><span></span>
              </h1>
              <div class="page-header__sub-title">Sadly something went wrong</div>
            </div>
          </div>
        </div>
      </div>
      <div class="page-container page-body ng-scope" style="padding: 2rem">
        <div class="alert">
          <div class="alert-icon"><i class="fa fa-exclamation-triangle"></i></div>
          <div class="alert-body">
            <div class="alert-title">Timeout error. You can set timeout in seconds with &amp;timeout url parameter</div>
          </div>
        </div>
        <br />
        
        <div style="padding: 2rem 0 0">
          <p>Check the Grafana server logs for the detailed error message.</p>
        </div>
      </div>
    </div>
  </body>
</html>

2018/11/11 11:34:37 Error creating image for panel: error getting panel {Id:13 Type:grafana-piechart-panel Title:Disk Space (\$partition)}: Error obtaining render: 500 Internal Server Error
2018/11/11 11:34:37 Error generating report: error rendering PNGs in parralel for dash {Title:System Description: VariableValues:Vendor, CustomerBla, customerbla-web-1, All, dm-, / Rows:[] Panels:[{Id:10 Type:text Title:} {Id:98 Type:singlestat Title:Instance Provider} {Id:99 Type:singlestat Title:Instance Type} {Id:100 Type:singlestat Title:Instance ID} {Id:4 Type:singlestat Title:System uptime} {Id:6 Type:singlestat Title:Available RAM} {Id:7 Type:singlestat Title:Swap Free} {Id:13 Type:grafana-piechart-panel Title:Disk Space (\$partition)} {Id:5 Type:singlestat Title:Process Running} {Id:1 Type:graph Title:CPU} {Id:12 Type:table Title:CPU Operation} {Id:34 Type:graph Title:Available RAM} {Id:2 Type:graph Title:System load} {Id:88 Type:table Title:Top CPU Consumers} {Id:89 Type:table Title:Top RAM Consumers} {Id:90 Type:table Title:Top SWAP Consumers} {Id:3 Type:graph Title:Network traffic on \$netif} {Id:35 Type:graph Title:Packets on \$netif} {Id:36 Type:graph Title:Packet Loss on \$netif interface (incremental)} {Id:37 Type:graph Title:Packet loss on \$netif interface (delta)} {Id:8 Type:graph Title:I/O Activity (ops) (\$disk)} {Id:82 Type:graph Title:Disk utilization queue (\%) [\$disk]} {Id:86 Type:graph Title:Disk Average wait [\$disk]} {Id:87 Type:graph Title:Disk Ops Average [\$disk]} {Id:91 Type:graph Title:Volume Growth [\$partition]} {Id:14 Type:alexanderzobnin-zabbix-triggers-panel Title:Last Events}]}: error getting panel {Id:13 Type:grafana-piechart-panel Title:Disk Space (\$partition)}: Error obtaining render: 500 Internal Server Error
2018/11/11 11:34:38 Downloading image  82 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=82&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:38 Downloading image  86 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=86&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:39 Downloading image  87 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=87&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:40 Downloading image  91 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=91&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:34:41 Downloading image  14 http://localhost:3000/render/d-solo/000000176/_?from=now-24h&height=500&panelId=14&theme=light&to=now&var-disk=dm-&var-group=CustomerBla&var-host=customerbla-web-1&var-hostinfo=Vendor&var-netif=All&var-partition=%2F&width=1000
2018/11/11 11:35:29 Error obtaining render for panel {Id:13 Type:grafana-piechart-panel Title:Disk Space (\$partition)}, Status: 500, Retrying after 10s...

My guess is that this is some timeout related issue and I know we can pass &timeout=x to Grafana API URL. I would like to know how to pass it using your great tool.

Thanks a lot

**Comment by IzakMarais** [comment]
> Id:13 Type:grafana-piechart-panel Title:Disk Space ($partition)}: Error obtaining render: 500 Internal Server Error

Maybe that is cause. Have you tried simplifying the problem. If you create a dashboard with just that Disk Space pie chart panel, does it work?

**Comment by IzakMarais** [comment]
I think this duplicates https://github.com/IzakMarais/reporter/issues/17. 
Which is caused by an open bug in Grafana: https://github.com/grafana/piechart-panel/issues/131
