### ISSUE TITLE
Unauthorized error using API to export PDF

### ISSUE THREAD

**Issue by mfarook** [IzakMarais/reporter#98]
I had successfully setup Reporter in my local system. I tried exporting to pdf using api "http://localhost:8686/api/v5/report/4LC-RVfiz" Am getting an error error fetching dashboard 4LC-RVfiz: error obtaining dashboard from http://localhost:3000/api/dashboards/uid/4LC-RVfiz. Got Status 401 Unauthorized, message: {"message":"Unauthorized"} . Is this because of API key issue?if so, how to create API key using Grafanna?

**Comment by IzakMarais** [comment]
> if so, how to create API key using Grafanna?
The Grafana docs explain how to do this via the Grafana UI. 

The reporter readme explains how to pass the key along to grafana as a query parameter.

**Comment by mfarook** [comment]
Thanks
